// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel
{
    /// <summary>
    /// Resource representing an action execution triggered by a function.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Zitadel = scoretechnologies.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @default = new Zitadel.ActionTarget("default", new()
    ///     {
    ///         Name = "token-enricher",
    ///         Endpoint = "https://example.com/oidc/enrich",
    ///         TargetType = "REST_CALL",
    ///         Timeout = "10s",
    ///         InterruptOnError = true,
    ///     });
    /// 
    ///     var defaultActionExecutionFunction = new Zitadel.ActionExecutionFunction("default", new()
    ///     {
    ///         Name = "preaccesstoken",
    ///         TargetIds = new[]
    ///         {
    ///             @default.Id,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// function name: preuserinfo, preaccesstoken, or presamlresponse
    /// 
    /// ```sh
    /// $ pulumi import zitadel:index/actionExecutionFunction:ActionExecutionFunction imported 'preaccesstoken'
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/actionExecutionFunction:ActionExecutionFunction")]
    public partial class ActionExecutionFunction : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the function. Valid values: `Preuserinfo`, `Preaccesstoken`, `Presamlresponse`
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The list of target IDs to call.
        /// </summary>
        [Output("targetIds")]
        public Output<ImmutableArray<string>> TargetIds { get; private set; } = null!;


        /// <summary>
        /// Create a ActionExecutionFunction resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ActionExecutionFunction(string name, ActionExecutionFunctionArgs args, CustomResourceOptions? options = null)
            : base("zitadel:index/actionExecutionFunction:ActionExecutionFunction", name, args ?? new ActionExecutionFunctionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ActionExecutionFunction(string name, Input<string> id, ActionExecutionFunctionState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/actionExecutionFunction:ActionExecutionFunction", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/scoretechnologies",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ActionExecutionFunction resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ActionExecutionFunction Get(string name, Input<string> id, ActionExecutionFunctionState? state = null, CustomResourceOptions? options = null)
        {
            return new ActionExecutionFunction(name, id, state, options);
        }
    }

    public sealed class ActionExecutionFunctionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the function. Valid values: `Preuserinfo`, `Preaccesstoken`, `Presamlresponse`
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("targetIds")]
        private InputList<string>? _targetIds;

        /// <summary>
        /// The list of target IDs to call.
        /// </summary>
        public InputList<string> TargetIds
        {
            get => _targetIds ?? (_targetIds = new InputList<string>());
            set => _targetIds = value;
        }

        public ActionExecutionFunctionArgs()
        {
        }
        public static new ActionExecutionFunctionArgs Empty => new ActionExecutionFunctionArgs();
    }

    public sealed class ActionExecutionFunctionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the function. Valid values: `Preuserinfo`, `Preaccesstoken`, `Presamlresponse`
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("targetIds")]
        private InputList<string>? _targetIds;

        /// <summary>
        /// The list of target IDs to call.
        /// </summary>
        public InputList<string> TargetIds
        {
            get => _targetIds ?? (_targetIds = new InputList<string>());
            set => _targetIds = value;
        }

        public ActionExecutionFunctionState()
        {
        }
        public static new ActionExecutionFunctionState Empty => new ActionExecutionFunctionState();
    }
}
