// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel
{
    /// <summary>
    /// Resource representing an action execution triggered by an event.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Zitadel = scoretechnologies.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @default = new Zitadel.ActionTarget("default", new()
    ///     {
    ///         Name = "event-webhook",
    ///         Endpoint = "https://example.com/webhooks/events",
    ///         TargetType = "REST_ASYNC",
    ///         Timeout = "10s",
    ///         InterruptOnError = false,
    ///     });
    /// 
    ///     var defaultActionExecutionEvent = new Zitadel.ActionExecutionEvent("default", new()
    ///     {
    ///         Event = "user.human.added",
    ///         TargetIds = new[]
    ///         {
    ///             @default.Id,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// event:name for specific event, group:name for event group, all for all events
    /// 
    /// ```sh
    /// $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'event:user.human.added'
    /// $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'group:user.human'
    /// $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'all'
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/actionExecutionEvent:ActionExecutionEvent")]
    public partial class ActionExecutionEvent : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Trigger on all events.
        /// </summary>
        [Output("all")]
        public Output<bool?> All { get; private set; } = null!;

        /// <summary>
        /// The specific event to trigger on, e.g., `user.human.added`
        /// </summary>
        [Output("event")]
        public Output<string?> Event { get; private set; } = null!;

        /// <summary>
        /// The event group to trigger on, e.g., `user.human`
        /// </summary>
        [Output("group")]
        public Output<string?> Group { get; private set; } = null!;

        /// <summary>
        /// The list of target IDs to call.
        /// </summary>
        [Output("targetIds")]
        public Output<ImmutableArray<string>> TargetIds { get; private set; } = null!;


        /// <summary>
        /// Create a ActionExecutionEvent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ActionExecutionEvent(string name, ActionExecutionEventArgs? args = null, CustomResourceOptions? options = null)
            : base("zitadel:index/actionExecutionEvent:ActionExecutionEvent", name, args ?? new ActionExecutionEventArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ActionExecutionEvent(string name, Input<string> id, ActionExecutionEventState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/actionExecutionEvent:ActionExecutionEvent", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/scoretechnologies",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ActionExecutionEvent resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ActionExecutionEvent Get(string name, Input<string> id, ActionExecutionEventState? state = null, CustomResourceOptions? options = null)
        {
            return new ActionExecutionEvent(name, id, state, options);
        }
    }

    public sealed class ActionExecutionEventArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Trigger on all events.
        /// </summary>
        [Input("all")]
        public Input<bool>? All { get; set; }

        /// <summary>
        /// The specific event to trigger on, e.g., `user.human.added`
        /// </summary>
        [Input("event")]
        public Input<string>? Event { get; set; }

        /// <summary>
        /// The event group to trigger on, e.g., `user.human`
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        [Input("targetIds")]
        private InputList<string>? _targetIds;

        /// <summary>
        /// The list of target IDs to call.
        /// </summary>
        public InputList<string> TargetIds
        {
            get => _targetIds ?? (_targetIds = new InputList<string>());
            set => _targetIds = value;
        }

        public ActionExecutionEventArgs()
        {
        }
        public static new ActionExecutionEventArgs Empty => new ActionExecutionEventArgs();
    }

    public sealed class ActionExecutionEventState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Trigger on all events.
        /// </summary>
        [Input("all")]
        public Input<bool>? All { get; set; }

        /// <summary>
        /// The specific event to trigger on, e.g., `user.human.added`
        /// </summary>
        [Input("event")]
        public Input<string>? Event { get; set; }

        /// <summary>
        /// The event group to trigger on, e.g., `user.human`
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        [Input("targetIds")]
        private InputList<string>? _targetIds;

        /// <summary>
        /// The list of target IDs to call.
        /// </summary>
        public InputList<string> TargetIds
        {
            get => _targetIds ?? (_targetIds = new InputList<string>());
            set => _targetIds = value;
        }

        public ActionExecutionEventState()
        {
        }
        public static new ActionExecutionEventState Empty => new ActionExecutionEventState();
    }
}
