// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel
{
    public static class GetActionExecutionRequest
    {
        /// <summary>
        /// Datasource representing an action execution triggered by a request.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zitadel = scoretechnologies.Zitadel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Zitadel.GetActionExecutionRequest.Invoke(new()
        ///     {
        ///         Id = "method:/zitadel.session.v2.SessionService/ListSessions",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetActionExecutionRequestResult> InvokeAsync(GetActionExecutionRequestArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetActionExecutionRequestResult>("zitadel:index/getActionExecutionRequest:getActionExecutionRequest", args ?? new GetActionExecutionRequestArgs(), options.WithDefaults());

        /// <summary>
        /// Datasource representing an action execution triggered by a request.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zitadel = scoretechnologies.Zitadel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Zitadel.GetActionExecutionRequest.Invoke(new()
        ///     {
        ///         Id = "method:/zitadel.session.v2.SessionService/ListSessions",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetActionExecutionRequestResult> Invoke(GetActionExecutionRequestInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetActionExecutionRequestResult>("zitadel:index/getActionExecutionRequest:getActionExecutionRequest", args ?? new GetActionExecutionRequestInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Datasource representing an action execution triggered by a request.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zitadel = scoretechnologies.Zitadel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Zitadel.GetActionExecutionRequest.Invoke(new()
        ///     {
        ///         Id = "method:/zitadel.session.v2.SessionService/ListSessions",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetActionExecutionRequestResult> Invoke(GetActionExecutionRequestInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetActionExecutionRequestResult>("zitadel:index/getActionExecutionRequest:getActionExecutionRequest", args ?? new GetActionExecutionRequestInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetActionExecutionRequestArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `All`/`all:`
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetActionExecutionRequestArgs()
        {
        }
        public static new GetActionExecutionRequestArgs Empty => new GetActionExecutionRequestArgs();
    }

    public sealed class GetActionExecutionRequestInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `All`/`all:`
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetActionExecutionRequestInvokeArgs()
        {
        }
        public static new GetActionExecutionRequestInvokeArgs Empty => new GetActionExecutionRequestInvokeArgs();
    }


    [OutputType]
    public sealed class GetActionExecutionRequestResult
    {
        /// <summary>
        /// Trigger on all requests.
        /// </summary>
        public readonly bool All;
        /// <summary>
        /// The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `All`/`all:`
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The gRPC method to trigger on.
        /// </summary>
        public readonly string Method;
        /// <summary>
        /// The gRPC service to trigger on.
        /// </summary>
        public readonly string Service;
        /// <summary>
        /// The list of target IDs to call.
        /// </summary>
        public readonly ImmutableArray<string> TargetIds;

        [OutputConstructor]
        private GetActionExecutionRequestResult(
            bool all,

            string id,

            string method,

            string service,

            ImmutableArray<string> targetIds)
        {
            All = all;
            Id = id;
            Method = method;
            Service = service;
            TargetIds = targetIds;
        }
    }
}
