// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel
{
    public static class GetOrganizationMetadata
    {
        /// <summary>
        /// Datasource representing a metadata entry of an organization in ZITADEL.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zitadel = scoretechnologies.Zitadel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Zitadel.GetOrganizationMetadata.Invoke(new()
        ///     {
        ///         OrganizationId = "123456789012345678",
        ///         Key = "example_key",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["metadataValue"] = @default.Apply(@default =&gt; @default.Apply(getOrganizationMetadataResult =&gt; getOrganizationMetadataResult.Value)),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetOrganizationMetadataResult> InvokeAsync(GetOrganizationMetadataArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetOrganizationMetadataResult>("zitadel:index/getOrganizationMetadata:getOrganizationMetadata", args ?? new GetOrganizationMetadataArgs(), options.WithDefaults());

        /// <summary>
        /// Datasource representing a metadata entry of an organization in ZITADEL.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zitadel = scoretechnologies.Zitadel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Zitadel.GetOrganizationMetadata.Invoke(new()
        ///     {
        ///         OrganizationId = "123456789012345678",
        ///         Key = "example_key",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["metadataValue"] = @default.Apply(@default =&gt; @default.Apply(getOrganizationMetadataResult =&gt; getOrganizationMetadataResult.Value)),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetOrganizationMetadataResult> Invoke(GetOrganizationMetadataInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetOrganizationMetadataResult>("zitadel:index/getOrganizationMetadata:getOrganizationMetadata", args ?? new GetOrganizationMetadataInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Datasource representing a metadata entry of an organization in ZITADEL.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zitadel = scoretechnologies.Zitadel;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Zitadel.GetOrganizationMetadata.Invoke(new()
        ///     {
        ///         OrganizationId = "123456789012345678",
        ///         Key = "example_key",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["metadataValue"] = @default.Apply(@default =&gt; @default.Apply(getOrganizationMetadataResult =&gt; getOrganizationMetadataResult.Value)),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetOrganizationMetadataResult> Invoke(GetOrganizationMetadataInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetOrganizationMetadataResult>("zitadel:index/getOrganizationMetadata:getOrganizationMetadata", args ?? new GetOrganizationMetadataInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetOrganizationMetadataArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Key of the metadata entry
        /// </summary>
        [Input("key", required: true)]
        public string Key { get; set; } = null!;

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Input("organizationId", required: true)]
        public string OrganizationId { get; set; } = null!;

        public GetOrganizationMetadataArgs()
        {
        }
        public static new GetOrganizationMetadataArgs Empty => new GetOrganizationMetadataArgs();
    }

    public sealed class GetOrganizationMetadataInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Key of the metadata entry
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Input("organizationId", required: true)]
        public Input<string> OrganizationId { get; set; } = null!;

        public GetOrganizationMetadataInvokeArgs()
        {
        }
        public static new GetOrganizationMetadataInvokeArgs Empty => new GetOrganizationMetadataInvokeArgs();
    }


    [OutputType]
    public sealed class GetOrganizationMetadataResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Key of the metadata entry
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// ID of the organization
        /// </summary>
        public readonly string OrganizationId;
        /// <summary>
        /// Value of the metadata entry
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetOrganizationMetadataResult(
            string id,

            string key,

            string organizationId,

            string value)
        {
            Id = id;
            Key = key;
            OrganizationId = organizationId;
            Value = value;
        }
    }
}
