// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel
{
    /// <summary>
    /// Resource representing an organization in ZITADEL. Uses the org/v2 API and **requires ZITADEL 4.x**. For deployments that must support ZITADEL 3.x, use `zitadel.Org` instead (it automatically falls back to the management API).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Zitadel = scoretechnologies.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @default = new Zitadel.Organization("default", new()
    ///     {
    ///         Name = "terraform-test",
    ///     });
    /// 
    ///     var withAdmins = new Zitadel.Organization("with_admins", new()
    ///     {
    ///         Name = "terraform-test-with-admins",
    ///         Admins = new[]
    ///         {
    ///             new Zitadel.Inputs.OrganizationAdminArgs
    ///             {
    ///                 UserId = "123456789012345678",
    ///                 Roles = new[]
    ///                 {
    ///                     "ORG_OWNER",
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    ///     var withCustomId = new Zitadel.Organization("with_custom_id", new()
    ///     {
    ///         Name = "terraform-test-custom",
    ///         OrgId = "custom-org-id-123",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import zitadel:index/organization:Organization imported '123456789012345678'
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/organization:Organization")]
    public partial class Organization : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of users to be granted organization admin roles
        /// </summary>
        [Output("admins")]
        public Output<ImmutableArray<Outputs.OrganizationAdmin>> Admins { get; private set; } = null!;

        /// <summary>
        /// Name of the org
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Custom unique identifier for the organization
        /// </summary>
        [Output("orgId")]
        public Output<string?> OrgId { get; private set; } = null!;

        /// <summary>
        /// Primary domain of the org
        /// </summary>
        [Output("primaryDomain")]
        public Output<string> PrimaryDomain { get; private set; } = null!;

        /// <summary>
        /// State of the org
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;


        /// <summary>
        /// Create a Organization resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Organization(string name, OrganizationArgs args, CustomResourceOptions? options = null)
            : base("zitadel:index/organization:Organization", name, args ?? new OrganizationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Organization(string name, Input<string> id, OrganizationState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/organization:Organization", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/scoretechnologies",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Organization resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Organization Get(string name, Input<string> id, OrganizationState? state = null, CustomResourceOptions? options = null)
        {
            return new Organization(name, id, state, options);
        }
    }

    public sealed class OrganizationArgs : global::Pulumi.ResourceArgs
    {
        [Input("admins")]
        private InputList<Inputs.OrganizationAdminArgs>? _admins;

        /// <summary>
        /// List of users to be granted organization admin roles
        /// </summary>
        public InputList<Inputs.OrganizationAdminArgs> Admins
        {
            get => _admins ?? (_admins = new InputList<Inputs.OrganizationAdminArgs>());
            set => _admins = value;
        }

        /// <summary>
        /// Name of the org
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Custom unique identifier for the organization
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        public OrganizationArgs()
        {
        }
        public static new OrganizationArgs Empty => new OrganizationArgs();
    }

    public sealed class OrganizationState : global::Pulumi.ResourceArgs
    {
        [Input("admins")]
        private InputList<Inputs.OrganizationAdminGetArgs>? _admins;

        /// <summary>
        /// List of users to be granted organization admin roles
        /// </summary>
        public InputList<Inputs.OrganizationAdminGetArgs> Admins
        {
            get => _admins ?? (_admins = new InputList<Inputs.OrganizationAdminGetArgs>());
            set => _admins = value;
        }

        /// <summary>
        /// Name of the org
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Custom unique identifier for the organization
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        /// <summary>
        /// Primary domain of the org
        /// </summary>
        [Input("primaryDomain")]
        public Input<string>? PrimaryDomain { get; set; }

        /// <summary>
        /// State of the org
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public OrganizationState()
        {
        }
        public static new OrganizationState Empty => new OrganizationState();
    }
}
