// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel
{
    /// <summary>
    /// Resource representing a web key.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Zitadel = scoretechnologies.Zitadel;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @default = new Zitadel.Webkey("default", new()
    ///     {
    ///         OrgId = defaultZitadelOrg.Id,
    ///         Rsa = new Zitadel.Inputs.WebkeyRsaArgs
    ///         {
    ///             Bits = "RSA_BITS_2048",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The resource can be imported using the ID format `&lt;id[:org_id]&gt;`, e.g.
    /// 
    /// ```sh
    /// $ pulumi import zitadel:index/webkey:Webkey imported '123456789012345678:123456789012345678'
    /// ```
    /// </summary>
    [ZitadelResourceType("zitadel:index/webkey:Webkey")]
    public partial class Webkey : global::Pulumi.CustomResource
    {
        [Output("ecdsa")]
        public Output<Outputs.WebkeyEcdsa?> Ecdsa { get; private set; } = null!;

        /// <summary>
        /// Create a ED25519 key pair.
        /// </summary>
        [Output("ed25519")]
        public Output<Outputs.WebkeyEd25519?> Ed25519 { get; private set; } = null!;

        /// <summary>
        /// Type of the key.
        /// </summary>
        [Output("keyType")]
        public Output<string> KeyType { get; private set; } = null!;

        /// <summary>
        /// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        /// </summary>
        [Output("orgId")]
        public Output<string?> OrgId { get; private set; } = null!;

        [Output("rsa")]
        public Output<Outputs.WebkeyRsa?> Rsa { get; private set; } = null!;

        /// <summary>
        /// State of the key.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;


        /// <summary>
        /// Create a Webkey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Webkey(string name, WebkeyArgs? args = null, CustomResourceOptions? options = null)
            : base("zitadel:index/webkey:Webkey", name, args ?? new WebkeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Webkey(string name, Input<string> id, WebkeyState? state = null, CustomResourceOptions? options = null)
            : base("zitadel:index/webkey:Webkey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/scoretechnologies",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Webkey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Webkey Get(string name, Input<string> id, WebkeyState? state = null, CustomResourceOptions? options = null)
        {
            return new Webkey(name, id, state, options);
        }
    }

    public sealed class WebkeyArgs : global::Pulumi.ResourceArgs
    {
        [Input("ecdsa")]
        public Input<Inputs.WebkeyEcdsaArgs>? Ecdsa { get; set; }

        /// <summary>
        /// Create a ED25519 key pair.
        /// </summary>
        [Input("ed25519")]
        public Input<Inputs.WebkeyEd25519Args>? Ed25519 { get; set; }

        /// <summary>
        /// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        [Input("rsa")]
        public Input<Inputs.WebkeyRsaArgs>? Rsa { get; set; }

        public WebkeyArgs()
        {
        }
        public static new WebkeyArgs Empty => new WebkeyArgs();
    }

    public sealed class WebkeyState : global::Pulumi.ResourceArgs
    {
        [Input("ecdsa")]
        public Input<Inputs.WebkeyEcdsaGetArgs>? Ecdsa { get; set; }

        /// <summary>
        /// Create a ED25519 key pair.
        /// </summary>
        [Input("ed25519")]
        public Input<Inputs.WebkeyEd25519GetArgs>? Ed25519 { get; set; }

        /// <summary>
        /// Type of the key.
        /// </summary>
        [Input("keyType")]
        public Input<string>? KeyType { get; set; }

        /// <summary>
        /// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        [Input("rsa")]
        public Input<Inputs.WebkeyRsaGetArgs>? Rsa { get; set; }

        /// <summary>
        /// State of the key.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public WebkeyState()
        {
        }
        public static new WebkeyState Empty => new WebkeyState();
    }
}
