// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class ApplicationSamlLoginVersion
    {
        /// <summary>
        /// Login V1
        /// </summary>
        public readonly bool? LoginV1;
        /// <summary>
        /// Login V2
        /// </summary>
        public readonly Outputs.ApplicationSamlLoginVersionLoginV2? LoginV2;

        [OutputConstructor]
        private ApplicationSamlLoginVersion(
            bool? loginV1,

            Outputs.ApplicationSamlLoginVersionLoginV2? loginV2)
        {
            LoginV1 = loginV1;
            LoginV2 = loginV2;
        }
    }
}
