// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class DefaultLoginTextsFooterText
    {
        public readonly string? Help;
        public readonly string? PrivacyPolicy;
        public readonly string? SupportEmail;
        public readonly string? Tos;

        [OutputConstructor]
        private DefaultLoginTextsFooterText(
            string? help,

            string? privacyPolicy,

            string? supportEmail,

            string? tos)
        {
            Help = help;
            PrivacyPolicy = privacyPolicy;
            SupportEmail = supportEmail;
            Tos = tos;
        }
    }
}
