// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class DefaultLoginTextsLoginText
    {
        public readonly string? Description;
        public readonly string? DescriptionLinkingProcess;
        public readonly string? ExternalUserDescription;
        public readonly string? LoginNameLabel;
        public readonly string? LoginNamePlaceholder;
        public readonly string? NextButtonText;
        public readonly string? RegisterButtonText;
        public readonly string? Title;
        public readonly string? TitleLinkingProcess;
        public readonly string? UserMustBeMemberOfOrg;
        public readonly string? UserNamePlaceholder;

        [OutputConstructor]
        private DefaultLoginTextsLoginText(
            string? description,

            string? descriptionLinkingProcess,

            string? externalUserDescription,

            string? loginNameLabel,

            string? loginNamePlaceholder,

            string? nextButtonText,

            string? registerButtonText,

            string? title,

            string? titleLinkingProcess,

            string? userMustBeMemberOfOrg,

            string? userNamePlaceholder)
        {
            Description = description;
            DescriptionLinkingProcess = descriptionLinkingProcess;
            ExternalUserDescription = externalUserDescription;
            LoginNameLabel = loginNameLabel;
            LoginNamePlaceholder = loginNamePlaceholder;
            NextButtonText = nextButtonText;
            RegisterButtonText = registerButtonText;
            Title = title;
            TitleLinkingProcess = titleLinkingProcess;
            UserMustBeMemberOfOrg = userMustBeMemberOfOrg;
            UserNamePlaceholder = userNamePlaceholder;
        }
    }
}
