// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class DefaultLoginTextsPasswordlessRegistrationDoneText
    {
        public readonly string? CancelButtonText;
        public readonly string? Description;
        public readonly string? DescriptionClose;
        public readonly string? NextButtonText;
        public readonly string? Title;

        [OutputConstructor]
        private DefaultLoginTextsPasswordlessRegistrationDoneText(
            string? cancelButtonText,

            string? description,

            string? descriptionClose,

            string? nextButtonText,

            string? title)
        {
            CancelButtonText = cancelButtonText;
            Description = description;
            DescriptionClose = descriptionClose;
            NextButtonText = nextButtonText;
            Title = title;
        }
    }
}
