// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class DefaultLoginTextsInitMfaPromptText
    {
        public readonly string? Description;
        public readonly string? NextButtonText;
        public readonly string? OtpOption;
        public readonly string? SkipButtonText;
        public readonly string? Title;
        public readonly string? U2fOption;

        [OutputConstructor]
        private DefaultLoginTextsInitMfaPromptText(
            string? description,

            string? nextButtonText,

            string? otpOption,

            string? skipButtonText,

            string? title,

            string? u2fOption)
        {
            Description = description;
            NextButtonText = nextButtonText;
            OtpOption = otpOption;
            SkipButtonText = skipButtonText;
            Title = title;
            U2fOption = u2fOption;
        }
    }
}
