// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class DefaultLoginTextsRegistrationOptionText
    {
        public readonly string? Description;
        public readonly string? ExternalLoginDescription;
        public readonly string? LoginButtonText;
        public readonly string? Title;
        public readonly string? UserNameButtonText;

        [OutputConstructor]
        private DefaultLoginTextsRegistrationOptionText(
            string? description,

            string? externalLoginDescription,

            string? loginButtonText,

            string? title,

            string? userNameButtonText)
        {
            Description = description;
            ExternalLoginDescription = externalLoginDescription;
            LoginButtonText = loginButtonText;
            Title = title;
            UserNameButtonText = userNameButtonText;
        }
    }
}
