// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class DefaultLoginTextsPasswordChangeDoneText
    {
        public readonly string? Description;
        public readonly string? NextButtonText;
        public readonly string? Title;

        [OutputConstructor]
        private DefaultLoginTextsPasswordChangeDoneText(
            string? description,

            string? nextButtonText,

            string? title)
        {
            Description = description;
            NextButtonText = nextButtonText;
            Title = title;
        }
    }
}
