// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class GetApplicationOidcLoginVersionResult
    {
        /// <summary>
        /// Login V1
        /// </summary>
        public readonly bool LoginV1;
        /// <summary>
        /// Login V2
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApplicationOidcLoginVersionLoginV2Result> LoginV2s;

        [OutputConstructor]
        private GetApplicationOidcLoginVersionResult(
            bool loginV1,

            ImmutableArray<Outputs.GetApplicationOidcLoginVersionLoginV2Result> loginV2s)
        {
            LoginV1 = loginV1;
            LoginV2s = loginV2s;
        }
    }
}
