// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class HumanUserMetadata
    {
        /// <summary>
        /// The key of the metadata entry.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The value of the metadata entry.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private HumanUserMetadata(
            string key,

            string value)
        {
            Key = key;
            Value = value;
        }
    }
}
