// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Outputs
{

    [OutputType]
    public sealed class LoginTextsLinkingUserPromptText
    {
        public readonly string? Description;
        public readonly string? LinkButtonText;
        public readonly string? OtherButtonText;
        public readonly string? Title;

        [OutputConstructor]
        private LoginTextsLinkingUserPromptText(
            string? description,

            string? linkButtonText,

            string? otherButtonText,

            string? title)
        {
            Description = description;
            LinkButtonText = linkButtonText;
            OtherButtonText = otherButtonText;
            Title = title;
        }
    }
}
