# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ActionExecutionEventArgs', 'ActionExecutionEvent']

@pulumi.input_type
class ActionExecutionEventArgs:
    def __init__(__self__, *,
                 all: pulumi.Input[Optional[_builtins.bool]] = None,
                 event: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 target_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a ActionExecutionEvent resource.

        :param pulumi.Input[_builtins.bool] all: Trigger on all events.
        :param pulumi.Input[_builtins.str] event: The specific event to trigger on, e.g., `user.human.added`
        :param pulumi.Input[_builtins.str] group: The event group to trigger on, e.g., `user.human`
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] target_ids: The list of target IDs to call.
        """
        if all is not None:
            pulumi.set(__self__, "all", all)
        if event is not None:
            pulumi.set(__self__, "event", event)
        if group is not None:
            pulumi.set(__self__, "group", group)
        if target_ids is not None:
            pulumi.set(__self__, "target_ids", target_ids)

    @_builtins.property
    @pulumi.getter
    def all(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Trigger on all events.
        """
        return pulumi.get(self, "all")

    @all.setter
    def all(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "all", value)

    @_builtins.property
    @pulumi.getter
    def event(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The specific event to trigger on, e.g., `user.human.added`
        """
        return pulumi.get(self, "event")

    @event.setter
    def event(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "event", value)

    @_builtins.property
    @pulumi.getter
    def group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The event group to trigger on, e.g., `user.human`
        """
        return pulumi.get(self, "group")

    @group.setter
    def group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "group", value)

    @_builtins.property
    @pulumi.getter(name="targetIds")
    def target_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The list of target IDs to call.
        """
        return pulumi.get(self, "target_ids")

    @target_ids.setter
    def target_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "target_ids", value)


@pulumi.input_type
class _ActionExecutionEventState:
    def __init__(__self__, *,
                 all: pulumi.Input[Optional[_builtins.bool]] = None,
                 event: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 target_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering ActionExecutionEvent resources.

        :param pulumi.Input[_builtins.bool] all: Trigger on all events.
        :param pulumi.Input[_builtins.str] event: The specific event to trigger on, e.g., `user.human.added`
        :param pulumi.Input[_builtins.str] group: The event group to trigger on, e.g., `user.human`
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] target_ids: The list of target IDs to call.
        """
        if all is not None:
            pulumi.set(__self__, "all", all)
        if event is not None:
            pulumi.set(__self__, "event", event)
        if group is not None:
            pulumi.set(__self__, "group", group)
        if target_ids is not None:
            pulumi.set(__self__, "target_ids", target_ids)

    @_builtins.property
    @pulumi.getter
    def all(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Trigger on all events.
        """
        return pulumi.get(self, "all")

    @all.setter
    def all(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "all", value)

    @_builtins.property
    @pulumi.getter
    def event(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The specific event to trigger on, e.g., `user.human.added`
        """
        return pulumi.get(self, "event")

    @event.setter
    def event(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "event", value)

    @_builtins.property
    @pulumi.getter
    def group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The event group to trigger on, e.g., `user.human`
        """
        return pulumi.get(self, "group")

    @group.setter
    def group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "group", value)

    @_builtins.property
    @pulumi.getter(name="targetIds")
    def target_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The list of target IDs to call.
        """
        return pulumi.get(self, "target_ids")

    @target_ids.setter
    def target_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "target_ids", value)


@pulumi.type_token("zitadel:index/actionExecutionEvent:ActionExecutionEvent")
class ActionExecutionEvent(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 all: pulumi.Input[Optional[_builtins.bool]] = None,
                 event: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 target_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Resource representing an action execution triggered by an event.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.ActionTarget("default",
            name="event-webhook",
            endpoint="https://example.com/webhooks/events",
            target_type="REST_ASYNC",
            timeout="10s",
            interrupt_on_error=False)
        default_action_execution_event = zitadel.ActionExecutionEvent("default",
            event="user.human.added",
            target_ids=[default.id])
        ```

        ## Import

        event:name for specific event, group:name for event group, all for all events

        ```sh
        $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'event:user.human.added'
        $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'group:user.human'
        $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'all'
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] all: Trigger on all events.
        :param pulumi.Input[_builtins.str] event: The specific event to trigger on, e.g., `user.human.added`
        :param pulumi.Input[_builtins.str] group: The event group to trigger on, e.g., `user.human`
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] target_ids: The list of target IDs to call.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ActionExecutionEventArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Resource representing an action execution triggered by an event.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.ActionTarget("default",
            name="event-webhook",
            endpoint="https://example.com/webhooks/events",
            target_type="REST_ASYNC",
            timeout="10s",
            interrupt_on_error=False)
        default_action_execution_event = zitadel.ActionExecutionEvent("default",
            event="user.human.added",
            target_ids=[default.id])
        ```

        ## Import

        event:name for specific event, group:name for event group, all for all events

        ```sh
        $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'event:user.human.added'
        $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'group:user.human'
        $ pulumi import zitadel:index/actionExecutionEvent:ActionExecutionEvent imported 'all'
        ```


        :param str resource_name: The name of the resource.
        :param ActionExecutionEventArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ActionExecutionEventArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 all: pulumi.Input[Optional[_builtins.bool]] = None,
                 event: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 target_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ActionExecutionEventArgs.__new__(ActionExecutionEventArgs)

            __props__.__dict__["all"] = all
            __props__.__dict__["event"] = event
            __props__.__dict__["group"] = group
            __props__.__dict__["target_ids"] = target_ids
        super(ActionExecutionEvent, __self__).__init__(
            'zitadel:index/actionExecutionEvent:ActionExecutionEvent',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            all: pulumi.Input[Optional[_builtins.bool]] = None,
            event: pulumi.Input[Optional[_builtins.str]] = None,
            group: pulumi.Input[Optional[_builtins.str]] = None,
            target_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'ActionExecutionEvent':
        """
        Get an existing ActionExecutionEvent resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] all: Trigger on all events.
        :param pulumi.Input[_builtins.str] event: The specific event to trigger on, e.g., `user.human.added`
        :param pulumi.Input[_builtins.str] group: The event group to trigger on, e.g., `user.human`
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] target_ids: The list of target IDs to call.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ActionExecutionEventState.__new__(_ActionExecutionEventState)

        __props__.__dict__["all"] = all
        __props__.__dict__["event"] = event
        __props__.__dict__["group"] = group
        __props__.__dict__["target_ids"] = target_ids
        return ActionExecutionEvent(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def all(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Trigger on all events.
        """
        return pulumi.get(self, "all")

    @_builtins.property
    @pulumi.getter
    def event(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The specific event to trigger on, e.g., `user.human.added`
        """
        return pulumi.get(self, "event")

    @_builtins.property
    @pulumi.getter
    def group(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The event group to trigger on, e.g., `user.human`
        """
        return pulumi.get(self, "group")

    @_builtins.property
    @pulumi.getter(name="targetIds")
    def target_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The list of target IDs to call.
        """
        return pulumi.get(self, "target_ids")

