# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ApplicationOidcArgs', 'ApplicationOidc']

@pulumi.input_type
class ApplicationOidcArgs:
    def __init__(__self__, *,
                 grant_types: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 name: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 redirect_uris: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 response_types: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 access_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 access_token_type: pulumi.Input[Optional[_builtins.str]] = None,
                 additional_origins: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 app_type: pulumi.Input[Optional[_builtins.str]] = None,
                 auth_method_type: pulumi.Input[Optional[_builtins.str]] = None,
                 back_channel_logout_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 clock_skew: pulumi.Input[Optional[_builtins.str]] = None,
                 dev_mode: pulumi.Input[Optional[_builtins.bool]] = None,
                 id_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 id_token_userinfo_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 login_version: pulumi.Input[Optional['ApplicationOidcLoginVersionArgs']] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 post_logout_redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_native_app_success_page: pulumi.Input[Optional[_builtins.bool]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a ApplicationOidc resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] grant_types: Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
        :param pulumi.Input[_builtins.str] name: Name of the application
        :param pulumi.Input[_builtins.str] project_id: ID of the project
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: RedirectURIs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] response_types: Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        :param pulumi.Input[_builtins.bool] access_token_role_assertion: Access token role assertion
        :param pulumi.Input[_builtins.str] access_token_type: Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] additional_origins: Additional origins
        :param pulumi.Input[_builtins.str] app_type: App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        :param pulumi.Input[_builtins.str] auth_method_type: Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        :param pulumi.Input[_builtins.str] back_channel_logout_uri: ZITADEL will use this URI to notify the application about terminated session according to the OIDC Back-Channel Logout
        :param pulumi.Input[_builtins.str] clock_skew: Clockskew
        :param pulumi.Input[_builtins.bool] dev_mode: Dev mode
        :param pulumi.Input[_builtins.bool] id_token_role_assertion: ID token role assertion
        :param pulumi.Input[_builtins.bool] id_token_userinfo_assertion: Token userinfo assertion
        :param pulumi.Input['ApplicationOidcLoginVersionArgs'] login_version: Specify the preferred login UI, where the user is redirected to for authentication. If unset, the login UI is chosen by the instance default.
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] post_logout_redirect_uris: Post logout redirect URIs
        :param pulumi.Input[_builtins.bool] skip_native_app_success_page: Skip the successful login page on native apps and directly redirect the user to the callback.
        :param pulumi.Input[_builtins.str] version: Version, supported values: OIDC*VERSION*1_0
        """
        pulumi.set(__self__, "grant_types", grant_types)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "redirect_uris", redirect_uris)
        pulumi.set(__self__, "response_types", response_types)
        if access_token_role_assertion is not None:
            pulumi.set(__self__, "access_token_role_assertion", access_token_role_assertion)
        if access_token_type is not None:
            pulumi.set(__self__, "access_token_type", access_token_type)
        if additional_origins is not None:
            pulumi.set(__self__, "additional_origins", additional_origins)
        if app_type is not None:
            pulumi.set(__self__, "app_type", app_type)
        if auth_method_type is not None:
            pulumi.set(__self__, "auth_method_type", auth_method_type)
        if back_channel_logout_uri is not None:
            pulumi.set(__self__, "back_channel_logout_uri", back_channel_logout_uri)
        if clock_skew is not None:
            pulumi.set(__self__, "clock_skew", clock_skew)
        if dev_mode is not None:
            pulumi.set(__self__, "dev_mode", dev_mode)
        if id_token_role_assertion is not None:
            pulumi.set(__self__, "id_token_role_assertion", id_token_role_assertion)
        if id_token_userinfo_assertion is not None:
            pulumi.set(__self__, "id_token_userinfo_assertion", id_token_userinfo_assertion)
        if login_version is not None:
            pulumi.set(__self__, "login_version", login_version)
        if org_id is not None:
            pulumi.set(__self__, "org_id", org_id)
        if post_logout_redirect_uris is not None:
            pulumi.set(__self__, "post_logout_redirect_uris", post_logout_redirect_uris)
        if skip_native_app_success_page is not None:
            pulumi.set(__self__, "skip_native_app_success_page", skip_native_app_success_page)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="grantTypes")
    def grant_types(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
        """
        return pulumi.get(self, "grant_types")

    @grant_types.setter
    def grant_types(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "grant_types", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the application
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the project
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        RedirectURIs
        """
        return pulumi.get(self, "redirect_uris")

    @redirect_uris.setter
    def redirect_uris(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "redirect_uris", value)

    @_builtins.property
    @pulumi.getter(name="responseTypes")
    def response_types(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        """
        return pulumi.get(self, "response_types")

    @response_types.setter
    def response_types(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "response_types", value)

    @_builtins.property
    @pulumi.getter(name="accessTokenRoleAssertion")
    def access_token_role_assertion(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Access token role assertion
        """
        return pulumi.get(self, "access_token_role_assertion")

    @access_token_role_assertion.setter
    def access_token_role_assertion(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "access_token_role_assertion", value)

    @_builtins.property
    @pulumi.getter(name="accessTokenType")
    def access_token_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        """
        return pulumi.get(self, "access_token_type")

    @access_token_type.setter
    def access_token_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_token_type", value)

    @_builtins.property
    @pulumi.getter(name="additionalOrigins")
    def additional_origins(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Additional origins
        """
        return pulumi.get(self, "additional_origins")

    @additional_origins.setter
    def additional_origins(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "additional_origins", value)

    @_builtins.property
    @pulumi.getter(name="appType")
    def app_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        """
        return pulumi.get(self, "app_type")

    @app_type.setter
    def app_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "app_type", value)

    @_builtins.property
    @pulumi.getter(name="authMethodType")
    def auth_method_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        """
        return pulumi.get(self, "auth_method_type")

    @auth_method_type.setter
    def auth_method_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "auth_method_type", value)

    @_builtins.property
    @pulumi.getter(name="backChannelLogoutUri")
    def back_channel_logout_uri(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ZITADEL will use this URI to notify the application about terminated session according to the OIDC Back-Channel Logout
        """
        return pulumi.get(self, "back_channel_logout_uri")

    @back_channel_logout_uri.setter
    def back_channel_logout_uri(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "back_channel_logout_uri", value)

    @_builtins.property
    @pulumi.getter(name="clockSkew")
    def clock_skew(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Clockskew
        """
        return pulumi.get(self, "clock_skew")

    @clock_skew.setter
    def clock_skew(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "clock_skew", value)

    @_builtins.property
    @pulumi.getter(name="devMode")
    def dev_mode(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Dev mode
        """
        return pulumi.get(self, "dev_mode")

    @dev_mode.setter
    def dev_mode(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "dev_mode", value)

    @_builtins.property
    @pulumi.getter(name="idTokenRoleAssertion")
    def id_token_role_assertion(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        ID token role assertion
        """
        return pulumi.get(self, "id_token_role_assertion")

    @id_token_role_assertion.setter
    def id_token_role_assertion(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "id_token_role_assertion", value)

    @_builtins.property
    @pulumi.getter(name="idTokenUserinfoAssertion")
    def id_token_userinfo_assertion(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Token userinfo assertion
        """
        return pulumi.get(self, "id_token_userinfo_assertion")

    @id_token_userinfo_assertion.setter
    def id_token_userinfo_assertion(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "id_token_userinfo_assertion", value)

    @_builtins.property
    @pulumi.getter(name="loginVersion")
    def login_version(self) -> pulumi.Input[Optional['ApplicationOidcLoginVersionArgs']]:
        """
        Specify the preferred login UI, where the user is redirected to for authentication. If unset, the login UI is chosen by the instance default.
        """
        return pulumi.get(self, "login_version")

    @login_version.setter
    def login_version(self, value: pulumi.Input[Optional['ApplicationOidcLoginVersionArgs']]):
        pulumi.set(self, "login_version", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_id", value)

    @_builtins.property
    @pulumi.getter(name="postLogoutRedirectUris")
    def post_logout_redirect_uris(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Post logout redirect URIs
        """
        return pulumi.get(self, "post_logout_redirect_uris")

    @post_logout_redirect_uris.setter
    def post_logout_redirect_uris(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "post_logout_redirect_uris", value)

    @_builtins.property
    @pulumi.getter(name="skipNativeAppSuccessPage")
    def skip_native_app_success_page(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip the successful login page on native apps and directly redirect the user to the callback.
        """
        return pulumi.get(self, "skip_native_app_success_page")

    @skip_native_app_success_page.setter
    def skip_native_app_success_page(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_native_app_success_page", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Version, supported values: OIDC*VERSION*1_0
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.input_type
class _ApplicationOidcState:
    def __init__(__self__, *,
                 access_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 access_token_type: pulumi.Input[Optional[_builtins.str]] = None,
                 additional_origins: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 app_type: pulumi.Input[Optional[_builtins.str]] = None,
                 auth_method_type: pulumi.Input[Optional[_builtins.str]] = None,
                 back_channel_logout_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 client_secret: pulumi.Input[Optional[_builtins.str]] = None,
                 clock_skew: pulumi.Input[Optional[_builtins.str]] = None,
                 compliance_problems: pulumi.Input[Optional[Sequence[pulumi.Input['ApplicationOidcComplianceProblemArgs']]]] = None,
                 dev_mode: pulumi.Input[Optional[_builtins.bool]] = None,
                 grant_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 id_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 id_token_userinfo_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 login_version: pulumi.Input[Optional['ApplicationOidcLoginVersionArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 none_compliant: pulumi.Input[Optional[_builtins.bool]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 post_logout_redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 response_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_native_app_success_page: pulumi.Input[Optional[_builtins.bool]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ApplicationOidc resources.

        :param pulumi.Input[_builtins.bool] access_token_role_assertion: Access token role assertion
        :param pulumi.Input[_builtins.str] access_token_type: Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] additional_origins: Additional origins
        :param pulumi.Input[_builtins.str] app_type: App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        :param pulumi.Input[_builtins.str] auth_method_type: Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        :param pulumi.Input[_builtins.str] back_channel_logout_uri: ZITADEL will use this URI to notify the application about terminated session according to the OIDC Back-Channel Logout
        :param pulumi.Input[_builtins.str] client_id: generated ID for this config
        :param pulumi.Input[_builtins.str] client_secret: generated secret for this config
        :param pulumi.Input[_builtins.str] clock_skew: Clockskew
        :param pulumi.Input[Sequence[pulumi.Input['ApplicationOidcComplianceProblemArgs']]] compliance_problems: lists the problems for non-compliancy
        :param pulumi.Input[_builtins.bool] dev_mode: Dev mode
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] grant_types: Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
        :param pulumi.Input[_builtins.bool] id_token_role_assertion: ID token role assertion
        :param pulumi.Input[_builtins.bool] id_token_userinfo_assertion: Token userinfo assertion
        :param pulumi.Input['ApplicationOidcLoginVersionArgs'] login_version: Specify the preferred login UI, where the user is redirected to for authentication. If unset, the login UI is chosen by the instance default.
        :param pulumi.Input[_builtins.str] name: Name of the application
        :param pulumi.Input[_builtins.bool] none_compliant: specifies whether the config is OIDC compliant. A production configuration SHOULD be compliant
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] post_logout_redirect_uris: Post logout redirect URIs
        :param pulumi.Input[_builtins.str] project_id: ID of the project
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: RedirectURIs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] response_types: Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        :param pulumi.Input[_builtins.bool] skip_native_app_success_page: Skip the successful login page on native apps and directly redirect the user to the callback.
        :param pulumi.Input[_builtins.str] version: Version, supported values: OIDC*VERSION*1_0
        """
        if access_token_role_assertion is not None:
            pulumi.set(__self__, "access_token_role_assertion", access_token_role_assertion)
        if access_token_type is not None:
            pulumi.set(__self__, "access_token_type", access_token_type)
        if additional_origins is not None:
            pulumi.set(__self__, "additional_origins", additional_origins)
        if app_type is not None:
            pulumi.set(__self__, "app_type", app_type)
        if auth_method_type is not None:
            pulumi.set(__self__, "auth_method_type", auth_method_type)
        if back_channel_logout_uri is not None:
            pulumi.set(__self__, "back_channel_logout_uri", back_channel_logout_uri)
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if client_secret is not None:
            pulumi.set(__self__, "client_secret", client_secret)
        if clock_skew is not None:
            pulumi.set(__self__, "clock_skew", clock_skew)
        if compliance_problems is not None:
            pulumi.set(__self__, "compliance_problems", compliance_problems)
        if dev_mode is not None:
            pulumi.set(__self__, "dev_mode", dev_mode)
        if grant_types is not None:
            pulumi.set(__self__, "grant_types", grant_types)
        if id_token_role_assertion is not None:
            pulumi.set(__self__, "id_token_role_assertion", id_token_role_assertion)
        if id_token_userinfo_assertion is not None:
            pulumi.set(__self__, "id_token_userinfo_assertion", id_token_userinfo_assertion)
        if login_version is not None:
            pulumi.set(__self__, "login_version", login_version)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if none_compliant is not None:
            pulumi.set(__self__, "none_compliant", none_compliant)
        if org_id is not None:
            pulumi.set(__self__, "org_id", org_id)
        if post_logout_redirect_uris is not None:
            pulumi.set(__self__, "post_logout_redirect_uris", post_logout_redirect_uris)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if redirect_uris is not None:
            pulumi.set(__self__, "redirect_uris", redirect_uris)
        if response_types is not None:
            pulumi.set(__self__, "response_types", response_types)
        if skip_native_app_success_page is not None:
            pulumi.set(__self__, "skip_native_app_success_page", skip_native_app_success_page)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="accessTokenRoleAssertion")
    def access_token_role_assertion(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Access token role assertion
        """
        return pulumi.get(self, "access_token_role_assertion")

    @access_token_role_assertion.setter
    def access_token_role_assertion(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "access_token_role_assertion", value)

    @_builtins.property
    @pulumi.getter(name="accessTokenType")
    def access_token_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        """
        return pulumi.get(self, "access_token_type")

    @access_token_type.setter
    def access_token_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_token_type", value)

    @_builtins.property
    @pulumi.getter(name="additionalOrigins")
    def additional_origins(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Additional origins
        """
        return pulumi.get(self, "additional_origins")

    @additional_origins.setter
    def additional_origins(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "additional_origins", value)

    @_builtins.property
    @pulumi.getter(name="appType")
    def app_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        """
        return pulumi.get(self, "app_type")

    @app_type.setter
    def app_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "app_type", value)

    @_builtins.property
    @pulumi.getter(name="authMethodType")
    def auth_method_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        """
        return pulumi.get(self, "auth_method_type")

    @auth_method_type.setter
    def auth_method_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "auth_method_type", value)

    @_builtins.property
    @pulumi.getter(name="backChannelLogoutUri")
    def back_channel_logout_uri(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ZITADEL will use this URI to notify the application about terminated session according to the OIDC Back-Channel Logout
        """
        return pulumi.get(self, "back_channel_logout_uri")

    @back_channel_logout_uri.setter
    def back_channel_logout_uri(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "back_channel_logout_uri", value)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        generated ID for this config
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        generated secret for this config
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter(name="clockSkew")
    def clock_skew(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Clockskew
        """
        return pulumi.get(self, "clock_skew")

    @clock_skew.setter
    def clock_skew(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "clock_skew", value)

    @_builtins.property
    @pulumi.getter(name="complianceProblems")
    def compliance_problems(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ApplicationOidcComplianceProblemArgs']]]]:
        """
        lists the problems for non-compliancy
        """
        return pulumi.get(self, "compliance_problems")

    @compliance_problems.setter
    def compliance_problems(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ApplicationOidcComplianceProblemArgs']]]]):
        pulumi.set(self, "compliance_problems", value)

    @_builtins.property
    @pulumi.getter(name="devMode")
    def dev_mode(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Dev mode
        """
        return pulumi.get(self, "dev_mode")

    @dev_mode.setter
    def dev_mode(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "dev_mode", value)

    @_builtins.property
    @pulumi.getter(name="grantTypes")
    def grant_types(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
        """
        return pulumi.get(self, "grant_types")

    @grant_types.setter
    def grant_types(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "grant_types", value)

    @_builtins.property
    @pulumi.getter(name="idTokenRoleAssertion")
    def id_token_role_assertion(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        ID token role assertion
        """
        return pulumi.get(self, "id_token_role_assertion")

    @id_token_role_assertion.setter
    def id_token_role_assertion(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "id_token_role_assertion", value)

    @_builtins.property
    @pulumi.getter(name="idTokenUserinfoAssertion")
    def id_token_userinfo_assertion(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Token userinfo assertion
        """
        return pulumi.get(self, "id_token_userinfo_assertion")

    @id_token_userinfo_assertion.setter
    def id_token_userinfo_assertion(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "id_token_userinfo_assertion", value)

    @_builtins.property
    @pulumi.getter(name="loginVersion")
    def login_version(self) -> pulumi.Input[Optional['ApplicationOidcLoginVersionArgs']]:
        """
        Specify the preferred login UI, where the user is redirected to for authentication. If unset, the login UI is chosen by the instance default.
        """
        return pulumi.get(self, "login_version")

    @login_version.setter
    def login_version(self, value: pulumi.Input[Optional['ApplicationOidcLoginVersionArgs']]):
        pulumi.set(self, "login_version", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the application
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="noneCompliant")
    def none_compliant(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        specifies whether the config is OIDC compliant. A production configuration SHOULD be compliant
        """
        return pulumi.get(self, "none_compliant")

    @none_compliant.setter
    def none_compliant(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "none_compliant", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_id", value)

    @_builtins.property
    @pulumi.getter(name="postLogoutRedirectUris")
    def post_logout_redirect_uris(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Post logout redirect URIs
        """
        return pulumi.get(self, "post_logout_redirect_uris")

    @post_logout_redirect_uris.setter
    def post_logout_redirect_uris(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "post_logout_redirect_uris", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the project
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        RedirectURIs
        """
        return pulumi.get(self, "redirect_uris")

    @redirect_uris.setter
    def redirect_uris(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "redirect_uris", value)

    @_builtins.property
    @pulumi.getter(name="responseTypes")
    def response_types(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        """
        return pulumi.get(self, "response_types")

    @response_types.setter
    def response_types(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "response_types", value)

    @_builtins.property
    @pulumi.getter(name="skipNativeAppSuccessPage")
    def skip_native_app_success_page(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip the successful login page on native apps and directly redirect the user to the callback.
        """
        return pulumi.get(self, "skip_native_app_success_page")

    @skip_native_app_success_page.setter
    def skip_native_app_success_page(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_native_app_success_page", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Version, supported values: OIDC*VERSION*1_0
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("zitadel:index/applicationOidc:ApplicationOidc")
class ApplicationOidc(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 access_token_type: pulumi.Input[Optional[_builtins.str]] = None,
                 additional_origins: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 app_type: pulumi.Input[Optional[_builtins.str]] = None,
                 auth_method_type: pulumi.Input[Optional[_builtins.str]] = None,
                 back_channel_logout_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 clock_skew: pulumi.Input[Optional[_builtins.str]] = None,
                 dev_mode: pulumi.Input[Optional[_builtins.bool]] = None,
                 grant_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 id_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 id_token_userinfo_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 login_version: pulumi.Input[Optional[Union['ApplicationOidcLoginVersionArgs', 'ApplicationOidcLoginVersionArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 post_logout_redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 response_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_native_app_success_page: pulumi.Input[Optional[_builtins.bool]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Resource representing an OIDC application belonging to a project, with all configuration possibilities.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.ApplicationOidc("default",
            project_id=default_zitadel_project["id"],
            org_id=default_zitadel_org["id"],
            name="applicationoidc",
            redirect_uris=["https://localhost.com"],
            response_types=["OIDC_RESPONSE_TYPE_CODE"],
            grant_types=["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
            post_logout_redirect_uris=["https://localhost.com"],
            app_type="OIDC_APP_TYPE_WEB",
            auth_method_type="OIDC_AUTH_METHOD_TYPE_BASIC",
            version="OIDC_VERSION_1_0",
            clock_skew="0s",
            dev_mode=True,
            access_token_type="OIDC_TOKEN_TYPE_BEARER",
            access_token_role_assertion=False,
            id_token_role_assertion=False,
            id_token_userinfo_assertion=False,
            additional_origins=[],
            skip_native_app_success_page=False)
        ```

        ## Import

        The resource can be imported using the ID format `<id:project_id[:org_id][:client_id][:client_secret]>`, e.g.

        ```sh
        $ pulumi import zitadel:index/applicationOidc:ApplicationOidc imported '123456789012345678:123456789012345678:123456789012345678:123456789012345678@zitadel:JuaDFFeOak5DGE655KCYPSAclSkbMVEJXXuX1lEMBT14eLMSs0A0qhafKX5SA2Df'
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] access_token_role_assertion: Access token role assertion
        :param pulumi.Input[_builtins.str] access_token_type: Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] additional_origins: Additional origins
        :param pulumi.Input[_builtins.str] app_type: App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        :param pulumi.Input[_builtins.str] auth_method_type: Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        :param pulumi.Input[_builtins.str] back_channel_logout_uri: ZITADEL will use this URI to notify the application about terminated session according to the OIDC Back-Channel Logout
        :param pulumi.Input[_builtins.str] clock_skew: Clockskew
        :param pulumi.Input[_builtins.bool] dev_mode: Dev mode
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] grant_types: Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
        :param pulumi.Input[_builtins.bool] id_token_role_assertion: ID token role assertion
        :param pulumi.Input[_builtins.bool] id_token_userinfo_assertion: Token userinfo assertion
        :param pulumi.Input[Union['ApplicationOidcLoginVersionArgs', 'ApplicationOidcLoginVersionArgsDict']] login_version: Specify the preferred login UI, where the user is redirected to for authentication. If unset, the login UI is chosen by the instance default.
        :param pulumi.Input[_builtins.str] name: Name of the application
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] post_logout_redirect_uris: Post logout redirect URIs
        :param pulumi.Input[_builtins.str] project_id: ID of the project
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: RedirectURIs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] response_types: Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        :param pulumi.Input[_builtins.bool] skip_native_app_success_page: Skip the successful login page on native apps and directly redirect the user to the callback.
        :param pulumi.Input[_builtins.str] version: Version, supported values: OIDC*VERSION*1_0
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApplicationOidcArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Resource representing an OIDC application belonging to a project, with all configuration possibilities.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.ApplicationOidc("default",
            project_id=default_zitadel_project["id"],
            org_id=default_zitadel_org["id"],
            name="applicationoidc",
            redirect_uris=["https://localhost.com"],
            response_types=["OIDC_RESPONSE_TYPE_CODE"],
            grant_types=["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
            post_logout_redirect_uris=["https://localhost.com"],
            app_type="OIDC_APP_TYPE_WEB",
            auth_method_type="OIDC_AUTH_METHOD_TYPE_BASIC",
            version="OIDC_VERSION_1_0",
            clock_skew="0s",
            dev_mode=True,
            access_token_type="OIDC_TOKEN_TYPE_BEARER",
            access_token_role_assertion=False,
            id_token_role_assertion=False,
            id_token_userinfo_assertion=False,
            additional_origins=[],
            skip_native_app_success_page=False)
        ```

        ## Import

        The resource can be imported using the ID format `<id:project_id[:org_id][:client_id][:client_secret]>`, e.g.

        ```sh
        $ pulumi import zitadel:index/applicationOidc:ApplicationOidc imported '123456789012345678:123456789012345678:123456789012345678:123456789012345678@zitadel:JuaDFFeOak5DGE655KCYPSAclSkbMVEJXXuX1lEMBT14eLMSs0A0qhafKX5SA2Df'
        ```


        :param str resource_name: The name of the resource.
        :param ApplicationOidcArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationOidcArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 access_token_type: pulumi.Input[Optional[_builtins.str]] = None,
                 additional_origins: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 app_type: pulumi.Input[Optional[_builtins.str]] = None,
                 auth_method_type: pulumi.Input[Optional[_builtins.str]] = None,
                 back_channel_logout_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 clock_skew: pulumi.Input[Optional[_builtins.str]] = None,
                 dev_mode: pulumi.Input[Optional[_builtins.bool]] = None,
                 grant_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 id_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 id_token_userinfo_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
                 login_version: pulumi.Input[Optional[Union['ApplicationOidcLoginVersionArgs', 'ApplicationOidcLoginVersionArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 post_logout_redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 response_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_native_app_success_page: pulumi.Input[Optional[_builtins.bool]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationOidcArgs.__new__(ApplicationOidcArgs)

            __props__.__dict__["access_token_role_assertion"] = access_token_role_assertion
            __props__.__dict__["access_token_type"] = access_token_type
            __props__.__dict__["additional_origins"] = additional_origins
            __props__.__dict__["app_type"] = app_type
            __props__.__dict__["auth_method_type"] = auth_method_type
            __props__.__dict__["back_channel_logout_uri"] = back_channel_logout_uri
            __props__.__dict__["clock_skew"] = clock_skew
            __props__.__dict__["dev_mode"] = dev_mode
            if grant_types is None and not opts.urn:
                raise TypeError("Missing required property 'grant_types'")
            __props__.__dict__["grant_types"] = grant_types
            __props__.__dict__["id_token_role_assertion"] = id_token_role_assertion
            __props__.__dict__["id_token_userinfo_assertion"] = id_token_userinfo_assertion
            __props__.__dict__["login_version"] = login_version
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["org_id"] = org_id
            __props__.__dict__["post_logout_redirect_uris"] = post_logout_redirect_uris
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            if redirect_uris is None and not opts.urn:
                raise TypeError("Missing required property 'redirect_uris'")
            __props__.__dict__["redirect_uris"] = redirect_uris
            if response_types is None and not opts.urn:
                raise TypeError("Missing required property 'response_types'")
            __props__.__dict__["response_types"] = response_types
            __props__.__dict__["skip_native_app_success_page"] = skip_native_app_success_page
            __props__.__dict__["version"] = version
            __props__.__dict__["client_id"] = None
            __props__.__dict__["client_secret"] = None
            __props__.__dict__["compliance_problems"] = None
            __props__.__dict__["none_compliant"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["clientId", "clientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ApplicationOidc, __self__).__init__(
            'zitadel:index/applicationOidc:ApplicationOidc',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            access_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
            access_token_type: pulumi.Input[Optional[_builtins.str]] = None,
            additional_origins: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            app_type: pulumi.Input[Optional[_builtins.str]] = None,
            auth_method_type: pulumi.Input[Optional[_builtins.str]] = None,
            back_channel_logout_uri: pulumi.Input[Optional[_builtins.str]] = None,
            client_id: pulumi.Input[Optional[_builtins.str]] = None,
            client_secret: pulumi.Input[Optional[_builtins.str]] = None,
            clock_skew: pulumi.Input[Optional[_builtins.str]] = None,
            compliance_problems: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ApplicationOidcComplianceProblemArgs', 'ApplicationOidcComplianceProblemArgsDict']]]]] = None,
            dev_mode: pulumi.Input[Optional[_builtins.bool]] = None,
            grant_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            id_token_role_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
            id_token_userinfo_assertion: pulumi.Input[Optional[_builtins.bool]] = None,
            login_version: pulumi.Input[Optional[Union['ApplicationOidcLoginVersionArgs', 'ApplicationOidcLoginVersionArgsDict']]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            none_compliant: pulumi.Input[Optional[_builtins.bool]] = None,
            org_id: pulumi.Input[Optional[_builtins.str]] = None,
            post_logout_redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            response_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            skip_native_app_success_page: pulumi.Input[Optional[_builtins.bool]] = None,
            version: pulumi.Input[Optional[_builtins.str]] = None) -> 'ApplicationOidc':
        """
        Get an existing ApplicationOidc resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] access_token_role_assertion: Access token role assertion
        :param pulumi.Input[_builtins.str] access_token_type: Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] additional_origins: Additional origins
        :param pulumi.Input[_builtins.str] app_type: App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        :param pulumi.Input[_builtins.str] auth_method_type: Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        :param pulumi.Input[_builtins.str] back_channel_logout_uri: ZITADEL will use this URI to notify the application about terminated session according to the OIDC Back-Channel Logout
        :param pulumi.Input[_builtins.str] client_id: generated ID for this config
        :param pulumi.Input[_builtins.str] client_secret: generated secret for this config
        :param pulumi.Input[_builtins.str] clock_skew: Clockskew
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApplicationOidcComplianceProblemArgs', 'ApplicationOidcComplianceProblemArgsDict']]]] compliance_problems: lists the problems for non-compliancy
        :param pulumi.Input[_builtins.bool] dev_mode: Dev mode
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] grant_types: Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
        :param pulumi.Input[_builtins.bool] id_token_role_assertion: ID token role assertion
        :param pulumi.Input[_builtins.bool] id_token_userinfo_assertion: Token userinfo assertion
        :param pulumi.Input[Union['ApplicationOidcLoginVersionArgs', 'ApplicationOidcLoginVersionArgsDict']] login_version: Specify the preferred login UI, where the user is redirected to for authentication. If unset, the login UI is chosen by the instance default.
        :param pulumi.Input[_builtins.str] name: Name of the application
        :param pulumi.Input[_builtins.bool] none_compliant: specifies whether the config is OIDC compliant. A production configuration SHOULD be compliant
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] post_logout_redirect_uris: Post logout redirect URIs
        :param pulumi.Input[_builtins.str] project_id: ID of the project
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: RedirectURIs
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] response_types: Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        :param pulumi.Input[_builtins.bool] skip_native_app_success_page: Skip the successful login page on native apps and directly redirect the user to the callback.
        :param pulumi.Input[_builtins.str] version: Version, supported values: OIDC*VERSION*1_0
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ApplicationOidcState.__new__(_ApplicationOidcState)

        __props__.__dict__["access_token_role_assertion"] = access_token_role_assertion
        __props__.__dict__["access_token_type"] = access_token_type
        __props__.__dict__["additional_origins"] = additional_origins
        __props__.__dict__["app_type"] = app_type
        __props__.__dict__["auth_method_type"] = auth_method_type
        __props__.__dict__["back_channel_logout_uri"] = back_channel_logout_uri
        __props__.__dict__["client_id"] = client_id
        __props__.__dict__["client_secret"] = client_secret
        __props__.__dict__["clock_skew"] = clock_skew
        __props__.__dict__["compliance_problems"] = compliance_problems
        __props__.__dict__["dev_mode"] = dev_mode
        __props__.__dict__["grant_types"] = grant_types
        __props__.__dict__["id_token_role_assertion"] = id_token_role_assertion
        __props__.__dict__["id_token_userinfo_assertion"] = id_token_userinfo_assertion
        __props__.__dict__["login_version"] = login_version
        __props__.__dict__["name"] = name
        __props__.__dict__["none_compliant"] = none_compliant
        __props__.__dict__["org_id"] = org_id
        __props__.__dict__["post_logout_redirect_uris"] = post_logout_redirect_uris
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["redirect_uris"] = redirect_uris
        __props__.__dict__["response_types"] = response_types
        __props__.__dict__["skip_native_app_success_page"] = skip_native_app_success_page
        __props__.__dict__["version"] = version
        return ApplicationOidc(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessTokenRoleAssertion")
    def access_token_role_assertion(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Access token role assertion
        """
        return pulumi.get(self, "access_token_role_assertion")

    @_builtins.property
    @pulumi.getter(name="accessTokenType")
    def access_token_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
        """
        return pulumi.get(self, "access_token_type")

    @_builtins.property
    @pulumi.getter(name="additionalOrigins")
    def additional_origins(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Additional origins
        """
        return pulumi.get(self, "additional_origins")

    @_builtins.property
    @pulumi.getter(name="appType")
    def app_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        App type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
        """
        return pulumi.get(self, "app_type")

    @_builtins.property
    @pulumi.getter(name="authMethodType")
    def auth_method_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
        """
        return pulumi.get(self, "auth_method_type")

    @_builtins.property
    @pulumi.getter(name="backChannelLogoutUri")
    def back_channel_logout_uri(self) -> pulumi.Output[_builtins.str]:
        """
        ZITADEL will use this URI to notify the application about terminated session according to the OIDC Back-Channel Logout
        """
        return pulumi.get(self, "back_channel_logout_uri")

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        """
        generated ID for this config
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[_builtins.str]:
        """
        generated secret for this config
        """
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter(name="clockSkew")
    def clock_skew(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Clockskew
        """
        return pulumi.get(self, "clock_skew")

    @_builtins.property
    @pulumi.getter(name="complianceProblems")
    def compliance_problems(self) -> pulumi.Output[Sequence['outputs.ApplicationOidcComplianceProblem']]:
        """
        lists the problems for non-compliancy
        """
        return pulumi.get(self, "compliance_problems")

    @_builtins.property
    @pulumi.getter(name="devMode")
    def dev_mode(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Dev mode
        """
        return pulumi.get(self, "dev_mode")

    @_builtins.property
    @pulumi.getter(name="grantTypes")
    def grant_types(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
        """
        return pulumi.get(self, "grant_types")

    @_builtins.property
    @pulumi.getter(name="idTokenRoleAssertion")
    def id_token_role_assertion(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        ID token role assertion
        """
        return pulumi.get(self, "id_token_role_assertion")

    @_builtins.property
    @pulumi.getter(name="idTokenUserinfoAssertion")
    def id_token_userinfo_assertion(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Token userinfo assertion
        """
        return pulumi.get(self, "id_token_userinfo_assertion")

    @_builtins.property
    @pulumi.getter(name="loginVersion")
    def login_version(self) -> pulumi.Output['outputs.ApplicationOidcLoginVersion']:
        """
        Specify the preferred login UI, where the user is redirected to for authentication. If unset, the login UI is chosen by the instance default.
        """
        return pulumi.get(self, "login_version")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the application
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="noneCompliant")
    def none_compliant(self) -> pulumi.Output[_builtins.bool]:
        """
        specifies whether the config is OIDC compliant. A production configuration SHOULD be compliant
        """
        return pulumi.get(self, "none_compliant")

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @_builtins.property
    @pulumi.getter(name="postLogoutRedirectUris")
    def post_logout_redirect_uris(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Post logout redirect URIs
        """
        return pulumi.get(self, "post_logout_redirect_uris")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the project
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        RedirectURIs
        """
        return pulumi.get(self, "redirect_uris")

    @_builtins.property
    @pulumi.getter(name="responseTypes")
    def response_types(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Response type, supported values: OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN*TOKEN
        """
        return pulumi.get(self, "response_types")

    @_builtins.property
    @pulumi.getter(name="skipNativeAppSuccessPage")
    def skip_native_app_success_page(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Skip the successful login page on native apps and directly redirect the user to the callback.
        """
        return pulumi.get(self, "skip_native_app_success_page")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Version, supported values: OIDC*VERSION*1_0
        """
        return pulumi.get(self, "version")

