# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ApplicationV2Args', 'ApplicationV2']

@pulumi.input_type
class ApplicationV2Args:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 api: pulumi.Input[Optional['ApplicationV2ApiArgs']] = None,
                 oidc: pulumi.Input[Optional['ApplicationV2OidcArgs']] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 saml: pulumi.Input[Optional['ApplicationV2SamlArgs']] = None):
        """
        The set of arguments for constructing a ApplicationV2 resource.

        :param pulumi.Input[_builtins.str] name: Name of the application.
        :param pulumi.Input[_builtins.str] project_id: ID of the project this application belongs to.
        :param pulumi.Input['ApplicationV2ApiArgs'] api: API configuration. Mutually exclusive with `oidc` and `saml`.
        :param pulumi.Input['ApplicationV2OidcArgs'] oidc: OIDC configuration. Mutually exclusive with `saml` and `api`.
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input['ApplicationV2SamlArgs'] saml: SAML configuration. Mutually exclusive with `oidc` and `api`.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "project_id", project_id)
        if api is not None:
            pulumi.set(__self__, "api", api)
        if oidc is not None:
            pulumi.set(__self__, "oidc", oidc)
        if org_id is not None:
            pulumi.set(__self__, "org_id", org_id)
        if saml is not None:
            pulumi.set(__self__, "saml", saml)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the application.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the project this application belongs to.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def api(self) -> pulumi.Input[Optional['ApplicationV2ApiArgs']]:
        """
        API configuration. Mutually exclusive with `oidc` and `saml`.
        """
        return pulumi.get(self, "api")

    @api.setter
    def api(self, value: pulumi.Input[Optional['ApplicationV2ApiArgs']]):
        pulumi.set(self, "api", value)

    @_builtins.property
    @pulumi.getter
    def oidc(self) -> pulumi.Input[Optional['ApplicationV2OidcArgs']]:
        """
        OIDC configuration. Mutually exclusive with `saml` and `api`.
        """
        return pulumi.get(self, "oidc")

    @oidc.setter
    def oidc(self, value: pulumi.Input[Optional['ApplicationV2OidcArgs']]):
        pulumi.set(self, "oidc", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_id", value)

    @_builtins.property
    @pulumi.getter
    def saml(self) -> pulumi.Input[Optional['ApplicationV2SamlArgs']]:
        """
        SAML configuration. Mutually exclusive with `oidc` and `api`.
        """
        return pulumi.get(self, "saml")

    @saml.setter
    def saml(self, value: pulumi.Input[Optional['ApplicationV2SamlArgs']]):
        pulumi.set(self, "saml", value)


@pulumi.input_type
class _ApplicationV2State:
    def __init__(__self__, *,
                 api: pulumi.Input[Optional['ApplicationV2ApiArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc: pulumi.Input[Optional['ApplicationV2OidcArgs']] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 saml: pulumi.Input[Optional['ApplicationV2SamlArgs']] = None,
                 state: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ApplicationV2 resources.

        :param pulumi.Input['ApplicationV2ApiArgs'] api: API configuration. Mutually exclusive with `oidc` and `saml`.
        :param pulumi.Input[_builtins.str] name: Name of the application.
        :param pulumi.Input['ApplicationV2OidcArgs'] oidc: OIDC configuration. Mutually exclusive with `saml` and `api`.
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[_builtins.str] project_id: ID of the project this application belongs to.
        :param pulumi.Input['ApplicationV2SamlArgs'] saml: SAML configuration. Mutually exclusive with `oidc` and `api`.
        :param pulumi.Input[_builtins.str] state: State of the application.
        """
        if api is not None:
            pulumi.set(__self__, "api", api)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if oidc is not None:
            pulumi.set(__self__, "oidc", oidc)
        if org_id is not None:
            pulumi.set(__self__, "org_id", org_id)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if saml is not None:
            pulumi.set(__self__, "saml", saml)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @_builtins.property
    @pulumi.getter
    def api(self) -> pulumi.Input[Optional['ApplicationV2ApiArgs']]:
        """
        API configuration. Mutually exclusive with `oidc` and `saml`.
        """
        return pulumi.get(self, "api")

    @api.setter
    def api(self, value: pulumi.Input[Optional['ApplicationV2ApiArgs']]):
        pulumi.set(self, "api", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the application.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def oidc(self) -> pulumi.Input[Optional['ApplicationV2OidcArgs']]:
        """
        OIDC configuration. Mutually exclusive with `saml` and `api`.
        """
        return pulumi.get(self, "oidc")

    @oidc.setter
    def oidc(self, value: pulumi.Input[Optional['ApplicationV2OidcArgs']]):
        pulumi.set(self, "oidc", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_id", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the project this application belongs to.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def saml(self) -> pulumi.Input[Optional['ApplicationV2SamlArgs']]:
        """
        SAML configuration. Mutually exclusive with `oidc` and `api`.
        """
        return pulumi.get(self, "saml")

    @saml.setter
    def saml(self, value: pulumi.Input[Optional['ApplicationV2SamlArgs']]):
        pulumi.set(self, "saml", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        State of the application.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "state", value)


@pulumi.type_token("zitadel:index/applicationV2:ApplicationV2")
class ApplicationV2(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api: pulumi.Input[Optional[Union['ApplicationV2ApiArgs', 'ApplicationV2ApiArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc: pulumi.Input[Optional[Union['ApplicationV2OidcArgs', 'ApplicationV2OidcArgsDict']]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 saml: pulumi.Input[Optional[Union['ApplicationV2SamlArgs', 'ApplicationV2SamlArgsDict']]] = None,
                 __props__=None):
        """
        Resource representing an application belonging to a project. Exposes the unified Zitadel Application v2 API; the application type is selected by populating exactly one of the oidc/saml/api configuration blocks.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.ApplicationV2("default",
            project_id=default_zitadel_project["id"],
            org_id=default_zitadel_org["id"],
            name="applicationv2",
            oidc={
                "redirect_uris": ["https://localhost.com"],
                "response_types": ["OIDC_RESPONSE_TYPE_CODE"],
                "grant_types": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
                "post_logout_redirect_uris": ["https://localhost.com"],
                "app_type": "OIDC_APP_TYPE_WEB",
                "auth_method_type": "OIDC_AUTH_METHOD_TYPE_BASIC",
                "version": "OIDC_VERSION_1_0",
                "clock_skew": "0s",
                "dev_mode": True,
                "access_token_type": "OIDC_TOKEN_TYPE_BEARER",
                "access_token_role_assertion": False,
                "id_token_role_assertion": False,
                "id_token_userinfo_assertion": False,
                "additional_origins": [],
                "skip_native_app_success_page": False,
            })
        ```

        ## Import

        The resource can be imported using the ID format `<id[:org_id[:client_secret]]>`, e.g.
        project_id is refreshed from the v2 API on the first read and does not need to
        be passed at import time.

        ```sh
        $ pulumi import zitadel:index/applicationV2:ApplicationV2 imported '123456789012345678:123456789012345678'
        ```

        For OIDC/API applications with a generated client secret, pass the secret as
        the optional final segment so it is preserved in state (it is never returned
        by the read API). See the "Migrating to the v2 resources" guide for details.

        ```sh
        $ pulumi import zitadel:index/applicationV2:ApplicationV2 imported '123456789012345678:123456789012345678:THE_CLIENT_SECRET'
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ApplicationV2ApiArgs', 'ApplicationV2ApiArgsDict']] api: API configuration. Mutually exclusive with `oidc` and `saml`.
        :param pulumi.Input[_builtins.str] name: Name of the application.
        :param pulumi.Input[Union['ApplicationV2OidcArgs', 'ApplicationV2OidcArgsDict']] oidc: OIDC configuration. Mutually exclusive with `saml` and `api`.
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[_builtins.str] project_id: ID of the project this application belongs to.
        :param pulumi.Input[Union['ApplicationV2SamlArgs', 'ApplicationV2SamlArgsDict']] saml: SAML configuration. Mutually exclusive with `oidc` and `api`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApplicationV2Args,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Resource representing an application belonging to a project. Exposes the unified Zitadel Application v2 API; the application type is selected by populating exactly one of the oidc/saml/api configuration blocks.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.ApplicationV2("default",
            project_id=default_zitadel_project["id"],
            org_id=default_zitadel_org["id"],
            name="applicationv2",
            oidc={
                "redirect_uris": ["https://localhost.com"],
                "response_types": ["OIDC_RESPONSE_TYPE_CODE"],
                "grant_types": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
                "post_logout_redirect_uris": ["https://localhost.com"],
                "app_type": "OIDC_APP_TYPE_WEB",
                "auth_method_type": "OIDC_AUTH_METHOD_TYPE_BASIC",
                "version": "OIDC_VERSION_1_0",
                "clock_skew": "0s",
                "dev_mode": True,
                "access_token_type": "OIDC_TOKEN_TYPE_BEARER",
                "access_token_role_assertion": False,
                "id_token_role_assertion": False,
                "id_token_userinfo_assertion": False,
                "additional_origins": [],
                "skip_native_app_success_page": False,
            })
        ```

        ## Import

        The resource can be imported using the ID format `<id[:org_id[:client_secret]]>`, e.g.
        project_id is refreshed from the v2 API on the first read and does not need to
        be passed at import time.

        ```sh
        $ pulumi import zitadel:index/applicationV2:ApplicationV2 imported '123456789012345678:123456789012345678'
        ```

        For OIDC/API applications with a generated client secret, pass the secret as
        the optional final segment so it is preserved in state (it is never returned
        by the read API). See the "Migrating to the v2 resources" guide for details.

        ```sh
        $ pulumi import zitadel:index/applicationV2:ApplicationV2 imported '123456789012345678:123456789012345678:THE_CLIENT_SECRET'
        ```


        :param str resource_name: The name of the resource.
        :param ApplicationV2Args args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationV2Args, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api: pulumi.Input[Optional[Union['ApplicationV2ApiArgs', 'ApplicationV2ApiArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc: pulumi.Input[Optional[Union['ApplicationV2OidcArgs', 'ApplicationV2OidcArgsDict']]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 saml: pulumi.Input[Optional[Union['ApplicationV2SamlArgs', 'ApplicationV2SamlArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationV2Args.__new__(ApplicationV2Args)

            __props__.__dict__["api"] = api
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["oidc"] = oidc
            __props__.__dict__["org_id"] = org_id
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["saml"] = saml
            __props__.__dict__["state"] = None
        super(ApplicationV2, __self__).__init__(
            'zitadel:index/applicationV2:ApplicationV2',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            api: pulumi.Input[Optional[Union['ApplicationV2ApiArgs', 'ApplicationV2ApiArgsDict']]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            oidc: pulumi.Input[Optional[Union['ApplicationV2OidcArgs', 'ApplicationV2OidcArgsDict']]] = None,
            org_id: pulumi.Input[Optional[_builtins.str]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            saml: pulumi.Input[Optional[Union['ApplicationV2SamlArgs', 'ApplicationV2SamlArgsDict']]] = None,
            state: pulumi.Input[Optional[_builtins.str]] = None) -> 'ApplicationV2':
        """
        Get an existing ApplicationV2 resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ApplicationV2ApiArgs', 'ApplicationV2ApiArgsDict']] api: API configuration. Mutually exclusive with `oidc` and `saml`.
        :param pulumi.Input[_builtins.str] name: Name of the application.
        :param pulumi.Input[Union['ApplicationV2OidcArgs', 'ApplicationV2OidcArgsDict']] oidc: OIDC configuration. Mutually exclusive with `saml` and `api`.
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[_builtins.str] project_id: ID of the project this application belongs to.
        :param pulumi.Input[Union['ApplicationV2SamlArgs', 'ApplicationV2SamlArgsDict']] saml: SAML configuration. Mutually exclusive with `oidc` and `api`.
        :param pulumi.Input[_builtins.str] state: State of the application.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ApplicationV2State.__new__(_ApplicationV2State)

        __props__.__dict__["api"] = api
        __props__.__dict__["name"] = name
        __props__.__dict__["oidc"] = oidc
        __props__.__dict__["org_id"] = org_id
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["saml"] = saml
        __props__.__dict__["state"] = state
        return ApplicationV2(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def api(self) -> pulumi.Output[Optional['outputs.ApplicationV2Api']]:
        """
        API configuration. Mutually exclusive with `oidc` and `saml`.
        """
        return pulumi.get(self, "api")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the application.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def oidc(self) -> pulumi.Output[Optional['outputs.ApplicationV2Oidc']]:
        """
        OIDC configuration. Mutually exclusive with `saml` and `api`.
        """
        return pulumi.get(self, "oidc")

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the project this application belongs to.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def saml(self) -> pulumi.Output[Optional['outputs.ApplicationV2Saml']]:
        """
        SAML configuration. Mutually exclusive with `oidc` and `api`.
        """
        return pulumi.get(self, "saml")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[_builtins.str]:
        """
        State of the application.
        """
        return pulumi.get(self, "state")

