# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DefaultPasswordAgePolicyArgs', 'DefaultPasswordAgePolicy']

@pulumi.input_type
class DefaultPasswordAgePolicyArgs:
    def __init__(__self__, *,
                 expire_warn_days: pulumi.Input[_builtins.int],
                 max_age_days: pulumi.Input[_builtins.int]):
        """
        The set of arguments for constructing a DefaultPasswordAgePolicy resource.

        :param pulumi.Input[_builtins.int] expire_warn_days: amount of days after which the user should be notified of the upcoming expiry
        :param pulumi.Input[_builtins.int] max_age_days: amount of days after which a password will expire
        """
        pulumi.set(__self__, "expire_warn_days", expire_warn_days)
        pulumi.set(__self__, "max_age_days", max_age_days)

    @_builtins.property
    @pulumi.getter(name="expireWarnDays")
    def expire_warn_days(self) -> pulumi.Input[_builtins.int]:
        """
        amount of days after which the user should be notified of the upcoming expiry
        """
        return pulumi.get(self, "expire_warn_days")

    @expire_warn_days.setter
    def expire_warn_days(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "expire_warn_days", value)

    @_builtins.property
    @pulumi.getter(name="maxAgeDays")
    def max_age_days(self) -> pulumi.Input[_builtins.int]:
        """
        amount of days after which a password will expire
        """
        return pulumi.get(self, "max_age_days")

    @max_age_days.setter
    def max_age_days(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "max_age_days", value)


@pulumi.input_type
class _DefaultPasswordAgePolicyState:
    def __init__(__self__, *,
                 expire_warn_days: pulumi.Input[Optional[_builtins.int]] = None,
                 max_age_days: pulumi.Input[Optional[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering DefaultPasswordAgePolicy resources.

        :param pulumi.Input[_builtins.int] expire_warn_days: amount of days after which the user should be notified of the upcoming expiry
        :param pulumi.Input[_builtins.int] max_age_days: amount of days after which a password will expire
        """
        if expire_warn_days is not None:
            pulumi.set(__self__, "expire_warn_days", expire_warn_days)
        if max_age_days is not None:
            pulumi.set(__self__, "max_age_days", max_age_days)

    @_builtins.property
    @pulumi.getter(name="expireWarnDays")
    def expire_warn_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        amount of days after which the user should be notified of the upcoming expiry
        """
        return pulumi.get(self, "expire_warn_days")

    @expire_warn_days.setter
    def expire_warn_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "expire_warn_days", value)

    @_builtins.property
    @pulumi.getter(name="maxAgeDays")
    def max_age_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        amount of days after which a password will expire
        """
        return pulumi.get(self, "max_age_days")

    @max_age_days.setter
    def max_age_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "max_age_days", value)


@pulumi.type_token("zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy")
class DefaultPasswordAgePolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expire_warn_days: pulumi.Input[Optional[_builtins.int]] = None,
                 max_age_days: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        Resource representing the default password age policy.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.DefaultPasswordAgePolicy("default",
            max_age_days=30,
            expire_warn_days=5)
        ```

        ## Import

        The resource can be imported using the ID format `<>`, e.g.

        ```sh
        $ pulumi import zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy imported ''
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] expire_warn_days: amount of days after which the user should be notified of the upcoming expiry
        :param pulumi.Input[_builtins.int] max_age_days: amount of days after which a password will expire
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DefaultPasswordAgePolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Resource representing the default password age policy.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.DefaultPasswordAgePolicy("default",
            max_age_days=30,
            expire_warn_days=5)
        ```

        ## Import

        The resource can be imported using the ID format `<>`, e.g.

        ```sh
        $ pulumi import zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy imported ''
        ```


        :param str resource_name: The name of the resource.
        :param DefaultPasswordAgePolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DefaultPasswordAgePolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expire_warn_days: pulumi.Input[Optional[_builtins.int]] = None,
                 max_age_days: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DefaultPasswordAgePolicyArgs.__new__(DefaultPasswordAgePolicyArgs)

            if expire_warn_days is None and not opts.urn:
                raise TypeError("Missing required property 'expire_warn_days'")
            __props__.__dict__["expire_warn_days"] = expire_warn_days
            if max_age_days is None and not opts.urn:
                raise TypeError("Missing required property 'max_age_days'")
            __props__.__dict__["max_age_days"] = max_age_days
        super(DefaultPasswordAgePolicy, __self__).__init__(
            'zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            expire_warn_days: pulumi.Input[Optional[_builtins.int]] = None,
            max_age_days: pulumi.Input[Optional[_builtins.int]] = None) -> 'DefaultPasswordAgePolicy':
        """
        Get an existing DefaultPasswordAgePolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] expire_warn_days: amount of days after which the user should be notified of the upcoming expiry
        :param pulumi.Input[_builtins.int] max_age_days: amount of days after which a password will expire
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DefaultPasswordAgePolicyState.__new__(_DefaultPasswordAgePolicyState)

        __props__.__dict__["expire_warn_days"] = expire_warn_days
        __props__.__dict__["max_age_days"] = max_age_days
        return DefaultPasswordAgePolicy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="expireWarnDays")
    def expire_warn_days(self) -> pulumi.Output[_builtins.int]:
        """
        amount of days after which the user should be notified of the upcoming expiry
        """
        return pulumi.get(self, "expire_warn_days")

    @_builtins.property
    @pulumi.getter(name="maxAgeDays")
    def max_age_days(self) -> pulumi.Output[_builtins.int]:
        """
        amount of days after which a password will expire
        """
        return pulumi.get(self, "max_age_days")

