# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetActionResult',
    'AwaitableGetActionResult',
    'get_action',
    'get_action_output',
]

@pulumi.output_type
class GetActionResult:
    """
    A collection of values returned by getAction.
    """
    def __init__(__self__, action_id=None, allowed_to_fail=None, id=None, name=None, org_id=None, script=None, state=None, timeout=None):
        if action_id and not isinstance(action_id, str):
            raise TypeError("Expected argument 'action_id' to be a str")
        pulumi.set(__self__, "action_id", action_id)
        if allowed_to_fail and not isinstance(allowed_to_fail, bool):
            raise TypeError("Expected argument 'allowed_to_fail' to be a bool")
        pulumi.set(__self__, "allowed_to_fail", allowed_to_fail)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if org_id and not isinstance(org_id, str):
            raise TypeError("Expected argument 'org_id' to be a str")
        pulumi.set(__self__, "org_id", org_id)
        if script and not isinstance(script, str):
            raise TypeError("Expected argument 'script' to be a str")
        pulumi.set(__self__, "script", script)
        if state and not isinstance(state, int):
            raise TypeError("Expected argument 'state' to be a int")
        pulumi.set(__self__, "state", state)
        if timeout and not isinstance(timeout, str):
            raise TypeError("Expected argument 'timeout' to be a str")
        pulumi.set(__self__, "timeout", timeout)

    @_builtins.property
    @pulumi.getter(name="actionId")
    def action_id(self) -> _builtins.str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "action_id")

    @_builtins.property
    @pulumi.getter(name="allowedToFail")
    def allowed_to_fail(self) -> _builtins.bool:
        """
        when true, the next action will be called even if this action fails
        """
        return pulumi.get(self, "allowed_to_fail")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> Optional[_builtins.str]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @_builtins.property
    @pulumi.getter
    def script(self) -> _builtins.str:
        return pulumi.get(self, "script")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.int:
        """
        the state of the action
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> _builtins.str:
        """
        after which time the action will be terminated if not finished
        """
        return pulumi.get(self, "timeout")


class AwaitableGetActionResult(GetActionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetActionResult(
            action_id=self.action_id,
            allowed_to_fail=self.allowed_to_fail,
            id=self.id,
            name=self.name,
            org_id=self.org_id,
            script=self.script,
            state=self.state,
            timeout=self.timeout)


def get_action(action_id: Optional[_builtins.str] = None,
               org_id: Optional[_builtins.str] = None,
               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetActionResult:
    """
    Datasource representing an action belonging to an organization.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_zitadel as zitadel

    default = zitadel.get_action(org_id=default_zitadel_org["id"],
        action_id="123456789012345678")
    pulumi.export("action", default)
    ```


    :param _builtins.str action_id: The ID of this resource.
    :param _builtins.str org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
    """
    __args__ = dict()
    __args__['actionId'] = action_id
    __args__['orgId'] = org_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zitadel:index/getAction:getAction', __args__, opts=opts, typ=GetActionResult).value

    return AwaitableGetActionResult(
        action_id=pulumi.get(__ret__, 'action_id'),
        allowed_to_fail=pulumi.get(__ret__, 'allowed_to_fail'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        org_id=pulumi.get(__ret__, 'org_id'),
        script=pulumi.get(__ret__, 'script'),
        state=pulumi.get(__ret__, 'state'),
        timeout=pulumi.get(__ret__, 'timeout'))
def get_action_output(action_id: pulumi.Input[Optional[_builtins.str]] = None,
                      org_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetActionResult]:
    """
    Datasource representing an action belonging to an organization.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_zitadel as zitadel

    default = zitadel.get_action(org_id=default_zitadel_org["id"],
        action_id="123456789012345678")
    pulumi.export("action", default)
    ```


    :param _builtins.str action_id: The ID of this resource.
    :param _builtins.str org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
    """
    __args__ = dict()
    __args__['actionId'] = action_id
    __args__['orgId'] = org_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zitadel:index/getAction:getAction', __args__, opts=opts, typ=GetActionResult)
    return __ret__.apply(lambda __response__: GetActionResult(
        action_id=pulumi.get(__response__, 'action_id'),
        allowed_to_fail=pulumi.get(__response__, 'allowed_to_fail'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        org_id=pulumi.get(__response__, 'org_id'),
        script=pulumi.get(__response__, 'script'),
        state=pulumi.get(__response__, 'state'),
        timeout=pulumi.get(__response__, 'timeout')))
