# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetOrganizationDomainsResult',
    'AwaitableGetOrganizationDomainsResult',
    'get_organization_domains',
    'get_organization_domains_output',
]

@pulumi.output_type
class GetOrganizationDomainsResult:
    """
    A collection of values returned by getOrganizationDomains.
    """
    def __init__(__self__, domain=None, domains=None, id=None, organization_id=None):
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if domains and not isinstance(domains, list):
            raise TypeError("Expected argument 'domains' to be a list")
        pulumi.set(__self__, "domains", domains)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if organization_id and not isinstance(organization_id, str):
            raise TypeError("Expected argument 'organization_id' to be a str")
        pulumi.set(__self__, "organization_id", organization_id)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[_builtins.str]:
        """
        Filter domains by name
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def domains(self) -> Sequence['outputs.GetOrganizationDomainsDomainResult']:
        """
        List of organization domains
        """
        return pulumi.get(self, "domains")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> _builtins.str:
        """
        ID of the organization
        """
        return pulumi.get(self, "organization_id")


class AwaitableGetOrganizationDomainsResult(GetOrganizationDomainsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOrganizationDomainsResult(
            domain=self.domain,
            domains=self.domains,
            id=self.id,
            organization_id=self.organization_id)


def get_organization_domains(domain: Optional[_builtins.str] = None,
                             organization_id: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOrganizationDomainsResult:
    """
    Datasource representing domains of an organization in ZITADEL.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_zitadel as zitadel

    default = zitadel.get_organization_domains(organization_id="123456789012345678")
    filtered = zitadel.get_organization_domains(organization_id="123456789012345678",
        domain="example.com")
    pulumi.export("allDomains", default.domains)
    ```


    :param _builtins.str domain: Filter domains by name
    :param _builtins.str organization_id: ID of the organization
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['organizationId'] = organization_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zitadel:index/getOrganizationDomains:getOrganizationDomains', __args__, opts=opts, typ=GetOrganizationDomainsResult).value

    return AwaitableGetOrganizationDomainsResult(
        domain=pulumi.get(__ret__, 'domain'),
        domains=pulumi.get(__ret__, 'domains'),
        id=pulumi.get(__ret__, 'id'),
        organization_id=pulumi.get(__ret__, 'organization_id'))
def get_organization_domains_output(domain: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                    organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetOrganizationDomainsResult]:
    """
    Datasource representing domains of an organization in ZITADEL.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_zitadel as zitadel

    default = zitadel.get_organization_domains(organization_id="123456789012345678")
    filtered = zitadel.get_organization_domains(organization_id="123456789012345678",
        domain="example.com")
    pulumi.export("allDomains", default.domains)
    ```


    :param _builtins.str domain: Filter domains by name
    :param _builtins.str organization_id: ID of the organization
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['organizationId'] = organization_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zitadel:index/getOrganizationDomains:getOrganizationDomains', __args__, opts=opts, typ=GetOrganizationDomainsResult)
    return __ret__.apply(lambda __response__: GetOrganizationDomainsResult(
        domain=pulumi.get(__response__, 'domain'),
        domains=pulumi.get(__response__, 'domains'),
        id=pulumi.get(__response__, 'id'),
        organization_id=pulumi.get(__response__, 'organization_id')))
