# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetOrganizationDomainResult',
    'AwaitableGetOrganizationDomainResult',
    'get_organization_domain',
    'get_organization_domain_output',
]

@pulumi.output_type
class GetOrganizationDomainResult:
    """
    A collection of values returned by getOrganizationDomain.
    """
    def __init__(__self__, domain=None, id=None, is_primary=None, is_verified=None, organization_id=None, validation_type=None):
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if is_primary and not isinstance(is_primary, bool):
            raise TypeError("Expected argument 'is_primary' to be a bool")
        pulumi.set(__self__, "is_primary", is_primary)
        if is_verified and not isinstance(is_verified, bool):
            raise TypeError("Expected argument 'is_verified' to be a bool")
        pulumi.set(__self__, "is_verified", is_verified)
        if organization_id and not isinstance(organization_id, str):
            raise TypeError("Expected argument 'organization_id' to be a str")
        pulumi.set(__self__, "organization_id", organization_id)
        if validation_type and not isinstance(validation_type, str):
            raise TypeError("Expected argument 'validation_type' to be a str")
        pulumi.set(__self__, "validation_type", validation_type)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> _builtins.str:
        """
        Domain name
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="isPrimary")
    def is_primary(self) -> _builtins.bool:
        """
        Whether this is the primary domain of the organization
        """
        return pulumi.get(self, "is_primary")

    @_builtins.property
    @pulumi.getter(name="isVerified")
    def is_verified(self) -> _builtins.bool:
        """
        Whether the domain has been verified
        """
        return pulumi.get(self, "is_verified")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> _builtins.str:
        """
        ID of the organization
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter(name="validationType")
    def validation_type(self) -> _builtins.str:
        """
        Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
        """
        return pulumi.get(self, "validation_type")


class AwaitableGetOrganizationDomainResult(GetOrganizationDomainResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOrganizationDomainResult(
            domain=self.domain,
            id=self.id,
            is_primary=self.is_primary,
            is_verified=self.is_verified,
            organization_id=self.organization_id,
            validation_type=self.validation_type)


def get_organization_domain(domain: Optional[_builtins.str] = None,
                            organization_id: Optional[_builtins.str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOrganizationDomainResult:
    """
    Datasource representing a domain of an organization in ZITADEL.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_zitadel as zitadel

    default = zitadel.get_organization_domain(organization_id="123456789012345678",
        domain="example.com")
    pulumi.export("domainVerified", default.is_verified)
    ```


    :param _builtins.str domain: Domain name
    :param _builtins.str organization_id: ID of the organization
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['organizationId'] = organization_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zitadel:index/getOrganizationDomain:getOrganizationDomain', __args__, opts=opts, typ=GetOrganizationDomainResult).value

    return AwaitableGetOrganizationDomainResult(
        domain=pulumi.get(__ret__, 'domain'),
        id=pulumi.get(__ret__, 'id'),
        is_primary=pulumi.get(__ret__, 'is_primary'),
        is_verified=pulumi.get(__ret__, 'is_verified'),
        organization_id=pulumi.get(__ret__, 'organization_id'),
        validation_type=pulumi.get(__ret__, 'validation_type'))
def get_organization_domain_output(domain: pulumi.Input[Optional[_builtins.str]] = None,
                                   organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetOrganizationDomainResult]:
    """
    Datasource representing a domain of an organization in ZITADEL.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_zitadel as zitadel

    default = zitadel.get_organization_domain(organization_id="123456789012345678",
        domain="example.com")
    pulumi.export("domainVerified", default.is_verified)
    ```


    :param _builtins.str domain: Domain name
    :param _builtins.str organization_id: ID of the organization
    """
    __args__ = dict()
    __args__['domain'] = domain
    __args__['organizationId'] = organization_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zitadel:index/getOrganizationDomain:getOrganizationDomain', __args__, opts=opts, typ=GetOrganizationDomainResult)
    return __ret__.apply(lambda __response__: GetOrganizationDomainResult(
        domain=pulumi.get(__response__, 'domain'),
        id=pulumi.get(__response__, 'id'),
        is_primary=pulumi.get(__response__, 'is_primary'),
        is_verified=pulumi.get(__response__, 'is_verified'),
        organization_id=pulumi.get(__response__, 'organization_id'),
        validation_type=pulumi.get(__response__, 'validation_type')))
