# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetProjectsV2Result',
    'AwaitableGetProjectsV2Result',
    'get_projects_v2',
    'get_projects_v2_output',
]

@pulumi.output_type
class GetProjectsV2Result:
    """
    A collection of values returned by getProjectsV2.
    """
    def __init__(__self__, id=None, name=None, name_method=None, org_id=None, project_ids=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if name_method and not isinstance(name_method, str):
            raise TypeError("Expected argument 'name_method' to be a str")
        pulumi.set(__self__, "name_method", name_method)
        if org_id and not isinstance(org_id, str):
            raise TypeError("Expected argument 'org_id' to be a str")
        pulumi.set(__self__, "org_id", org_id)
        if project_ids and not isinstance(project_ids, list):
            raise TypeError("Expected argument 'project_ids' to be a list")
        pulumi.set(__self__, "project_ids", project_ids)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Name of the project
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="nameMethod")
    def name_method(self) -> Optional[_builtins.str]:
        """
        Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
        """
        return pulumi.get(self, "name_method")

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> Optional[_builtins.str]:
        """
        ID of the organization
        """
        return pulumi.get(self, "org_id")

    @_builtins.property
    @pulumi.getter(name="projectIds")
    def project_ids(self) -> Sequence[_builtins.str]:
        """
        IDs of the projects matching the name filter.
        """
        return pulumi.get(self, "project_ids")


class AwaitableGetProjectsV2Result(GetProjectsV2Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetProjectsV2Result(
            id=self.id,
            name=self.name,
            name_method=self.name_method,
            org_id=self.org_id,
            project_ids=self.project_ids)


def get_projects_v2(name: Optional[_builtins.str] = None,
                    name_method: Optional[_builtins.str] = None,
                    org_id: Optional[_builtins.str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetProjectsV2Result:
    """
    Datasource representing the project, which can then be granted to different organizations or users directly, containing different applications.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_std as std
    import pulumi_zitadel as zitadel

    default = zitadel.get_projects_v2(org_id=default_zitadel_org["id"],
        name="example-name",
        name_method="TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE")
    default_get_project_v2 = {str(__key): zitadel.get_project_v2(project_id=__value) for __key, __value in enumerate(std.toset(input=default.project_ids).result)}
    pulumi.export("projectV2Names", std.toset(input=[project.name for project in default_get_project_v2.values()]).result)
    ```


    :param _builtins.str name: Name of the project
    :param _builtins.str name_method: Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
    :param _builtins.str org_id: ID of the organization
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['nameMethod'] = name_method
    __args__['orgId'] = org_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zitadel:index/getProjectsV2:getProjectsV2', __args__, opts=opts, typ=GetProjectsV2Result).value

    return AwaitableGetProjectsV2Result(
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        name_method=pulumi.get(__ret__, 'name_method'),
        org_id=pulumi.get(__ret__, 'org_id'),
        project_ids=pulumi.get(__ret__, 'project_ids'))
def get_projects_v2_output(name: pulumi.Input[Optional[_builtins.str]] = None,
                           name_method: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                           org_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetProjectsV2Result]:
    """
    Datasource representing the project, which can then be granted to different organizations or users directly, containing different applications.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_std as std
    import pulumi_zitadel as zitadel

    default = zitadel.get_projects_v2(org_id=default_zitadel_org["id"],
        name="example-name",
        name_method="TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE")
    default_get_project_v2 = {str(__key): zitadel.get_project_v2(project_id=__value) for __key, __value in enumerate(std.toset(input=default.project_ids).result)}
    pulumi.export("projectV2Names", std.toset(input=[project.name for project in default_get_project_v2.values()]).result)
    ```


    :param _builtins.str name: Name of the project
    :param _builtins.str name_method: Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
    :param _builtins.str org_id: ID of the organization
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['nameMethod'] = name_method
    __args__['orgId'] = org_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zitadel:index/getProjectsV2:getProjectsV2', __args__, opts=opts, typ=GetProjectsV2Result)
    return __ret__.apply(lambda __response__: GetProjectsV2Result(
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        name_method=pulumi.get(__response__, 'name_method'),
        org_id=pulumi.get(__response__, 'org_id'),
        project_ids=pulumi.get(__response__, 'project_ids')))
