# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['HostedLoginTranslationArgs', 'HostedLoginTranslation']

@pulumi.input_type
class HostedLoginTranslationArgs:
    def __init__(__self__, *,
                 language: pulumi.Input[_builtins.str],
                 translations: pulumi.Input[_builtins.str],
                 org_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a HostedLoginTranslation resource.

        :param pulumi.Input[_builtins.str] language: BCP 47 language tag of the translations, e.g. `en`, `de` or `fr-CH`
        :param pulumi.Input[_builtins.str] translations: Translations as a JSON object with at least one key, for example built with `jsonencode`. The keys follow the structure of the [hosted login locale files](https://github.com/zitadel/zitadel/tree/main/apps/login/locales), e.g. `loginname.title`. Replaces all translations previously set for this language on the organization.
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        pulumi.set(__self__, "language", language)
        pulumi.set(__self__, "translations", translations)
        if org_id is not None:
            pulumi.set(__self__, "org_id", org_id)

    @_builtins.property
    @pulumi.getter
    def language(self) -> pulumi.Input[_builtins.str]:
        """
        BCP 47 language tag of the translations, e.g. `en`, `de` or `fr-CH`
        """
        return pulumi.get(self, "language")

    @language.setter
    def language(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "language", value)

    @_builtins.property
    @pulumi.getter
    def translations(self) -> pulumi.Input[_builtins.str]:
        """
        Translations as a JSON object with at least one key, for example built with `jsonencode`. The keys follow the structure of the [hosted login locale files](https://github.com/zitadel/zitadel/tree/main/apps/login/locales), e.g. `loginname.title`. Replaces all translations previously set for this language on the organization.
        """
        return pulumi.get(self, "translations")

    @translations.setter
    def translations(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "translations", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_id", value)


@pulumi.input_type
class _HostedLoginTranslationState:
    def __init__(__self__, *,
                 language: pulumi.Input[Optional[_builtins.str]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 translations: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering HostedLoginTranslation resources.

        :param pulumi.Input[_builtins.str] language: BCP 47 language tag of the translations, e.g. `en`, `de` or `fr-CH`
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[_builtins.str] translations: Translations as a JSON object with at least one key, for example built with `jsonencode`. The keys follow the structure of the [hosted login locale files](https://github.com/zitadel/zitadel/tree/main/apps/login/locales), e.g. `loginname.title`. Replaces all translations previously set for this language on the organization.
        """
        if language is not None:
            pulumi.set(__self__, "language", language)
        if org_id is not None:
            pulumi.set(__self__, "org_id", org_id)
        if translations is not None:
            pulumi.set(__self__, "translations", translations)

    @_builtins.property
    @pulumi.getter
    def language(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        BCP 47 language tag of the translations, e.g. `en`, `de` or `fr-CH`
        """
        return pulumi.get(self, "language")

    @language.setter
    def language(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "language", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_id", value)

    @_builtins.property
    @pulumi.getter
    def translations(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Translations as a JSON object with at least one key, for example built with `jsonencode`. The keys follow the structure of the [hosted login locale files](https://github.com/zitadel/zitadel/tree/main/apps/login/locales), e.g. `loginname.title`. Replaces all translations previously set for this language on the organization.
        """
        return pulumi.get(self, "translations")

    @translations.setter
    def translations(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "translations", value)


@pulumi.type_token("zitadel:index/hostedLoginTranslation:HostedLoginTranslation")
class HostedLoginTranslation(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 language: pulumi.Input[Optional[_builtins.str]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 translations: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Organization-level translations for the **hosted login v2** (`/ui/v2/login`) in one language, using the settings/v2 API. **Requires ZITADEL 4.x.** ZITADEL checks the instance-level `iam.policy.read` and `iam.policy.write` permissions for these translations, so the service account needs an instance role such as `IAM_OWNER`; `ORG_OWNER` is not sufficient. Keys that are not set fall back to the instance-level translations and then to the built-in translations of the hosted login. ZITADEL has no API to remove translations, so destroying this resource only removes it from the Terraform state and leaves the last applied translations in place. Instance-level defaults are managed by `DefaultHostedLoginTranslation`. The legacy login UI (v1) is customized with `LoginTexts`.

        ## Example Usage

        ```python
        import pulumi
        import json
        import scoretechnologies_zitadel as zitadel

        default = zitadel.HostedLoginTranslation("default",
            org_id=default_zitadel_org["id"],
            language="en",
            translations=json.dumps({
                "loginname": {
                    "title": "Welcome to ACME",
                    "description": "Sign in with your ACME account.",
                },
            }))
        ```

        ## Import

        The resource can be imported using the ID format `<language[:org_id]>`, e.g.

        ```sh
        $ pulumi import zitadel:index/hostedLoginTranslation:HostedLoginTranslation imported 'en:123456789012345678'
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] language: BCP 47 language tag of the translations, e.g. `en`, `de` or `fr-CH`
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[_builtins.str] translations: Translations as a JSON object with at least one key, for example built with `jsonencode`. The keys follow the structure of the [hosted login locale files](https://github.com/zitadel/zitadel/tree/main/apps/login/locales), e.g. `loginname.title`. Replaces all translations previously set for this language on the organization.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: HostedLoginTranslationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Organization-level translations for the **hosted login v2** (`/ui/v2/login`) in one language, using the settings/v2 API. **Requires ZITADEL 4.x.** ZITADEL checks the instance-level `iam.policy.read` and `iam.policy.write` permissions for these translations, so the service account needs an instance role such as `IAM_OWNER`; `ORG_OWNER` is not sufficient. Keys that are not set fall back to the instance-level translations and then to the built-in translations of the hosted login. ZITADEL has no API to remove translations, so destroying this resource only removes it from the Terraform state and leaves the last applied translations in place. Instance-level defaults are managed by `DefaultHostedLoginTranslation`. The legacy login UI (v1) is customized with `LoginTexts`.

        ## Example Usage

        ```python
        import pulumi
        import json
        import scoretechnologies_zitadel as zitadel

        default = zitadel.HostedLoginTranslation("default",
            org_id=default_zitadel_org["id"],
            language="en",
            translations=json.dumps({
                "loginname": {
                    "title": "Welcome to ACME",
                    "description": "Sign in with your ACME account.",
                },
            }))
        ```

        ## Import

        The resource can be imported using the ID format `<language[:org_id]>`, e.g.

        ```sh
        $ pulumi import zitadel:index/hostedLoginTranslation:HostedLoginTranslation imported 'en:123456789012345678'
        ```


        :param str resource_name: The name of the resource.
        :param HostedLoginTranslationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(HostedLoginTranslationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 language: pulumi.Input[Optional[_builtins.str]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 translations: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = HostedLoginTranslationArgs.__new__(HostedLoginTranslationArgs)

            if language is None and not opts.urn:
                raise TypeError("Missing required property 'language'")
            __props__.__dict__["language"] = language
            __props__.__dict__["org_id"] = org_id
            if translations is None and not opts.urn:
                raise TypeError("Missing required property 'translations'")
            __props__.__dict__["translations"] = translations
        super(HostedLoginTranslation, __self__).__init__(
            'zitadel:index/hostedLoginTranslation:HostedLoginTranslation',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            language: pulumi.Input[Optional[_builtins.str]] = None,
            org_id: pulumi.Input[Optional[_builtins.str]] = None,
            translations: pulumi.Input[Optional[_builtins.str]] = None) -> 'HostedLoginTranslation':
        """
        Get an existing HostedLoginTranslation resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] language: BCP 47 language tag of the translations, e.g. `en`, `de` or `fr-CH`
        :param pulumi.Input[_builtins.str] org_id: ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        :param pulumi.Input[_builtins.str] translations: Translations as a JSON object with at least one key, for example built with `jsonencode`. The keys follow the structure of the [hosted login locale files](https://github.com/zitadel/zitadel/tree/main/apps/login/locales), e.g. `loginname.title`. Replaces all translations previously set for this language on the organization.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _HostedLoginTranslationState.__new__(_HostedLoginTranslationState)

        __props__.__dict__["language"] = language
        __props__.__dict__["org_id"] = org_id
        __props__.__dict__["translations"] = translations
        return HostedLoginTranslation(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def language(self) -> pulumi.Output[_builtins.str]:
        """
        BCP 47 language tag of the translations, e.g. `en`, `de` or `fr-CH`
        """
        return pulumi.get(self, "language")

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the organization. If not provided, the organization of the authenticated user/service account is used.
        """
        return pulumi.get(self, "org_id")

    @_builtins.property
    @pulumi.getter
    def translations(self) -> pulumi.Output[_builtins.str]:
        """
        Translations as a JSON object with at least one key, for example built with `jsonencode`. The keys follow the structure of the [hosted login locale files](https://github.com/zitadel/zitadel/tree/main/apps/login/locales), e.g. `loginname.title`. Replaces all translations previously set for this language on the organization.
        """
        return pulumi.get(self, "translations")

