# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SmsProviderHttpArgs', 'SmsProviderHttp']

@pulumi.input_type
class SmsProviderHttpArgs:
    def __init__(__self__, *,
                 endpoint: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expiration_signing_key: pulumi.Input[Optional[_builtins.str]] = None,
                 set_active: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a SmsProviderHttp resource.

        :param pulumi.Input[_builtins.str] endpoint: Http endpoint which is used to send the SMS.
        :param pulumi.Input[_builtins.str] description: Description of the SMS provider.
        :param pulumi.Input[_builtins.str] expiration_signing_key: Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
        :param pulumi.Input[_builtins.bool] set_active: Set the SMS provider as active after creating/updating.
        """
        pulumi.set(__self__, "endpoint", endpoint)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expiration_signing_key is not None:
            pulumi.set(__self__, "expiration_signing_key", expiration_signing_key)
        if set_active is not None:
            pulumi.set(__self__, "set_active", set_active)

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Input[_builtins.str]:
        """
        Http endpoint which is used to send the SMS.
        """
        return pulumi.get(self, "endpoint")

    @endpoint.setter
    def endpoint(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "endpoint", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Description of the SMS provider.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="expirationSigningKey")
    def expiration_signing_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
        """
        return pulumi.get(self, "expiration_signing_key")

    @expiration_signing_key.setter
    def expiration_signing_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expiration_signing_key", value)

    @_builtins.property
    @pulumi.getter(name="setActive")
    def set_active(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Set the SMS provider as active after creating/updating.
        """
        return pulumi.get(self, "set_active")

    @set_active.setter
    def set_active(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "set_active", value)


@pulumi.input_type
class _SmsProviderHttpState:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 expiration_signing_key: pulumi.Input[Optional[_builtins.str]] = None,
                 set_active: pulumi.Input[Optional[_builtins.bool]] = None,
                 signing_key: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SmsProviderHttp resources.

        :param pulumi.Input[_builtins.str] description: Description of the SMS provider.
        :param pulumi.Input[_builtins.str] endpoint: Http endpoint which is used to send the SMS.
        :param pulumi.Input[_builtins.str] expiration_signing_key: Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
        :param pulumi.Input[_builtins.bool] set_active: Set the SMS provider as active after creating/updating.
        :param pulumi.Input[_builtins.str] signing_key: Key used to sign and check payload sent to the HTTP provider
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if endpoint is not None:
            pulumi.set(__self__, "endpoint", endpoint)
        if expiration_signing_key is not None:
            pulumi.set(__self__, "expiration_signing_key", expiration_signing_key)
        if set_active is not None:
            pulumi.set(__self__, "set_active", set_active)
        if signing_key is not None:
            pulumi.set(__self__, "signing_key", signing_key)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Description of the SMS provider.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Http endpoint which is used to send the SMS.
        """
        return pulumi.get(self, "endpoint")

    @endpoint.setter
    def endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "endpoint", value)

    @_builtins.property
    @pulumi.getter(name="expirationSigningKey")
    def expiration_signing_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
        """
        return pulumi.get(self, "expiration_signing_key")

    @expiration_signing_key.setter
    def expiration_signing_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expiration_signing_key", value)

    @_builtins.property
    @pulumi.getter(name="setActive")
    def set_active(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Set the SMS provider as active after creating/updating.
        """
        return pulumi.get(self, "set_active")

    @set_active.setter
    def set_active(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "set_active", value)

    @_builtins.property
    @pulumi.getter(name="signingKey")
    def signing_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Key used to sign and check payload sent to the HTTP provider
        """
        return pulumi.get(self, "signing_key")

    @signing_key.setter
    def signing_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "signing_key", value)


@pulumi.type_token("zitadel:index/smsProviderHttp:SmsProviderHttp")
class SmsProviderHttp(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 expiration_signing_key: pulumi.Input[Optional[_builtins.str]] = None,
                 set_active: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Resource representing the HTTP SMS provider configuration of an instance.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.SmsProviderHttp("default",
            endpoint="https://relay.example.com/provider",
            description="provider description",
            set_active=False)
        ```

        ## Import

        The resource can be imported using the ID format `<id>`, e.g.

        ```sh
        $ pulumi import zitadel:index/smsProviderHttp:SmsProviderHttp imported '123456789012345678'
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the SMS provider.
        :param pulumi.Input[_builtins.str] endpoint: Http endpoint which is used to send the SMS.
        :param pulumi.Input[_builtins.str] expiration_signing_key: Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
        :param pulumi.Input[_builtins.bool] set_active: Set the SMS provider as active after creating/updating.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SmsProviderHttpArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Resource representing the HTTP SMS provider configuration of an instance.

        ## Example Usage

        ```python
        import pulumi
        import scoretechnologies_zitadel as zitadel

        default = zitadel.SmsProviderHttp("default",
            endpoint="https://relay.example.com/provider",
            description="provider description",
            set_active=False)
        ```

        ## Import

        The resource can be imported using the ID format `<id>`, e.g.

        ```sh
        $ pulumi import zitadel:index/smsProviderHttp:SmsProviderHttp imported '123456789012345678'
        ```


        :param str resource_name: The name of the resource.
        :param SmsProviderHttpArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SmsProviderHttpArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 expiration_signing_key: pulumi.Input[Optional[_builtins.str]] = None,
                 set_active: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SmsProviderHttpArgs.__new__(SmsProviderHttpArgs)

            __props__.__dict__["description"] = description
            if endpoint is None and not opts.urn:
                raise TypeError("Missing required property 'endpoint'")
            __props__.__dict__["endpoint"] = endpoint
            __props__.__dict__["expiration_signing_key"] = expiration_signing_key
            __props__.__dict__["set_active"] = set_active
            __props__.__dict__["signing_key"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["signingKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(SmsProviderHttp, __self__).__init__(
            'zitadel:index/smsProviderHttp:SmsProviderHttp',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            endpoint: pulumi.Input[Optional[_builtins.str]] = None,
            expiration_signing_key: pulumi.Input[Optional[_builtins.str]] = None,
            set_active: pulumi.Input[Optional[_builtins.bool]] = None,
            signing_key: pulumi.Input[Optional[_builtins.str]] = None) -> 'SmsProviderHttp':
        """
        Get an existing SmsProviderHttp resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the SMS provider.
        :param pulumi.Input[_builtins.str] endpoint: Http endpoint which is used to send the SMS.
        :param pulumi.Input[_builtins.str] expiration_signing_key: Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
        :param pulumi.Input[_builtins.bool] set_active: Set the SMS provider as active after creating/updating.
        :param pulumi.Input[_builtins.str] signing_key: Key used to sign and check payload sent to the HTTP provider
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SmsProviderHttpState.__new__(_SmsProviderHttpState)

        __props__.__dict__["description"] = description
        __props__.__dict__["endpoint"] = endpoint
        __props__.__dict__["expiration_signing_key"] = expiration_signing_key
        __props__.__dict__["set_active"] = set_active
        __props__.__dict__["signing_key"] = signing_key
        return SmsProviderHttp(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the SMS provider.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Output[_builtins.str]:
        """
        Http endpoint which is used to send the SMS.
        """
        return pulumi.get(self, "endpoint")

    @_builtins.property
    @pulumi.getter(name="expirationSigningKey")
    def expiration_signing_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
        """
        return pulumi.get(self, "expiration_signing_key")

    @_builtins.property
    @pulumi.getter(name="setActive")
    def set_active(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Set the SMS provider as active after creating/updating.
        """
        return pulumi.get(self, "set_active")

    @_builtins.property
    @pulumi.getter(name="signingKey")
    def signing_key(self) -> pulumi.Output[_builtins.str]:
        """
        Key used to sign and check payload sent to the HTTP provider
        """
        return pulumi.get(self, "signing_key")

