// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing a target, which can be used in executions.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewActionTarget(ctx, "default", &zitadel.ActionTargetArgs{
//				Name:             pulumi.String("test-target-name"),
//				Endpoint:         pulumi.String("https://example.com/target"),
//				TargetType:       pulumi.String("REST_WEBHOOK"),
//				Timeout:          pulumi.String("15s"),
//				InterruptOnError: pulumi.Bool(false),
//				PayloadType:      pulumi.String("PAYLOAD_TYPE_JSON"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<id>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/actionTarget:ActionTarget imported '123456789012345678'
// ```
type ActionTarget struct {
	pulumi.CustomResourceState

	// The endpoint of the target.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	ExpirationSigningKey pulumi.StringPtrOutput `pulumi:"expirationSigningKey"`
	// Define if any error stops the whole execution. Note: this is not used for REST_ASYNC target type.
	InterruptOnError pulumi.BoolOutput `pulumi:"interruptOnError"`
	// The name of the target.
	Name pulumi.StringOutput `pulumi:"name"`
	// The payload type of the target, supported values: PAYLOAD*TYPE*UNSPECIFIED, PAYLOAD*TYPE*JSON, PAYLOAD*TYPE*JWT, PAYLOAD*TYPE*JWE
	PayloadType pulumi.StringOutput `pulumi:"payloadType"`
	// The signing key generated by ZITADEL when the target was created.
	SigningKey pulumi.StringOutput `pulumi:"signingKey"`
	// The type of the target. (REST*WEBHOOK, REST*CALL, REST_ASYNC)
	TargetType pulumi.StringOutput `pulumi:"targetType"`
	// Timeout defines the duration until ZITADEL cancels the execution.
	Timeout pulumi.StringOutput `pulumi:"timeout"`
}

// NewActionTarget registers a new resource with the given unique name, arguments, and options.
func NewActionTarget(ctx *pulumi.Context,
	name string, args *ActionTargetArgs, opts ...pulumi.ResourceOption) (*ActionTarget, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Endpoint == nil {
		return nil, errors.New("invalid value for required argument 'Endpoint'")
	}
	if args.InterruptOnError == nil {
		return nil, errors.New("invalid value for required argument 'InterruptOnError'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.TargetType == nil {
		return nil, errors.New("invalid value for required argument 'TargetType'")
	}
	if args.Timeout == nil {
		return nil, errors.New("invalid value for required argument 'Timeout'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"signingKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ActionTarget
	err := ctx.RegisterResource("zitadel:index/actionTarget:ActionTarget", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetActionTarget gets an existing ActionTarget resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetActionTarget(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ActionTargetState, opts ...pulumi.ResourceOption) (*ActionTarget, error) {
	var resource ActionTarget
	err := ctx.ReadResource("zitadel:index/actionTarget:ActionTarget", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ActionTarget resources.
type actionTargetState struct {
	// The endpoint of the target.
	Endpoint *string `pulumi:"endpoint"`
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	ExpirationSigningKey *string `pulumi:"expirationSigningKey"`
	// Define if any error stops the whole execution. Note: this is not used for REST_ASYNC target type.
	InterruptOnError *bool `pulumi:"interruptOnError"`
	// The name of the target.
	Name *string `pulumi:"name"`
	// The payload type of the target, supported values: PAYLOAD*TYPE*UNSPECIFIED, PAYLOAD*TYPE*JSON, PAYLOAD*TYPE*JWT, PAYLOAD*TYPE*JWE
	PayloadType *string `pulumi:"payloadType"`
	// The signing key generated by ZITADEL when the target was created.
	SigningKey *string `pulumi:"signingKey"`
	// The type of the target. (REST*WEBHOOK, REST*CALL, REST_ASYNC)
	TargetType *string `pulumi:"targetType"`
	// Timeout defines the duration until ZITADEL cancels the execution.
	Timeout *string `pulumi:"timeout"`
}

type ActionTargetState struct {
	// The endpoint of the target.
	Endpoint pulumi.StringPtrInput
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	ExpirationSigningKey pulumi.StringPtrInput
	// Define if any error stops the whole execution. Note: this is not used for REST_ASYNC target type.
	InterruptOnError pulumi.BoolPtrInput
	// The name of the target.
	Name pulumi.StringPtrInput
	// The payload type of the target, supported values: PAYLOAD*TYPE*UNSPECIFIED, PAYLOAD*TYPE*JSON, PAYLOAD*TYPE*JWT, PAYLOAD*TYPE*JWE
	PayloadType pulumi.StringPtrInput
	// The signing key generated by ZITADEL when the target was created.
	SigningKey pulumi.StringPtrInput
	// The type of the target. (REST*WEBHOOK, REST*CALL, REST_ASYNC)
	TargetType pulumi.StringPtrInput
	// Timeout defines the duration until ZITADEL cancels the execution.
	Timeout pulumi.StringPtrInput
}

func (ActionTargetState) ElementType() reflect.Type {
	return reflect.TypeOf((*actionTargetState)(nil)).Elem()
}

type actionTargetArgs struct {
	// The endpoint of the target.
	Endpoint string `pulumi:"endpoint"`
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	ExpirationSigningKey *string `pulumi:"expirationSigningKey"`
	// Define if any error stops the whole execution. Note: this is not used for REST_ASYNC target type.
	InterruptOnError bool `pulumi:"interruptOnError"`
	// The name of the target.
	Name string `pulumi:"name"`
	// The payload type of the target, supported values: PAYLOAD*TYPE*UNSPECIFIED, PAYLOAD*TYPE*JSON, PAYLOAD*TYPE*JWT, PAYLOAD*TYPE*JWE
	PayloadType *string `pulumi:"payloadType"`
	// The type of the target. (REST*WEBHOOK, REST*CALL, REST_ASYNC)
	TargetType string `pulumi:"targetType"`
	// Timeout defines the duration until ZITADEL cancels the execution.
	Timeout string `pulumi:"timeout"`
}

// The set of arguments for constructing a ActionTarget resource.
type ActionTargetArgs struct {
	// The endpoint of the target.
	Endpoint pulumi.StringInput
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	ExpirationSigningKey pulumi.StringPtrInput
	// Define if any error stops the whole execution. Note: this is not used for REST_ASYNC target type.
	InterruptOnError pulumi.BoolInput
	// The name of the target.
	Name pulumi.StringInput
	// The payload type of the target, supported values: PAYLOAD*TYPE*UNSPECIFIED, PAYLOAD*TYPE*JSON, PAYLOAD*TYPE*JWT, PAYLOAD*TYPE*JWE
	PayloadType pulumi.StringPtrInput
	// The type of the target. (REST*WEBHOOK, REST*CALL, REST_ASYNC)
	TargetType pulumi.StringInput
	// Timeout defines the duration until ZITADEL cancels the execution.
	Timeout pulumi.StringInput
}

func (ActionTargetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*actionTargetArgs)(nil)).Elem()
}

type ActionTargetInput interface {
	pulumi.Input

	ToActionTargetOutput() ActionTargetOutput
	ToActionTargetOutputWithContext(ctx context.Context) ActionTargetOutput
}

func (*ActionTarget) ElementType() reflect.Type {
	return reflect.TypeOf((**ActionTarget)(nil)).Elem()
}

func (i *ActionTarget) ToActionTargetOutput() ActionTargetOutput {
	return i.ToActionTargetOutputWithContext(context.Background())
}

func (i *ActionTarget) ToActionTargetOutputWithContext(ctx context.Context) ActionTargetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActionTargetOutput)
}

// ActionTargetArrayInput is an input type that accepts ActionTargetArray and ActionTargetArrayOutput values.
// You can construct a concrete instance of `ActionTargetArrayInput` via:
//
//	ActionTargetArray{ ActionTargetArgs{...} }
type ActionTargetArrayInput interface {
	pulumi.Input

	ToActionTargetArrayOutput() ActionTargetArrayOutput
	ToActionTargetArrayOutputWithContext(context.Context) ActionTargetArrayOutput
}

type ActionTargetArray []ActionTargetInput

func (ActionTargetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ActionTarget)(nil)).Elem()
}

func (i ActionTargetArray) ToActionTargetArrayOutput() ActionTargetArrayOutput {
	return i.ToActionTargetArrayOutputWithContext(context.Background())
}

func (i ActionTargetArray) ToActionTargetArrayOutputWithContext(ctx context.Context) ActionTargetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActionTargetArrayOutput)
}

// ActionTargetMapInput is an input type that accepts ActionTargetMap and ActionTargetMapOutput values.
// You can construct a concrete instance of `ActionTargetMapInput` via:
//
//	ActionTargetMap{ "key": ActionTargetArgs{...} }
type ActionTargetMapInput interface {
	pulumi.Input

	ToActionTargetMapOutput() ActionTargetMapOutput
	ToActionTargetMapOutputWithContext(context.Context) ActionTargetMapOutput
}

type ActionTargetMap map[string]ActionTargetInput

func (ActionTargetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ActionTarget)(nil)).Elem()
}

func (i ActionTargetMap) ToActionTargetMapOutput() ActionTargetMapOutput {
	return i.ToActionTargetMapOutputWithContext(context.Background())
}

func (i ActionTargetMap) ToActionTargetMapOutputWithContext(ctx context.Context) ActionTargetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActionTargetMapOutput)
}

type ActionTargetOutput struct{ *pulumi.OutputState }

func (ActionTargetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ActionTarget)(nil)).Elem()
}

func (o ActionTargetOutput) ToActionTargetOutput() ActionTargetOutput {
	return o
}

func (o ActionTargetOutput) ToActionTargetOutputWithContext(ctx context.Context) ActionTargetOutput {
	return o
}

// The endpoint of the target.
func (o ActionTargetOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
func (o ActionTargetOutput) ExpirationSigningKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.StringPtrOutput { return v.ExpirationSigningKey }).(pulumi.StringPtrOutput)
}

// Define if any error stops the whole execution. Note: this is not used for REST_ASYNC target type.
func (o ActionTargetOutput) InterruptOnError() pulumi.BoolOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.BoolOutput { return v.InterruptOnError }).(pulumi.BoolOutput)
}

// The name of the target.
func (o ActionTargetOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The payload type of the target, supported values: PAYLOAD*TYPE*UNSPECIFIED, PAYLOAD*TYPE*JSON, PAYLOAD*TYPE*JWT, PAYLOAD*TYPE*JWE
func (o ActionTargetOutput) PayloadType() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.StringOutput { return v.PayloadType }).(pulumi.StringOutput)
}

// The signing key generated by ZITADEL when the target was created.
func (o ActionTargetOutput) SigningKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.StringOutput { return v.SigningKey }).(pulumi.StringOutput)
}

// The type of the target. (REST*WEBHOOK, REST*CALL, REST_ASYNC)
func (o ActionTargetOutput) TargetType() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.StringOutput { return v.TargetType }).(pulumi.StringOutput)
}

// Timeout defines the duration until ZITADEL cancels the execution.
func (o ActionTargetOutput) Timeout() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTarget) pulumi.StringOutput { return v.Timeout }).(pulumi.StringOutput)
}

type ActionTargetArrayOutput struct{ *pulumi.OutputState }

func (ActionTargetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ActionTarget)(nil)).Elem()
}

func (o ActionTargetArrayOutput) ToActionTargetArrayOutput() ActionTargetArrayOutput {
	return o
}

func (o ActionTargetArrayOutput) ToActionTargetArrayOutputWithContext(ctx context.Context) ActionTargetArrayOutput {
	return o
}

func (o ActionTargetArrayOutput) Index(i pulumi.IntInput) ActionTargetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ActionTarget {
		return vs[0].([]*ActionTarget)[vs[1].(int)]
	}).(ActionTargetOutput)
}

type ActionTargetMapOutput struct{ *pulumi.OutputState }

func (ActionTargetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ActionTarget)(nil)).Elem()
}

func (o ActionTargetMapOutput) ToActionTargetMapOutput() ActionTargetMapOutput {
	return o
}

func (o ActionTargetMapOutput) ToActionTargetMapOutputWithContext(ctx context.Context) ActionTargetMapOutput {
	return o
}

func (o ActionTargetMapOutput) MapIndex(k pulumi.StringInput) ActionTargetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ActionTarget {
		return vs[0].(map[string]*ActionTarget)[vs[1].(string)]
	}).(ActionTargetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ActionTargetInput)(nil)).Elem(), &ActionTarget{})
	pulumi.RegisterInputType(reflect.TypeOf((*ActionTargetArrayInput)(nil)).Elem(), ActionTargetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ActionTargetMapInput)(nil)).Elem(), ActionTargetMap{})
	pulumi.RegisterOutputType(ActionTargetOutput{})
	pulumi.RegisterOutputType(ActionTargetArrayOutput{})
	pulumi.RegisterOutputType(ActionTargetMapOutput{})
}
