// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing an application belonging to a project. Exposes the unified Zitadel Application v2 API; the application type is selected by populating exactly one of the oidc/saml/api configuration blocks.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewApplicationV2(ctx, "default", &zitadel.ApplicationV2Args{
//				ProjectId: pulumi.Any(defaultZitadelProject.Id),
//				OrgId:     pulumi.Any(defaultZitadelOrg.Id),
//				Name:      pulumi.String("applicationv2"),
//				Oidc: &zitadel.ApplicationV2OidcArgs{
//					RedirectUris: pulumi.StringArray{
//						pulumi.String("https://localhost.com"),
//					},
//					ResponseTypes: pulumi.StringArray{
//						pulumi.String("OIDC_RESPONSE_TYPE_CODE"),
//					},
//					GrantTypes: pulumi.StringArray{
//						pulumi.String("OIDC_GRANT_TYPE_AUTHORIZATION_CODE"),
//					},
//					PostLogoutRedirectUris: pulumi.StringArray{
//						pulumi.String("https://localhost.com"),
//					},
//					AppType:                  pulumi.String("OIDC_APP_TYPE_WEB"),
//					AuthMethodType:           pulumi.String("OIDC_AUTH_METHOD_TYPE_BASIC"),
//					Version:                  pulumi.String("OIDC_VERSION_1_0"),
//					ClockSkew:                pulumi.String("0s"),
//					DevMode:                  pulumi.Bool(true),
//					AccessTokenType:          pulumi.String("OIDC_TOKEN_TYPE_BEARER"),
//					AccessTokenRoleAssertion: pulumi.Bool(false),
//					IdTokenRoleAssertion:     pulumi.Bool(false),
//					IdTokenUserinfoAssertion: pulumi.Bool(false),
//					AdditionalOrigins:        pulumi.StringArray{},
//					SkipNativeAppSuccessPage: pulumi.Bool(false),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<id[:org_id[:client_secret]]>`, e.g.
// projectId is refreshed from the v2 API on the first read and does not need to
// be passed at import time.
//
// ```sh
// $ pulumi import zitadel:index/applicationV2:ApplicationV2 imported '123456789012345678:123456789012345678'
// ```
//
// For OIDC/API applications with a generated client secret, pass the secret as
// the optional final segment so it is preserved in state (it is never returned
// by the read API). See the "Migrating to the v2 resources" guide for details.
//
// ```sh
// $ pulumi import zitadel:index/applicationV2:ApplicationV2 imported '123456789012345678:123456789012345678:THE_CLIENT_SECRET'
// ```
type ApplicationV2 struct {
	pulumi.CustomResourceState

	// API configuration. Mutually exclusive with `oidc` and `saml`.
	Api ApplicationV2ApiPtrOutput `pulumi:"api"`
	// Name of the application.
	Name pulumi.StringOutput `pulumi:"name"`
	// OIDC configuration. Mutually exclusive with `saml` and `api`.
	Oidc ApplicationV2OidcPtrOutput `pulumi:"oidc"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
	// ID of the project this application belongs to.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// SAML configuration. Mutually exclusive with `oidc` and `api`.
	Saml ApplicationV2SamlPtrOutput `pulumi:"saml"`
	// State of the application.
	State pulumi.StringOutput `pulumi:"state"`
}

// NewApplicationV2 registers a new resource with the given unique name, arguments, and options.
func NewApplicationV2(ctx *pulumi.Context,
	name string, args *ApplicationV2Args, opts ...pulumi.ResourceOption) (*ApplicationV2, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApplicationV2
	err := ctx.RegisterResource("zitadel:index/applicationV2:ApplicationV2", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApplicationV2 gets an existing ApplicationV2 resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApplicationV2(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApplicationV2State, opts ...pulumi.ResourceOption) (*ApplicationV2, error) {
	var resource ApplicationV2
	err := ctx.ReadResource("zitadel:index/applicationV2:ApplicationV2", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApplicationV2 resources.
type applicationV2State struct {
	// API configuration. Mutually exclusive with `oidc` and `saml`.
	Api *ApplicationV2Api `pulumi:"api"`
	// Name of the application.
	Name *string `pulumi:"name"`
	// OIDC configuration. Mutually exclusive with `saml` and `api`.
	Oidc *ApplicationV2Oidc `pulumi:"oidc"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
	// ID of the project this application belongs to.
	ProjectId *string `pulumi:"projectId"`
	// SAML configuration. Mutually exclusive with `oidc` and `api`.
	Saml *ApplicationV2Saml `pulumi:"saml"`
	// State of the application.
	State *string `pulumi:"state"`
}

type ApplicationV2State struct {
	// API configuration. Mutually exclusive with `oidc` and `saml`.
	Api ApplicationV2ApiPtrInput
	// Name of the application.
	Name pulumi.StringPtrInput
	// OIDC configuration. Mutually exclusive with `saml` and `api`.
	Oidc ApplicationV2OidcPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
	// ID of the project this application belongs to.
	ProjectId pulumi.StringPtrInput
	// SAML configuration. Mutually exclusive with `oidc` and `api`.
	Saml ApplicationV2SamlPtrInput
	// State of the application.
	State pulumi.StringPtrInput
}

func (ApplicationV2State) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationV2State)(nil)).Elem()
}

type applicationV2Args struct {
	// API configuration. Mutually exclusive with `oidc` and `saml`.
	Api *ApplicationV2Api `pulumi:"api"`
	// Name of the application.
	Name string `pulumi:"name"`
	// OIDC configuration. Mutually exclusive with `saml` and `api`.
	Oidc *ApplicationV2Oidc `pulumi:"oidc"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
	// ID of the project this application belongs to.
	ProjectId string `pulumi:"projectId"`
	// SAML configuration. Mutually exclusive with `oidc` and `api`.
	Saml *ApplicationV2Saml `pulumi:"saml"`
}

// The set of arguments for constructing a ApplicationV2 resource.
type ApplicationV2Args struct {
	// API configuration. Mutually exclusive with `oidc` and `saml`.
	Api ApplicationV2ApiPtrInput
	// Name of the application.
	Name pulumi.StringInput
	// OIDC configuration. Mutually exclusive with `saml` and `api`.
	Oidc ApplicationV2OidcPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
	// ID of the project this application belongs to.
	ProjectId pulumi.StringInput
	// SAML configuration. Mutually exclusive with `oidc` and `api`.
	Saml ApplicationV2SamlPtrInput
}

func (ApplicationV2Args) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationV2Args)(nil)).Elem()
}

type ApplicationV2Input interface {
	pulumi.Input

	ToApplicationV2Output() ApplicationV2Output
	ToApplicationV2OutputWithContext(ctx context.Context) ApplicationV2Output
}

func (*ApplicationV2) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationV2)(nil)).Elem()
}

func (i *ApplicationV2) ToApplicationV2Output() ApplicationV2Output {
	return i.ToApplicationV2OutputWithContext(context.Background())
}

func (i *ApplicationV2) ToApplicationV2OutputWithContext(ctx context.Context) ApplicationV2Output {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationV2Output)
}

// ApplicationV2ArrayInput is an input type that accepts ApplicationV2Array and ApplicationV2ArrayOutput values.
// You can construct a concrete instance of `ApplicationV2ArrayInput` via:
//
//	ApplicationV2Array{ ApplicationV2Args{...} }
type ApplicationV2ArrayInput interface {
	pulumi.Input

	ToApplicationV2ArrayOutput() ApplicationV2ArrayOutput
	ToApplicationV2ArrayOutputWithContext(context.Context) ApplicationV2ArrayOutput
}

type ApplicationV2Array []ApplicationV2Input

func (ApplicationV2Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationV2)(nil)).Elem()
}

func (i ApplicationV2Array) ToApplicationV2ArrayOutput() ApplicationV2ArrayOutput {
	return i.ToApplicationV2ArrayOutputWithContext(context.Background())
}

func (i ApplicationV2Array) ToApplicationV2ArrayOutputWithContext(ctx context.Context) ApplicationV2ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationV2ArrayOutput)
}

// ApplicationV2MapInput is an input type that accepts ApplicationV2Map and ApplicationV2MapOutput values.
// You can construct a concrete instance of `ApplicationV2MapInput` via:
//
//	ApplicationV2Map{ "key": ApplicationV2Args{...} }
type ApplicationV2MapInput interface {
	pulumi.Input

	ToApplicationV2MapOutput() ApplicationV2MapOutput
	ToApplicationV2MapOutputWithContext(context.Context) ApplicationV2MapOutput
}

type ApplicationV2Map map[string]ApplicationV2Input

func (ApplicationV2Map) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationV2)(nil)).Elem()
}

func (i ApplicationV2Map) ToApplicationV2MapOutput() ApplicationV2MapOutput {
	return i.ToApplicationV2MapOutputWithContext(context.Background())
}

func (i ApplicationV2Map) ToApplicationV2MapOutputWithContext(ctx context.Context) ApplicationV2MapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationV2MapOutput)
}

type ApplicationV2Output struct{ *pulumi.OutputState }

func (ApplicationV2Output) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationV2)(nil)).Elem()
}

func (o ApplicationV2Output) ToApplicationV2Output() ApplicationV2Output {
	return o
}

func (o ApplicationV2Output) ToApplicationV2OutputWithContext(ctx context.Context) ApplicationV2Output {
	return o
}

// API configuration. Mutually exclusive with `oidc` and `saml`.
func (o ApplicationV2Output) Api() ApplicationV2ApiPtrOutput {
	return o.ApplyT(func(v *ApplicationV2) ApplicationV2ApiPtrOutput { return v.Api }).(ApplicationV2ApiPtrOutput)
}

// Name of the application.
func (o ApplicationV2Output) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationV2) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// OIDC configuration. Mutually exclusive with `saml` and `api`.
func (o ApplicationV2Output) Oidc() ApplicationV2OidcPtrOutput {
	return o.ApplyT(func(v *ApplicationV2) ApplicationV2OidcPtrOutput { return v.Oidc }).(ApplicationV2OidcPtrOutput)
}

// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
func (o ApplicationV2Output) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApplicationV2) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

// ID of the project this application belongs to.
func (o ApplicationV2Output) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationV2) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// SAML configuration. Mutually exclusive with `oidc` and `api`.
func (o ApplicationV2Output) Saml() ApplicationV2SamlPtrOutput {
	return o.ApplyT(func(v *ApplicationV2) ApplicationV2SamlPtrOutput { return v.Saml }).(ApplicationV2SamlPtrOutput)
}

// State of the application.
func (o ApplicationV2Output) State() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationV2) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

type ApplicationV2ArrayOutput struct{ *pulumi.OutputState }

func (ApplicationV2ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationV2)(nil)).Elem()
}

func (o ApplicationV2ArrayOutput) ToApplicationV2ArrayOutput() ApplicationV2ArrayOutput {
	return o
}

func (o ApplicationV2ArrayOutput) ToApplicationV2ArrayOutputWithContext(ctx context.Context) ApplicationV2ArrayOutput {
	return o
}

func (o ApplicationV2ArrayOutput) Index(i pulumi.IntInput) ApplicationV2Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ApplicationV2 {
		return vs[0].([]*ApplicationV2)[vs[1].(int)]
	}).(ApplicationV2Output)
}

type ApplicationV2MapOutput struct{ *pulumi.OutputState }

func (ApplicationV2MapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationV2)(nil)).Elem()
}

func (o ApplicationV2MapOutput) ToApplicationV2MapOutput() ApplicationV2MapOutput {
	return o
}

func (o ApplicationV2MapOutput) ToApplicationV2MapOutputWithContext(ctx context.Context) ApplicationV2MapOutput {
	return o
}

func (o ApplicationV2MapOutput) MapIndex(k pulumi.StringInput) ApplicationV2Output {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ApplicationV2 {
		return vs[0].(map[string]*ApplicationV2)[vs[1].(string)]
	}).(ApplicationV2Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationV2Input)(nil)).Elem(), &ApplicationV2{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationV2ArrayInput)(nil)).Elem(), ApplicationV2Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationV2MapInput)(nil)).Elem(), ApplicationV2Map{})
	pulumi.RegisterOutputType(ApplicationV2Output{})
	pulumi.RegisterOutputType(ApplicationV2ArrayOutput{})
	pulumi.RegisterOutputType(ApplicationV2MapOutput{})
}
