// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Instance-level default template for the OTP verification SMS. Org-level overrides are managed by `VerifySmsOtpMessageText`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultVerifySmsOtpMessageText(ctx, "default", &zitadel.DefaultVerifySmsOtpMessageTextArgs{
//				Language: pulumi.String("en"),
//				Text:     pulumi.String("text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultVerifySmsOtpMessageText struct {
	pulumi.CustomResourceState

	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Greeting pulumi.StringPtrOutput `pulumi:"greeting"`
	Language pulumi.StringOutput    `pulumi:"language"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	PreHeader pulumi.StringPtrOutput `pulumi:"preHeader"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Subject pulumi.StringPtrOutput `pulumi:"subject"`
	Text    pulumi.StringPtrOutput `pulumi:"text"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Title pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultVerifySmsOtpMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultVerifySmsOtpMessageText(ctx *pulumi.Context,
	name string, args *DefaultVerifySmsOtpMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultVerifySmsOtpMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultVerifySmsOtpMessageText
	err := ctx.RegisterResource("zitadel:index/defaultVerifySmsOtpMessageText:DefaultVerifySmsOtpMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultVerifySmsOtpMessageText gets an existing DefaultVerifySmsOtpMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultVerifySmsOtpMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultVerifySmsOtpMessageTextState, opts ...pulumi.ResourceOption) (*DefaultVerifySmsOtpMessageText, error) {
	var resource DefaultVerifySmsOtpMessageText
	err := ctx.ReadResource("zitadel:index/defaultVerifySmsOtpMessageText:DefaultVerifySmsOtpMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultVerifySmsOtpMessageText resources.
type defaultVerifySmsOtpMessageTextState struct {
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	ButtonText *string `pulumi:"buttonText"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	FooterText *string `pulumi:"footerText"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Greeting *string `pulumi:"greeting"`
	Language *string `pulumi:"language"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	PreHeader *string `pulumi:"preHeader"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Subject *string `pulumi:"subject"`
	Text    *string `pulumi:"text"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Title *string `pulumi:"title"`
}

type DefaultVerifySmsOtpMessageTextState struct {
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	ButtonText pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	FooterText pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Greeting pulumi.StringPtrInput
	Language pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	PreHeader pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Subject pulumi.StringPtrInput
	Text    pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Title pulumi.StringPtrInput
}

func (DefaultVerifySmsOtpMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifySmsOtpMessageTextState)(nil)).Elem()
}

type defaultVerifySmsOtpMessageTextArgs struct {
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	ButtonText *string `pulumi:"buttonText"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	FooterText *string `pulumi:"footerText"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Greeting *string `pulumi:"greeting"`
	Language string  `pulumi:"language"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	PreHeader *string `pulumi:"preHeader"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Subject *string `pulumi:"subject"`
	Text    *string `pulumi:"text"`
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Title *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultVerifySmsOtpMessageText resource.
type DefaultVerifySmsOtpMessageTextArgs struct {
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	ButtonText pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	FooterText pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Greeting pulumi.StringPtrInput
	Language pulumi.StringInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	PreHeader pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Subject pulumi.StringPtrInput
	Text    pulumi.StringPtrInput
	// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
	Title pulumi.StringPtrInput
}

func (DefaultVerifySmsOtpMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifySmsOtpMessageTextArgs)(nil)).Elem()
}

type DefaultVerifySmsOtpMessageTextInput interface {
	pulumi.Input

	ToDefaultVerifySmsOtpMessageTextOutput() DefaultVerifySmsOtpMessageTextOutput
	ToDefaultVerifySmsOtpMessageTextOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextOutput
}

func (*DefaultVerifySmsOtpMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (i *DefaultVerifySmsOtpMessageText) ToDefaultVerifySmsOtpMessageTextOutput() DefaultVerifySmsOtpMessageTextOutput {
	return i.ToDefaultVerifySmsOtpMessageTextOutputWithContext(context.Background())
}

func (i *DefaultVerifySmsOtpMessageText) ToDefaultVerifySmsOtpMessageTextOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultVerifySmsOtpMessageTextOutput)
}

// DefaultVerifySmsOtpMessageTextArrayInput is an input type that accepts DefaultVerifySmsOtpMessageTextArray and DefaultVerifySmsOtpMessageTextArrayOutput values.
// You can construct a concrete instance of `DefaultVerifySmsOtpMessageTextArrayInput` via:
//
//	DefaultVerifySmsOtpMessageTextArray{ DefaultVerifySmsOtpMessageTextArgs{...} }
type DefaultVerifySmsOtpMessageTextArrayInput interface {
	pulumi.Input

	ToDefaultVerifySmsOtpMessageTextArrayOutput() DefaultVerifySmsOtpMessageTextArrayOutput
	ToDefaultVerifySmsOtpMessageTextArrayOutputWithContext(context.Context) DefaultVerifySmsOtpMessageTextArrayOutput
}

type DefaultVerifySmsOtpMessageTextArray []DefaultVerifySmsOtpMessageTextInput

func (DefaultVerifySmsOtpMessageTextArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (i DefaultVerifySmsOtpMessageTextArray) ToDefaultVerifySmsOtpMessageTextArrayOutput() DefaultVerifySmsOtpMessageTextArrayOutput {
	return i.ToDefaultVerifySmsOtpMessageTextArrayOutputWithContext(context.Background())
}

func (i DefaultVerifySmsOtpMessageTextArray) ToDefaultVerifySmsOtpMessageTextArrayOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultVerifySmsOtpMessageTextArrayOutput)
}

// DefaultVerifySmsOtpMessageTextMapInput is an input type that accepts DefaultVerifySmsOtpMessageTextMap and DefaultVerifySmsOtpMessageTextMapOutput values.
// You can construct a concrete instance of `DefaultVerifySmsOtpMessageTextMapInput` via:
//
//	DefaultVerifySmsOtpMessageTextMap{ "key": DefaultVerifySmsOtpMessageTextArgs{...} }
type DefaultVerifySmsOtpMessageTextMapInput interface {
	pulumi.Input

	ToDefaultVerifySmsOtpMessageTextMapOutput() DefaultVerifySmsOtpMessageTextMapOutput
	ToDefaultVerifySmsOtpMessageTextMapOutputWithContext(context.Context) DefaultVerifySmsOtpMessageTextMapOutput
}

type DefaultVerifySmsOtpMessageTextMap map[string]DefaultVerifySmsOtpMessageTextInput

func (DefaultVerifySmsOtpMessageTextMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (i DefaultVerifySmsOtpMessageTextMap) ToDefaultVerifySmsOtpMessageTextMapOutput() DefaultVerifySmsOtpMessageTextMapOutput {
	return i.ToDefaultVerifySmsOtpMessageTextMapOutputWithContext(context.Background())
}

func (i DefaultVerifySmsOtpMessageTextMap) ToDefaultVerifySmsOtpMessageTextMapOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultVerifySmsOtpMessageTextMapOutput)
}

type DefaultVerifySmsOtpMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultVerifySmsOtpMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (o DefaultVerifySmsOtpMessageTextOutput) ToDefaultVerifySmsOtpMessageTextOutput() DefaultVerifySmsOtpMessageTextOutput {
	return o
}

func (o DefaultVerifySmsOtpMessageTextOutput) ToDefaultVerifySmsOtpMessageTextOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextOutput {
	return o
}

// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
func (o DefaultVerifySmsOtpMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
func (o DefaultVerifySmsOtpMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
func (o DefaultVerifySmsOtpMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
func (o DefaultVerifySmsOtpMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
func (o DefaultVerifySmsOtpMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

// Deprecated: Not supported by the SMS OTP message: the ZITADEL API only stores `text` for this message type, so this attribute has no effect. It will be removed in a future major version.
func (o DefaultVerifySmsOtpMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

type DefaultVerifySmsOtpMessageTextArrayOutput struct{ *pulumi.OutputState }

func (DefaultVerifySmsOtpMessageTextArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (o DefaultVerifySmsOtpMessageTextArrayOutput) ToDefaultVerifySmsOtpMessageTextArrayOutput() DefaultVerifySmsOtpMessageTextArrayOutput {
	return o
}

func (o DefaultVerifySmsOtpMessageTextArrayOutput) ToDefaultVerifySmsOtpMessageTextArrayOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextArrayOutput {
	return o
}

func (o DefaultVerifySmsOtpMessageTextArrayOutput) Index(i pulumi.IntInput) DefaultVerifySmsOtpMessageTextOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DefaultVerifySmsOtpMessageText {
		return vs[0].([]*DefaultVerifySmsOtpMessageText)[vs[1].(int)]
	}).(DefaultVerifySmsOtpMessageTextOutput)
}

type DefaultVerifySmsOtpMessageTextMapOutput struct{ *pulumi.OutputState }

func (DefaultVerifySmsOtpMessageTextMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (o DefaultVerifySmsOtpMessageTextMapOutput) ToDefaultVerifySmsOtpMessageTextMapOutput() DefaultVerifySmsOtpMessageTextMapOutput {
	return o
}

func (o DefaultVerifySmsOtpMessageTextMapOutput) ToDefaultVerifySmsOtpMessageTextMapOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextMapOutput {
	return o
}

func (o DefaultVerifySmsOtpMessageTextMapOutput) MapIndex(k pulumi.StringInput) DefaultVerifySmsOtpMessageTextOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DefaultVerifySmsOtpMessageText {
		return vs[0].(map[string]*DefaultVerifySmsOtpMessageText)[vs[1].(string)]
	}).(DefaultVerifySmsOtpMessageTextOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultVerifySmsOtpMessageTextInput)(nil)).Elem(), &DefaultVerifySmsOtpMessageText{})
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultVerifySmsOtpMessageTextArrayInput)(nil)).Elem(), DefaultVerifySmsOtpMessageTextArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultVerifySmsOtpMessageTextMapInput)(nil)).Elem(), DefaultVerifySmsOtpMessageTextMap{})
	pulumi.RegisterOutputType(DefaultVerifySmsOtpMessageTextOutput{})
	pulumi.RegisterOutputType(DefaultVerifySmsOtpMessageTextArrayOutput{})
	pulumi.RegisterOutputType(DefaultVerifySmsOtpMessageTextMapOutput{})
}
