// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing a generic OIDC IDP on the instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/scoretechnologies/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewIdpOidc(ctx, "default", &zitadel.IdpOidcArgs{
//				AutoLinking:       pulumi.String("AUTO_LINKING_OPTION_USERNAME"),
//				ClientId:          pulumi.String("a_client_id"),
//				ClientSecret:      pulumi.String("a_client_secret"),
//				IsAutoCreation:    pulumi.Bool(false),
//				IsAutoUpdate:      pulumi.Bool(true),
//				IsCreationAllowed: pulumi.Bool(true),
//				IsIdTokenMapping:  pulumi.Bool(true),
//				IsLinkingAllowed:  pulumi.Bool(false),
//				Issuer:            pulumi.String("https://example.com"),
//				Scopes: pulumi.StringArray{
//					pulumi.String("openid"),
//					pulumi.String("profile"),
//					pulumi.String("email"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// bash The resource can be imported using the ID format `<id[:client_secret]>`, e.g.
//
// ```sh
//
//	$ pulumi import zitadel:index/idpOidc:IdpOidc imported '123456789012345678:1234567890abcdef'
//
// ```
type IdpOidc struct {
	pulumi.CustomResourceState

	// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
	AutoLinking pulumi.StringPtrOutput `pulumi:"autoLinking"`
	// client id generated by the identity provider
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// client secret generated by the identity provider
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// enable if a new account in ZITADEL should be created automatically on login with an external account
	IsAutoCreation pulumi.BoolOutput `pulumi:"isAutoCreation"`
	// enable if a the ZITADEL account fields should be updated automatically on each login
	IsAutoUpdate pulumi.BoolOutput `pulumi:"isAutoUpdate"`
	// enable if users should be able to create a new account in ZITADEL when using an external account
	IsCreationAllowed pulumi.BoolOutput `pulumi:"isCreationAllowed"`
	// if true, provider information get mapped from the id token, not from the userinfo endpoint
	IsIdTokenMapping pulumi.BoolOutput `pulumi:"isIdTokenMapping"`
	// enable if users should be able to link an existing ZITADEL user with an external account
	IsLinkingAllowed pulumi.BoolOutput `pulumi:"isLinkingAllowed"`
	// the issuer of the idp
	Issuer pulumi.StringOutput `pulumi:"issuer"`
	// Name of the IDP
	Name pulumi.StringOutput `pulumi:"name"`
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes pulumi.StringArrayOutput `pulumi:"scopes"`
}

// NewIdpOidc registers a new resource with the given unique name, arguments, and options.
func NewIdpOidc(ctx *pulumi.Context,
	name string, args *IdpOidcArgs, opts ...pulumi.ResourceOption) (*IdpOidc, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.IsAutoCreation == nil {
		return nil, errors.New("invalid value for required argument 'IsAutoCreation'")
	}
	if args.IsAutoUpdate == nil {
		return nil, errors.New("invalid value for required argument 'IsAutoUpdate'")
	}
	if args.IsCreationAllowed == nil {
		return nil, errors.New("invalid value for required argument 'IsCreationAllowed'")
	}
	if args.IsIdTokenMapping == nil {
		return nil, errors.New("invalid value for required argument 'IsIdTokenMapping'")
	}
	if args.IsLinkingAllowed == nil {
		return nil, errors.New("invalid value for required argument 'IsLinkingAllowed'")
	}
	if args.Issuer == nil {
		return nil, errors.New("invalid value for required argument 'Issuer'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource IdpOidc
	err := ctx.RegisterResource("zitadel:index/idpOidc:IdpOidc", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIdpOidc gets an existing IdpOidc resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIdpOidc(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IdpOidcState, opts ...pulumi.ResourceOption) (*IdpOidc, error) {
	var resource IdpOidc
	err := ctx.ReadResource("zitadel:index/idpOidc:IdpOidc", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IdpOidc resources.
type idpOidcState struct {
	// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
	AutoLinking *string `pulumi:"autoLinking"`
	// client id generated by the identity provider
	ClientId *string `pulumi:"clientId"`
	// client secret generated by the identity provider
	ClientSecret *string `pulumi:"clientSecret"`
	// enable if a new account in ZITADEL should be created automatically on login with an external account
	IsAutoCreation *bool `pulumi:"isAutoCreation"`
	// enable if a the ZITADEL account fields should be updated automatically on each login
	IsAutoUpdate *bool `pulumi:"isAutoUpdate"`
	// enable if users should be able to create a new account in ZITADEL when using an external account
	IsCreationAllowed *bool `pulumi:"isCreationAllowed"`
	// if true, provider information get mapped from the id token, not from the userinfo endpoint
	IsIdTokenMapping *bool `pulumi:"isIdTokenMapping"`
	// enable if users should be able to link an existing ZITADEL user with an external account
	IsLinkingAllowed *bool `pulumi:"isLinkingAllowed"`
	// the issuer of the idp
	Issuer *string `pulumi:"issuer"`
	// Name of the IDP
	Name *string `pulumi:"name"`
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes []string `pulumi:"scopes"`
}

type IdpOidcState struct {
	// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
	AutoLinking pulumi.StringPtrInput
	// client id generated by the identity provider
	ClientId pulumi.StringPtrInput
	// client secret generated by the identity provider
	ClientSecret pulumi.StringPtrInput
	// enable if a new account in ZITADEL should be created automatically on login with an external account
	IsAutoCreation pulumi.BoolPtrInput
	// enable if a the ZITADEL account fields should be updated automatically on each login
	IsAutoUpdate pulumi.BoolPtrInput
	// enable if users should be able to create a new account in ZITADEL when using an external account
	IsCreationAllowed pulumi.BoolPtrInput
	// if true, provider information get mapped from the id token, not from the userinfo endpoint
	IsIdTokenMapping pulumi.BoolPtrInput
	// enable if users should be able to link an existing ZITADEL user with an external account
	IsLinkingAllowed pulumi.BoolPtrInput
	// the issuer of the idp
	Issuer pulumi.StringPtrInput
	// Name of the IDP
	Name pulumi.StringPtrInput
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes pulumi.StringArrayInput
}

func (IdpOidcState) ElementType() reflect.Type {
	return reflect.TypeOf((*idpOidcState)(nil)).Elem()
}

type idpOidcArgs struct {
	// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
	AutoLinking *string `pulumi:"autoLinking"`
	// client id generated by the identity provider
	ClientId string `pulumi:"clientId"`
	// client secret generated by the identity provider
	ClientSecret string `pulumi:"clientSecret"`
	// enable if a new account in ZITADEL should be created automatically on login with an external account
	IsAutoCreation bool `pulumi:"isAutoCreation"`
	// enable if a the ZITADEL account fields should be updated automatically on each login
	IsAutoUpdate bool `pulumi:"isAutoUpdate"`
	// enable if users should be able to create a new account in ZITADEL when using an external account
	IsCreationAllowed bool `pulumi:"isCreationAllowed"`
	// if true, provider information get mapped from the id token, not from the userinfo endpoint
	IsIdTokenMapping bool `pulumi:"isIdTokenMapping"`
	// enable if users should be able to link an existing ZITADEL user with an external account
	IsLinkingAllowed bool `pulumi:"isLinkingAllowed"`
	// the issuer of the idp
	Issuer string `pulumi:"issuer"`
	// Name of the IDP
	Name *string `pulumi:"name"`
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes []string `pulumi:"scopes"`
}

// The set of arguments for constructing a IdpOidc resource.
type IdpOidcArgs struct {
	// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
	AutoLinking pulumi.StringPtrInput
	// client id generated by the identity provider
	ClientId pulumi.StringInput
	// client secret generated by the identity provider
	ClientSecret pulumi.StringInput
	// enable if a new account in ZITADEL should be created automatically on login with an external account
	IsAutoCreation pulumi.BoolInput
	// enable if a the ZITADEL account fields should be updated automatically on each login
	IsAutoUpdate pulumi.BoolInput
	// enable if users should be able to create a new account in ZITADEL when using an external account
	IsCreationAllowed pulumi.BoolInput
	// if true, provider information get mapped from the id token, not from the userinfo endpoint
	IsIdTokenMapping pulumi.BoolInput
	// enable if users should be able to link an existing ZITADEL user with an external account
	IsLinkingAllowed pulumi.BoolInput
	// the issuer of the idp
	Issuer pulumi.StringInput
	// Name of the IDP
	Name pulumi.StringPtrInput
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes pulumi.StringArrayInput
}

func (IdpOidcArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*idpOidcArgs)(nil)).Elem()
}

type IdpOidcInput interface {
	pulumi.Input

	ToIdpOidcOutput() IdpOidcOutput
	ToIdpOidcOutputWithContext(ctx context.Context) IdpOidcOutput
}

func (*IdpOidc) ElementType() reflect.Type {
	return reflect.TypeOf((**IdpOidc)(nil)).Elem()
}

func (i *IdpOidc) ToIdpOidcOutput() IdpOidcOutput {
	return i.ToIdpOidcOutputWithContext(context.Background())
}

func (i *IdpOidc) ToIdpOidcOutputWithContext(ctx context.Context) IdpOidcOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IdpOidcOutput)
}

func (i *IdpOidc) ToOutput(ctx context.Context) pulumix.Output[*IdpOidc] {
	return pulumix.Output[*IdpOidc]{
		OutputState: i.ToIdpOidcOutputWithContext(ctx).OutputState,
	}
}

// IdpOidcArrayInput is an input type that accepts IdpOidcArray and IdpOidcArrayOutput values.
// You can construct a concrete instance of `IdpOidcArrayInput` via:
//
//	IdpOidcArray{ IdpOidcArgs{...} }
type IdpOidcArrayInput interface {
	pulumi.Input

	ToIdpOidcArrayOutput() IdpOidcArrayOutput
	ToIdpOidcArrayOutputWithContext(context.Context) IdpOidcArrayOutput
}

type IdpOidcArray []IdpOidcInput

func (IdpOidcArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IdpOidc)(nil)).Elem()
}

func (i IdpOidcArray) ToIdpOidcArrayOutput() IdpOidcArrayOutput {
	return i.ToIdpOidcArrayOutputWithContext(context.Background())
}

func (i IdpOidcArray) ToIdpOidcArrayOutputWithContext(ctx context.Context) IdpOidcArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IdpOidcArrayOutput)
}

func (i IdpOidcArray) ToOutput(ctx context.Context) pulumix.Output[[]*IdpOidc] {
	return pulumix.Output[[]*IdpOidc]{
		OutputState: i.ToIdpOidcArrayOutputWithContext(ctx).OutputState,
	}
}

// IdpOidcMapInput is an input type that accepts IdpOidcMap and IdpOidcMapOutput values.
// You can construct a concrete instance of `IdpOidcMapInput` via:
//
//	IdpOidcMap{ "key": IdpOidcArgs{...} }
type IdpOidcMapInput interface {
	pulumi.Input

	ToIdpOidcMapOutput() IdpOidcMapOutput
	ToIdpOidcMapOutputWithContext(context.Context) IdpOidcMapOutput
}

type IdpOidcMap map[string]IdpOidcInput

func (IdpOidcMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IdpOidc)(nil)).Elem()
}

func (i IdpOidcMap) ToIdpOidcMapOutput() IdpOidcMapOutput {
	return i.ToIdpOidcMapOutputWithContext(context.Background())
}

func (i IdpOidcMap) ToIdpOidcMapOutputWithContext(ctx context.Context) IdpOidcMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IdpOidcMapOutput)
}

func (i IdpOidcMap) ToOutput(ctx context.Context) pulumix.Output[map[string]*IdpOidc] {
	return pulumix.Output[map[string]*IdpOidc]{
		OutputState: i.ToIdpOidcMapOutputWithContext(ctx).OutputState,
	}
}

type IdpOidcOutput struct{ *pulumi.OutputState }

func (IdpOidcOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IdpOidc)(nil)).Elem()
}

func (o IdpOidcOutput) ToIdpOidcOutput() IdpOidcOutput {
	return o
}

func (o IdpOidcOutput) ToIdpOidcOutputWithContext(ctx context.Context) IdpOidcOutput {
	return o
}

func (o IdpOidcOutput) ToOutput(ctx context.Context) pulumix.Output[*IdpOidc] {
	return pulumix.Output[*IdpOidc]{
		OutputState: o.OutputState,
	}
}

// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
func (o IdpOidcOutput) AutoLinking() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.StringPtrOutput { return v.AutoLinking }).(pulumi.StringPtrOutput)
}

// client id generated by the identity provider
func (o IdpOidcOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// client secret generated by the identity provider
func (o IdpOidcOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// enable if a new account in ZITADEL should be created automatically on login with an external account
func (o IdpOidcOutput) IsAutoCreation() pulumi.BoolOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.BoolOutput { return v.IsAutoCreation }).(pulumi.BoolOutput)
}

// enable if a the ZITADEL account fields should be updated automatically on each login
func (o IdpOidcOutput) IsAutoUpdate() pulumi.BoolOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.BoolOutput { return v.IsAutoUpdate }).(pulumi.BoolOutput)
}

// enable if users should be able to create a new account in ZITADEL when using an external account
func (o IdpOidcOutput) IsCreationAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.BoolOutput { return v.IsCreationAllowed }).(pulumi.BoolOutput)
}

// if true, provider information get mapped from the id token, not from the userinfo endpoint
func (o IdpOidcOutput) IsIdTokenMapping() pulumi.BoolOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.BoolOutput { return v.IsIdTokenMapping }).(pulumi.BoolOutput)
}

// enable if users should be able to link an existing ZITADEL user with an external account
func (o IdpOidcOutput) IsLinkingAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.BoolOutput { return v.IsLinkingAllowed }).(pulumi.BoolOutput)
}

// the issuer of the idp
func (o IdpOidcOutput) Issuer() pulumi.StringOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.StringOutput { return v.Issuer }).(pulumi.StringOutput)
}

// Name of the IDP
func (o IdpOidcOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// the scopes requested by ZITADEL during the request on the identity provider
func (o IdpOidcOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *IdpOidc) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

type IdpOidcArrayOutput struct{ *pulumi.OutputState }

func (IdpOidcArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IdpOidc)(nil)).Elem()
}

func (o IdpOidcArrayOutput) ToIdpOidcArrayOutput() IdpOidcArrayOutput {
	return o
}

func (o IdpOidcArrayOutput) ToIdpOidcArrayOutputWithContext(ctx context.Context) IdpOidcArrayOutput {
	return o
}

func (o IdpOidcArrayOutput) ToOutput(ctx context.Context) pulumix.Output[[]*IdpOidc] {
	return pulumix.Output[[]*IdpOidc]{
		OutputState: o.OutputState,
	}
}

func (o IdpOidcArrayOutput) Index(i pulumi.IntInput) IdpOidcOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IdpOidc {
		return vs[0].([]*IdpOidc)[vs[1].(int)]
	}).(IdpOidcOutput)
}

type IdpOidcMapOutput struct{ *pulumi.OutputState }

func (IdpOidcMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IdpOidc)(nil)).Elem()
}

func (o IdpOidcMapOutput) ToIdpOidcMapOutput() IdpOidcMapOutput {
	return o
}

func (o IdpOidcMapOutput) ToIdpOidcMapOutputWithContext(ctx context.Context) IdpOidcMapOutput {
	return o
}

func (o IdpOidcMapOutput) ToOutput(ctx context.Context) pulumix.Output[map[string]*IdpOidc] {
	return pulumix.Output[map[string]*IdpOidc]{
		OutputState: o.OutputState,
	}
}

func (o IdpOidcMapOutput) MapIndex(k pulumi.StringInput) IdpOidcOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IdpOidc {
		return vs[0].(map[string]*IdpOidc)[vs[1].(string)]
	}).(IdpOidcOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IdpOidcInput)(nil)).Elem(), &IdpOidc{})
	pulumi.RegisterInputType(reflect.TypeOf((*IdpOidcArrayInput)(nil)).Elem(), IdpOidcArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IdpOidcMapInput)(nil)).Elem(), IdpOidcMap{})
	pulumi.RegisterOutputType(IdpOidcOutput{})
	pulumi.RegisterOutputType(IdpOidcArrayOutput{})
	pulumi.RegisterOutputType(IdpOidcMapOutput{})
}
