// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ApplicationOidcComplianceProblem {
    /**
     * Machine-readable identifier for the compliance problem
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * Human-readable localized message
     */
    message?: pulumi.Input<string | undefined>;
}

export interface ApplicationOidcLoginVersion {
    /**
     * Login V1
     */
    loginV1?: pulumi.Input<boolean | undefined>;
    /**
     * Login V2
     */
    loginV2?: pulumi.Input<inputs.ApplicationOidcLoginVersionLoginV2 | undefined>;
}

export interface ApplicationOidcLoginVersionLoginV2 {
    /**
     * Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
     */
    baseUri?: pulumi.Input<string | undefined>;
}

export interface ApplicationSamlLoginVersion {
    /**
     * Login V1
     */
    loginV1?: pulumi.Input<boolean | undefined>;
    /**
     * Login V2
     */
    loginV2?: pulumi.Input<inputs.ApplicationSamlLoginVersionLoginV2 | undefined>;
}

export interface ApplicationSamlLoginVersionLoginV2 {
    /**
     * Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
     */
    baseUri?: pulumi.Input<string | undefined>;
}

export interface ApplicationV2Api {
    /**
     * API auth method type, supported values: API*AUTH*METHOD*TYPE*BASIC, API*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
     */
    authMethodType?: pulumi.Input<string | undefined>;
    /**
     * Generated client ID.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * Generated client secret (only returned on create).
     */
    clientSecret?: pulumi.Input<string | undefined>;
}

export interface ApplicationV2Oidc {
    accessTokenRoleAssertion?: pulumi.Input<boolean | undefined>;
    /**
     * Access token type, supported values: OIDC*TOKEN*TYPE*BEARER, OIDC*TOKEN*TYPE*JWT
     */
    accessTokenType?: pulumi.Input<string | undefined>;
    /**
     * Additional allowed origins.
     */
    additionalOrigins?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Application type, supported values: OIDC*APP*TYPE*WEB, OIDC*APP*TYPE*USER*AGENT, OIDC*APP*TYPE*NATIVE
     */
    appType?: pulumi.Input<string | undefined>;
    /**
     * Auth method type, supported values: OIDC*AUTH*METHOD*TYPE*BASIC, OIDC*AUTH*METHOD*TYPE*POST, OIDC*AUTH*METHOD*TYPE*NONE, OIDC*AUTH*METHOD*TYPE*PRIVATE*KEY*JWT
     */
    authMethodType?: pulumi.Input<string | undefined>;
    /**
     * Back-channel logout URI used by ZITADEL to notify the application of terminated sessions (OIDC Back-Channel Logout). Computed if not set, so the server-side default flows back into state.
     */
    backChannelLogoutUri?: pulumi.Input<string | undefined>;
    /**
     * Generated client ID.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * Generated client secret (only set on create when the auth method requires one).
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * Allowed clock skew (Go duration string, e.g. `5s`).
     */
    clockSkew?: pulumi.Input<string | undefined>;
    /**
     * List of OIDC specification compliance problems detected by ZITADEL for this configuration. Empty when the configuration is compliant.
     */
    complianceProblems?: pulumi.Input<pulumi.Input<inputs.ApplicationV2OidcComplianceProblem>[] | undefined>;
    /**
     * Development mode (relaxes redirect-URI validation).
     */
    devMode?: pulumi.Input<boolean | undefined>;
    /**
     * Grant types, supported values: OIDC*GRANT*TYPE*AUTHORIZATION*CODE, OIDC*GRANT*TYPE*IMPLICIT, OIDC*GRANT*TYPE*REFRESH*TOKEN, OIDC*GRANT*TYPE*DEVICE*CODE, OIDC*GRANT*TYPE*TOKEN_EXCHANGE
     */
    grantTypes: pulumi.Input<pulumi.Input<string>[]>;
    idTokenRoleAssertion?: pulumi.Input<boolean | undefined>;
    idTokenUserinfoAssertion?: pulumi.Input<boolean | undefined>;
    /**
     * Login UI version to use for this application. Exactly one of `loginV1` and `loginV2` may be set. Computed so that the server-side default flows back into state when the user omits this block.
     */
    loginVersion?: pulumi.Input<inputs.ApplicationV2OidcLoginVersion | undefined>;
    /**
     * Whether the OIDC configuration violates the OIDC specification, as determined by ZITADEL. See `complianceProblems` for the individual findings.
     */
    noneCompliant?: pulumi.Input<boolean | undefined>;
    /**
     * Post-logout redirect URIs.
     */
    postLogoutRedirectUris?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Allowed redirect URIs. Required: OIDC clients cannot function without at least one redirect URI, and the Zitadel API rejects creation otherwise. Matches the v1 `zitadel.ApplicationOidc` requirement.
     */
    redirectUris: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Response types, supported values: OIDC*RESPONSE*TYPE*UNSPECIFIED, OIDC*RESPONSE*TYPE*CODE, OIDC*RESPONSE*TYPE*ID*TOKEN, OIDC*RESPONSE*TYPE*ID*TOKEN_TOKEN
     */
    responseTypes: pulumi.Input<pulumi.Input<string>[]>;
    skipNativeAppSuccessPage?: pulumi.Input<boolean | undefined>;
    /**
     * OIDC version, supported values: OIDC*VERSION*1_0
     */
    version?: pulumi.Input<string | undefined>;
}

export interface ApplicationV2OidcComplianceProblem {
    /**
     * Stable i18n key identifying the compliance problem.
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * Human-readable description of the compliance problem.
     */
    message?: pulumi.Input<string | undefined>;
}

export interface ApplicationV2OidcLoginVersion {
    /**
     * Use the legacy Login UI (V1).
     */
    loginV1?: pulumi.Input<boolean | undefined>;
    /**
     * Use the Login UI V2.
     */
    loginV2?: pulumi.Input<inputs.ApplicationV2OidcLoginVersionLoginV2 | undefined>;
}

export interface ApplicationV2OidcLoginVersionLoginV2 {
    /**
     * Optional base URI of a custom Login UI V2. If unset, the instance default is used.
     */
    baseUri?: pulumi.Input<string | undefined>;
}

export interface ApplicationV2Saml {
    /**
     * Login UI version to use for this application. Exactly one of `loginV1` and `loginV2` may be set. Computed so that the server-side default flows back into state when the user omits this block.
     */
    loginVersion?: pulumi.Input<inputs.ApplicationV2SamlLoginVersion | undefined>;
    /**
     * URL from which SAML metadata can be fetched. Mutually exclusive with `metadataXml`.
     */
    metadataUrl?: pulumi.Input<string | undefined>;
    /**
     * SAML metadata as raw XML. Mutually exclusive with `metadataUrl`. Marked sensitive because SAML metadata documents commonly embed signing/encryption certificates.
     */
    metadataXml?: pulumi.Input<string | undefined>;
}

export interface ApplicationV2SamlLoginVersion {
    /**
     * Use the legacy Login UI (V1).
     */
    loginV1?: pulumi.Input<boolean | undefined>;
    /**
     * Use the Login UI V2.
     */
    loginV2?: pulumi.Input<inputs.ApplicationV2SamlLoginVersionLoginV2 | undefined>;
}

export interface ApplicationV2SamlLoginVersionLoginV2 {
    /**
     * Optional base URI of a custom Login UI V2. If unset, the instance default is used.
     */
    baseUri?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsEmailVerificationDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    loginButtonText?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsEmailVerificationText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    resendButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsExternalRegistrationUserOverviewText {
    backButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    emailLabel?: pulumi.Input<string | undefined>;
    firstnameLabel?: pulumi.Input<string | undefined>;
    languageLabel?: pulumi.Input<string | undefined>;
    lastnameLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    nicknameLabel?: pulumi.Input<string | undefined>;
    phoneLabel?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsExternalUserNotFoundText {
    autoRegisterButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    linkButtonText?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsFooterText {
    help?: pulumi.Input<string | undefined>;
    privacyPolicy?: pulumi.Input<string | undefined>;
    supportEmail?: pulumi.Input<string | undefined>;
    tos?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitMfaDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitMfaOtpText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    descriptionOtp?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    secretLabel?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitMfaPromptText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    otpOption?: pulumi.Input<string | undefined>;
    skipButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    u2fOption?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitMfaU2fText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    registerTokenButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tokenNameLabel?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitPasswordDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitPasswordText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    newPasswordConfirmLabel?: pulumi.Input<string | undefined>;
    newPasswordLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    resendButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitializeDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsInitializeUserText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    newPasswordConfirmLabel?: pulumi.Input<string | undefined>;
    newPasswordLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    resendButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsLinkingUserDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsLinkingUserPromptText {
    description?: pulumi.Input<string | undefined>;
    linkButtonText?: pulumi.Input<string | undefined>;
    otherButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsLoginText {
    description?: pulumi.Input<string | undefined>;
    descriptionLinkingProcess?: pulumi.Input<string | undefined>;
    externalUserDescription?: pulumi.Input<string | undefined>;
    loginNameLabel?: pulumi.Input<string | undefined>;
    loginNamePlaceholder?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    registerButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    titleLinkingProcess?: pulumi.Input<string | undefined>;
    userMustBeMemberOfOrg?: pulumi.Input<string | undefined>;
    userNamePlaceholder?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsLogoutText {
    description?: pulumi.Input<string | undefined>;
    loginButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsMfaProvidersText {
    chooseOther?: pulumi.Input<string | undefined>;
    otp?: pulumi.Input<string | undefined>;
    u2f?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordChangeDoneText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordChangeText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    expiredDescription?: pulumi.Input<string | undefined>;
    newPasswordConfirmLabel?: pulumi.Input<string | undefined>;
    newPasswordLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    oldPasswordLabel?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordResetDoneText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordText {
    backButtonText?: pulumi.Input<string | undefined>;
    confirmation?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    hasLowercase?: pulumi.Input<string | undefined>;
    hasNumber?: pulumi.Input<string | undefined>;
    hasSymbol?: pulumi.Input<string | undefined>;
    hasUppercase?: pulumi.Input<string | undefined>;
    minLength?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    passwordLabel?: pulumi.Input<string | undefined>;
    resetLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordlessPromptText {
    description?: pulumi.Input<string | undefined>;
    descriptionInit?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    passwordlessButtonText?: pulumi.Input<string | undefined>;
    skipButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordlessRegistrationDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    descriptionClose?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordlessRegistrationText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    registerTokenButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tokenNameLabel?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsPasswordlessText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    loginWithPwButtonText?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    validateTokenButtonText?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsRegistrationOptionText {
    description?: pulumi.Input<string | undefined>;
    externalLoginDescription?: pulumi.Input<string | undefined>;
    loginButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    userNameButtonText?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsRegistrationOrgText {
    description?: pulumi.Input<string | undefined>;
    emailLabel?: pulumi.Input<string | undefined>;
    firstnameLabel?: pulumi.Input<string | undefined>;
    lastnameLabel?: pulumi.Input<string | undefined>;
    orgnameLabel?: pulumi.Input<string | undefined>;
    passwordConfirmLabel?: pulumi.Input<string | undefined>;
    passwordLabel?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    saveButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsRegistrationUserText {
    backButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    descriptionOrgRegister?: pulumi.Input<string | undefined>;
    emailLabel?: pulumi.Input<string | undefined>;
    firstnameLabel?: pulumi.Input<string | undefined>;
    genderLabel?: pulumi.Input<string | undefined>;
    languageLabel?: pulumi.Input<string | undefined>;
    lastnameLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    passwordConfirmLabel?: pulumi.Input<string | undefined>;
    passwordLabel?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsSelectAccountText {
    description?: pulumi.Input<string | undefined>;
    descriptionLinkingProcess?: pulumi.Input<string | undefined>;
    otherUser?: pulumi.Input<string | undefined>;
    sessionStateActive?: pulumi.Input<string | undefined>;
    sessionStateInactive?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    titleLinkingProcess?: pulumi.Input<string | undefined>;
    userMustBeMemberOfOrg?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsSuccessLoginText {
    /**
     * Text to describe that auto-redirect should happen after successful login
     */
    autoRedirectDescription?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    /**
     * Text to describe that the window can be closed after redirect
     */
    redirectedDescription?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsUsernameChangeDoneText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsUsernameChangeText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsVerifyMfaOtpText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface DefaultLoginTextsVerifyMfaU2fText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    validateTokenText?: pulumi.Input<string | undefined>;
}

export interface HumanUserIdpLink {
    /**
     * The ID of the identity provider.
     */
    idpId: pulumi.Input<string>;
    /**
     * The user ID at the identity provider.
     */
    userId: pulumi.Input<string>;
    /**
     * The username at the identity provider.
     */
    userName: pulumi.Input<string>;
}

export interface HumanUserMetadata {
    /**
     * The key of the metadata entry.
     */
    key: pulumi.Input<string>;
    /**
     * The value of the metadata entry.
     */
    value: pulumi.Input<string>;
}

export interface InstanceFeaturesLoginV2 {
    /**
     * Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
     */
    baseUri?: pulumi.Input<string | undefined>;
    /**
     * Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
     */
    required?: pulumi.Input<boolean | undefined>;
}

export interface LoginTextsEmailVerificationDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    loginButtonText?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsEmailVerificationText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    resendButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsExternalRegistrationUserOverviewText {
    backButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    emailLabel?: pulumi.Input<string | undefined>;
    firstnameLabel?: pulumi.Input<string | undefined>;
    languageLabel?: pulumi.Input<string | undefined>;
    lastnameLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    nicknameLabel?: pulumi.Input<string | undefined>;
    phoneLabel?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface LoginTextsExternalUserNotFoundText {
    autoRegisterButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    linkButtonText?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
}

export interface LoginTextsFooterText {
    help?: pulumi.Input<string | undefined>;
    privacyPolicy?: pulumi.Input<string | undefined>;
    supportEmail?: pulumi.Input<string | undefined>;
    tos?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitMfaDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitMfaOtpText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    descriptionOtp?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    secretLabel?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitMfaPromptText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    otpOption?: pulumi.Input<string | undefined>;
    skipButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    u2fOption?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitMfaU2fText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    registerTokenButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tokenNameLabel?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitPasswordDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitPasswordText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    newPasswordConfirmLabel?: pulumi.Input<string | undefined>;
    newPasswordLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    resendButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitializeDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsInitializeUserText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    newPasswordConfirmLabel?: pulumi.Input<string | undefined>;
    newPasswordLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    resendButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsLinkingUserDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsLinkingUserPromptText {
    description?: pulumi.Input<string | undefined>;
    linkButtonText?: pulumi.Input<string | undefined>;
    otherButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsLoginText {
    description?: pulumi.Input<string | undefined>;
    descriptionLinkingProcess?: pulumi.Input<string | undefined>;
    externalUserDescription?: pulumi.Input<string | undefined>;
    loginNameLabel?: pulumi.Input<string | undefined>;
    loginNamePlaceholder?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    registerButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    titleLinkingProcess?: pulumi.Input<string | undefined>;
    userMustBeMemberOfOrg?: pulumi.Input<string | undefined>;
    userNamePlaceholder?: pulumi.Input<string | undefined>;
}

export interface LoginTextsLogoutText {
    description?: pulumi.Input<string | undefined>;
    loginButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsMfaProvidersText {
    chooseOther?: pulumi.Input<string | undefined>;
    otp?: pulumi.Input<string | undefined>;
    u2f?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordChangeDoneText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordChangeText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    expiredDescription?: pulumi.Input<string | undefined>;
    newPasswordConfirmLabel?: pulumi.Input<string | undefined>;
    newPasswordLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    oldPasswordLabel?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordResetDoneText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordText {
    backButtonText?: pulumi.Input<string | undefined>;
    confirmation?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    hasLowercase?: pulumi.Input<string | undefined>;
    hasNumber?: pulumi.Input<string | undefined>;
    hasSymbol?: pulumi.Input<string | undefined>;
    hasUppercase?: pulumi.Input<string | undefined>;
    minLength?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    passwordLabel?: pulumi.Input<string | undefined>;
    resetLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordlessPromptText {
    description?: pulumi.Input<string | undefined>;
    descriptionInit?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    passwordlessButtonText?: pulumi.Input<string | undefined>;
    skipButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordlessRegistrationDoneText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    descriptionClose?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordlessRegistrationText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    registerTokenButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tokenNameLabel?: pulumi.Input<string | undefined>;
}

export interface LoginTextsPasswordlessText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    loginWithPwButtonText?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    validateTokenButtonText?: pulumi.Input<string | undefined>;
}

export interface LoginTextsRegistrationOptionText {
    description?: pulumi.Input<string | undefined>;
    externalLoginDescription?: pulumi.Input<string | undefined>;
    loginButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    userNameButtonText?: pulumi.Input<string | undefined>;
}

export interface LoginTextsRegistrationOrgText {
    description?: pulumi.Input<string | undefined>;
    emailLabel?: pulumi.Input<string | undefined>;
    firstnameLabel?: pulumi.Input<string | undefined>;
    lastnameLabel?: pulumi.Input<string | undefined>;
    orgnameLabel?: pulumi.Input<string | undefined>;
    passwordConfirmLabel?: pulumi.Input<string | undefined>;
    passwordLabel?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    saveButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface LoginTextsRegistrationUserText {
    backButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    descriptionOrgRegister?: pulumi.Input<string | undefined>;
    emailLabel?: pulumi.Input<string | undefined>;
    firstnameLabel?: pulumi.Input<string | undefined>;
    genderLabel?: pulumi.Input<string | undefined>;
    languageLabel?: pulumi.Input<string | undefined>;
    lastnameLabel?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    passwordConfirmLabel?: pulumi.Input<string | undefined>;
    passwordLabel?: pulumi.Input<string | undefined>;
    privacyConfirm?: pulumi.Input<string | undefined>;
    privacyLinkText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    tosAndPrivacyLabel?: pulumi.Input<string | undefined>;
    tosConfirm?: pulumi.Input<string | undefined>;
    tosLinkText?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface LoginTextsSelectAccountText {
    description?: pulumi.Input<string | undefined>;
    descriptionLinkingProcess?: pulumi.Input<string | undefined>;
    otherUser?: pulumi.Input<string | undefined>;
    sessionStateActive?: pulumi.Input<string | undefined>;
    sessionStateInactive?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    titleLinkingProcess?: pulumi.Input<string | undefined>;
    userMustBeMemberOfOrg?: pulumi.Input<string | undefined>;
}

export interface LoginTextsSuccessLoginText {
    /**
     * Text to describe that auto-redirect should happen after successful login
     */
    autoRedirectDescription?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    /**
     * Text to describe that the window can be closed after redirect
     */
    redirectedDescription?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsUsernameChangeDoneText {
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsUsernameChangeText {
    cancelButtonText?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    usernameLabel?: pulumi.Input<string | undefined>;
}

export interface LoginTextsVerifyMfaOtpText {
    codeLabel?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    nextButtonText?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
}

export interface LoginTextsVerifyMfaU2fText {
    description?: pulumi.Input<string | undefined>;
    errorRetry?: pulumi.Input<string | undefined>;
    notSupported?: pulumi.Input<string | undefined>;
    title?: pulumi.Input<string | undefined>;
    validateTokenText?: pulumi.Input<string | undefined>;
}

export interface OrgAdmin {
    /**
     * Roles to assign (defaults to ORG_OWNER if empty)
     */
    roles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * ID of existing user to grant admin access
     */
    userId: pulumi.Input<string>;
}

export interface OrganizationAdmin {
    /**
     * List of roles to grant to the user. If empty, ORG_OWNER is granted by default
     */
    roles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * ID of the user to be added as org admin
     */
    userId: pulumi.Input<string>;
}

export interface ProviderSystemApi {
    /**
     * Audience to set on the System API JWT. Defaults to the issuer derived from domain/port if omitted.
     */
    audience?: pulumi.Input<string | undefined>;
    /**
     * PEM encoded private key for a ZITADEL System API user. Either 'key_file'/'key' or the 'private_key'+'public_key' pair is required when using System API authentication.
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * Path to the PEM encoded private key for a ZITADEL System API user. Either 'key_file'/'key' or the 'private_key'+'public_key' pair is required when using System API authentication.
     */
    keyFile?: pulumi.Input<string | undefined>;
    /**
     * PEM encoded private key for a ZITADEL System API user when provided separately from the public key. Use together with 'public_key'.
     */
    privateKey?: pulumi.Input<string | undefined>;
    /**
     * PEM encoded public key for a ZITADEL System API user when provided separately from the private key. Use together with 'private_key'.
     */
    publicKey?: pulumi.Input<string | undefined>;
    /**
     * User ID configured for the System API key. Used as both issuer and subject in the self-signed JWT.
     */
    user: pulumi.Input<string>;
}

export interface SystemFeaturesLoginV2 {
    /**
     * Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
     */
    baseUri?: pulumi.Input<string | undefined>;
    /**
     * Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
     */
    required?: pulumi.Input<boolean | undefined>;
}

export interface WebkeyEcdsa {
    /**
     * Curve of the ECDSA key.
     */
    curve?: pulumi.Input<string | undefined>;
}

export interface WebkeyEd25519 {
}

export interface WebkeyRsa {
    /**
     * Bit size of the RSA key.
     */
    bits?: pulumi.Input<string | undefined>;
    /**
     * Signing algorithm used.
     */
    hasher?: pulumi.Input<string | undefined>;
}
export namespace config {
}
