// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Inputs
{

    public sealed class HumanUserMetadataGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key of the metadata entry.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The value of the metadata entry.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public HumanUserMetadataGetArgs()
        {
        }
        public static new HumanUserMetadataGetArgs Empty => new HumanUserMetadataGetArgs();
    }
}
