// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace scoretechnologies.Zitadel.Inputs
{

    public sealed class LoginTextsRegistrationUserTextGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("backButtonText")]
        public Input<string>? BackButtonText { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("descriptionOrgRegister")]
        public Input<string>? DescriptionOrgRegister { get; set; }

        [Input("emailLabel")]
        public Input<string>? EmailLabel { get; set; }

        [Input("firstnameLabel")]
        public Input<string>? FirstnameLabel { get; set; }

        [Input("genderLabel")]
        public Input<string>? GenderLabel { get; set; }

        [Input("languageLabel")]
        public Input<string>? LanguageLabel { get; set; }

        [Input("lastnameLabel")]
        public Input<string>? LastnameLabel { get; set; }

        [Input("nextButtonText")]
        public Input<string>? NextButtonText { get; set; }

        [Input("passwordConfirmLabel")]
        public Input<string>? PasswordConfirmLabel { get; set; }

        [Input("passwordLabel")]
        public Input<string>? PasswordLabel { get; set; }

        [Input("privacyConfirm")]
        public Input<string>? PrivacyConfirm { get; set; }

        [Input("privacyLinkText")]
        public Input<string>? PrivacyLinkText { get; set; }

        [Input("title")]
        public Input<string>? Title { get; set; }

        [Input("tosAndPrivacyLabel")]
        public Input<string>? TosAndPrivacyLabel { get; set; }

        [Input("tosConfirm")]
        public Input<string>? TosConfirm { get; set; }

        [Input("tosLinkText")]
        public Input<string>? TosLinkText { get; set; }

        [Input("usernameLabel")]
        public Input<string>? UsernameLabel { get; set; }

        public LoginTextsRegistrationUserTextGetArgs()
        {
        }
        public static new LoginTextsRegistrationUserTextGetArgs Empty => new LoginTextsRegistrationUserTextGetArgs();
    }
}
