// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource representing a public key for an action target, used for payload encryption.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as std from "@pulumi/std";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = new zitadel.ActionTargetPublicKey("default", {
 *     targetId: defaultZitadelActionTarget.id,
 *     publicKey: std.file({
 *         input: "path/to/public_key.pem",
 *     }).result,
 * });
 * ```
 *
 * ## Import
 *
 * The resource can be imported using the ID format `<key_id>:<target_id>`, e.g.
 *
 * ```sh
 * $ pulumi import zitadel:index/actionTargetPublicKey:ActionTargetPublicKey imported '123456789012345678:123456789012345678'
 * ```
 */
export class ActionTargetPublicKey extends pulumi.CustomResource {
    /**
     * Get an existing ActionTargetPublicKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ActionTargetPublicKeyState, opts?: pulumi.CustomResourceOptions): ActionTargetPublicKey {
        return new ActionTargetPublicKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zitadel:index/actionTargetPublicKey:ActionTargetPublicKey';

    /**
     * Returns true if the given object is an instance of ActionTargetPublicKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ActionTargetPublicKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ActionTargetPublicKey.__pulumiType;
    }

    /**
     * Whether the public key is active and used for payload encryption. If unset, the key is created in ZITADEL's default (inactive) state and the provider does not modify its activation state. Set to true to activate the key after creation, or to toggle activation on an existing key.
     */
    declare public readonly active: pulumi.Output<boolean>;
    /**
     * The date the public key was added.
     */
    declare public /*out*/ readonly creationDate: pulumi.Output<string>;
    /**
     * The expiration date of the public key in RFC3339 format.
     */
    declare public readonly expirationDate: pulumi.Output<string | undefined>;
    /**
     * The fingerprint of the public key.
     */
    declare public /*out*/ readonly fingerprint: pulumi.Output<string>;
    /**
     * The ID of the public key, used as 'kid' in the JWE header.
     */
    declare public /*out*/ readonly keyId: pulumi.Output<string>;
    /**
     * The public key in PEM format (RSA or EC).
     */
    declare public readonly publicKey: pulumi.Output<string>;
    /**
     * The ID of the action target to add the public key to.
     */
    declare public readonly targetId: pulumi.Output<string>;

    /**
     * Create a ActionTargetPublicKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ActionTargetPublicKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ActionTargetPublicKeyArgs | ActionTargetPublicKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ActionTargetPublicKeyState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["creationDate"] = state?.creationDate;
            resourceInputs["expirationDate"] = state?.expirationDate;
            resourceInputs["fingerprint"] = state?.fingerprint;
            resourceInputs["keyId"] = state?.keyId;
            resourceInputs["publicKey"] = state?.publicKey;
            resourceInputs["targetId"] = state?.targetId;
        } else {
            const args = argsOrState as ActionTargetPublicKeyArgs | undefined;
            if (args?.publicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'publicKey'");
            }
            if (args?.targetId === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetId'");
            }
            resourceInputs["active"] = args?.active;
            resourceInputs["expirationDate"] = args?.expirationDate;
            resourceInputs["publicKey"] = args?.publicKey;
            resourceInputs["targetId"] = args?.targetId;
            resourceInputs["creationDate"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["keyId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ActionTargetPublicKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ActionTargetPublicKey resources.
 */
export interface ActionTargetPublicKeyState {
    /**
     * Whether the public key is active and used for payload encryption. If unset, the key is created in ZITADEL's default (inactive) state and the provider does not modify its activation state. Set to true to activate the key after creation, or to toggle activation on an existing key.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * The date the public key was added.
     */
    creationDate?: pulumi.Input<string | undefined>;
    /**
     * The expiration date of the public key in RFC3339 format.
     */
    expirationDate?: pulumi.Input<string | undefined>;
    /**
     * The fingerprint of the public key.
     */
    fingerprint?: pulumi.Input<string | undefined>;
    /**
     * The ID of the public key, used as 'kid' in the JWE header.
     */
    keyId?: pulumi.Input<string | undefined>;
    /**
     * The public key in PEM format (RSA or EC).
     */
    publicKey?: pulumi.Input<string | undefined>;
    /**
     * The ID of the action target to add the public key to.
     */
    targetId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ActionTargetPublicKey resource.
 */
export interface ActionTargetPublicKeyArgs {
    /**
     * Whether the public key is active and used for payload encryption. If unset, the key is created in ZITADEL's default (inactive) state and the provider does not modify its activation state. Set to true to activate the key after creation, or to toggle activation on an existing key.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * The expiration date of the public key in RFC3339 format.
     */
    expirationDate?: pulumi.Input<string | undefined>;
    /**
     * The public key in PEM format (RSA or EC).
     */
    publicKey: pulumi.Input<string>;
    /**
     * The ID of the action target to add the public key to.
     */
    targetId: pulumi.Input<string>;
}
