// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Datasource representing an action execution triggered by a request.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = zitadel.getActionExecutionRequest({
 *     id: "method:/zitadel.session.v2.SessionService/ListSessions",
 * });
 * ```
 */
export function getActionExecutionRequest(args: GetActionExecutionRequestArgs, opts?: pulumi.InvokeOptions): Promise<GetActionExecutionRequestResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zitadel:index/getActionExecutionRequest:getActionExecutionRequest", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getActionExecutionRequest.
 */
export interface GetActionExecutionRequestArgs {
    /**
     * The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `all`/`all:`
     */
    id: string;
}

/**
 * A collection of values returned by getActionExecutionRequest.
 */
export interface GetActionExecutionRequestResult {
    /**
     * Trigger on all requests.
     */
    readonly all: boolean;
    /**
     * The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `all`/`all:`
     */
    readonly id: string;
    /**
     * The gRPC method to trigger on.
     */
    readonly method: string;
    /**
     * The gRPC service to trigger on.
     */
    readonly service: string;
    /**
     * The list of target IDs to call.
     */
    readonly targetIds: string[];
}
/**
 * Datasource representing an action execution triggered by a request.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = zitadel.getActionExecutionRequest({
 *     id: "method:/zitadel.session.v2.SessionService/ListSessions",
 * });
 * ```
 */
export function getActionExecutionRequestOutput(args: GetActionExecutionRequestOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetActionExecutionRequestResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zitadel:index/getActionExecutionRequest:getActionExecutionRequest", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getActionExecutionRequest.
 */
export interface GetActionExecutionRequestOutputArgs {
    /**
     * The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `all`/`all:`
     */
    id: pulumi.Input<string>;
}
