// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Datasource representing an Azure AD IdP of the organization.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = zitadel.getOrgIdpAzureAd({
 *     orgId: defaultZitadelOrg.id,
 *     id: "123456789012345678",
 * });
 * ```
 */
export function getOrgIdpAzureAd(args: GetOrgIdpAzureAdArgs, opts?: pulumi.InvokeOptions): Promise<GetOrgIdpAzureAdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zitadel:index/getOrgIdpAzureAd:getOrgIdpAzureAd", {
        "id": args.id,
        "orgId": args.orgId,
    }, opts);
}

/**
 * A collection of arguments for invoking getOrgIdpAzureAd.
 */
export interface GetOrgIdpAzureAdArgs {
    /**
     * The ID of this resource.
     */
    id: string;
    /**
     * ID of the organization
     */
    orgId?: string;
}

/**
 * A collection of values returned by getOrgIdpAzureAd.
 */
export interface GetOrgIdpAzureAdResult {
    /**
     * Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
     */
    readonly autoLinking: string;
    /**
     * client id generated by the identity provider
     */
    readonly clientId: string;
    /**
     * automatically mark emails as verified
     */
    readonly emailVerified: boolean;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * enabled if a new account in ZITADEL are created automatically on login with an external account
     */
    readonly isAutoCreation: boolean;
    /**
     * enabled if a the ZITADEL account fields are updated automatically on each login
     */
    readonly isAutoUpdate: boolean;
    /**
     * enabled if users are able to create a new account in ZITADEL when using an external account
     */
    readonly isCreationAllowed: boolean;
    /**
     * enabled if users are able to link an existing ZITADEL user with an external account
     */
    readonly isLinkingAllowed: boolean;
    /**
     * Name of the IDP
     */
    readonly name: string;
    /**
     * ID of the organization
     */
    readonly orgId?: string;
    /**
     * the scopes requested by ZITADEL during the request on the identity provider
     */
    readonly scopes: string[];
    /**
     * the azure ad tenant id
     */
    readonly tenantId: string;
    /**
     * the azure ad tenant type
     */
    readonly tenantType: string;
}
/**
 * Datasource representing an Azure AD IdP of the organization.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = zitadel.getOrgIdpAzureAd({
 *     orgId: defaultZitadelOrg.id,
 *     id: "123456789012345678",
 * });
 * ```
 */
export function getOrgIdpAzureAdOutput(args: GetOrgIdpAzureAdOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOrgIdpAzureAdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zitadel:index/getOrgIdpAzureAd:getOrgIdpAzureAd", {
        "id": args.id,
        "orgId": args.orgId,
    }, opts);
}

/**
 * A collection of arguments for invoking getOrgIdpAzureAd.
 */
export interface GetOrgIdpAzureAdOutputArgs {
    /**
     * The ID of this resource.
     */
    id: pulumi.Input<string>;
    /**
     * ID of the organization
     */
    orgId?: pulumi.Input<string | undefined>;
}
