// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Datasource representing the project, which can then be granted to different organizations or users directly, containing different applications.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as std from "@pulumi/std";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = zitadel.getProjectsV2({
 *     orgId: defaultZitadelOrg.id,
 *     name: "example-name",
 *     nameMethod: "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE",
 * });
 * const defaultGetProjectV2 = .reduce((__obj, [__key, __value]) => ({ ...__obj, [String(__key)]: zitadel.getProjectV2({
 *     projectId: __value,
 * }) }), {});
 * export const projectV2Names = std.toset({
 *     input: Object.values(defaultGetProjectV2).map(project => (project.name)),
 * }).result;
 * ```
 */
export function getProjectsV2(args: GetProjectsV2Args, opts?: pulumi.InvokeOptions): Promise<GetProjectsV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zitadel:index/getProjectsV2:getProjectsV2", {
        "name": args.name,
        "nameMethod": args.nameMethod,
        "orgId": args.orgId,
    }, opts);
}

/**
 * A collection of arguments for invoking getProjectsV2.
 */
export interface GetProjectsV2Args {
    /**
     * Name of the project
     */
    name: string;
    /**
     * Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
     */
    nameMethod?: string;
    /**
     * ID of the organization
     */
    orgId?: string;
}

/**
 * A collection of values returned by getProjectsV2.
 */
export interface GetProjectsV2Result {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Name of the project
     */
    readonly name: string;
    /**
     * Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
     */
    readonly nameMethod?: string;
    /**
     * ID of the organization
     */
    readonly orgId?: string;
    /**
     * IDs of the projects matching the name filter.
     */
    readonly projectIds: string[];
}
/**
 * Datasource representing the project, which can then be granted to different organizations or users directly, containing different applications.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as std from "@pulumi/std";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = zitadel.getProjectsV2({
 *     orgId: defaultZitadelOrg.id,
 *     name: "example-name",
 *     nameMethod: "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE",
 * });
 * const defaultGetProjectV2 = .reduce((__obj, [__key, __value]) => ({ ...__obj, [String(__key)]: zitadel.getProjectV2({
 *     projectId: __value,
 * }) }), {});
 * export const projectV2Names = std.toset({
 *     input: Object.values(defaultGetProjectV2).map(project => (project.name)),
 * }).result;
 * ```
 */
export function getProjectsV2Output(args: GetProjectsV2OutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetProjectsV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zitadel:index/getProjectsV2:getProjectsV2", {
        "name": args.name,
        "nameMethod": args.nameMethod,
        "orgId": args.orgId,
    }, opts);
}

/**
 * A collection of arguments for invoking getProjectsV2.
 */
export interface GetProjectsV2OutputArgs {
    /**
     * Name of the project
     */
    name: pulumi.Input<string>;
    /**
     * Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
     */
    nameMethod?: pulumi.Input<string | undefined>;
    /**
     * ID of the organization
     */
    orgId?: pulumi.Input<string | undefined>;
}
