// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource representing an LDAP IDP on the instance.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = new zitadel.IdpLdap("default", {
 *     name: "LDAP",
 *     servers: [
 *         "ldaps://my.primary.server:389",
 *         "ldaps://my.secondary.server:389",
 *     ],
 *     startTls: false,
 *     baseDn: "dc=example,dc=com",
 *     bindDn: "cn=admin,dc=example,dc=com",
 *     bindPassword: "Password1!",
 *     userBase: "dn",
 *     userObjectClasses: ["inetOrgPerson"],
 *     userFilters: [
 *         "uid",
 *         "email",
 *     ],
 *     timeout: "10s",
 *     idAttribute: "uid",
 *     firstNameAttribute: "firstname",
 *     lastNameAttribute: "lastname",
 *     isLinkingAllowed: false,
 *     isCreationAllowed: true,
 *     isAutoCreation: false,
 *     isAutoUpdate: true,
 *     autoLinking: "AUTO_LINKING_OPTION_USERNAME",
 * });
 * ```
 *
 * ## Import
 *
 * The resource can be imported using the ID format `<id[:bind_password]>`, e.g.
 *
 * ```sh
 * $ pulumi import zitadel:index/idpLdap:IdpLdap imported '123456789012345678:b1nd_p4ssw0rd'
 * ```
 */
export class IdpLdap extends pulumi.CustomResource {
    /**
     * Get an existing IdpLdap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdpLdapState, opts?: pulumi.CustomResourceOptions): IdpLdap {
        return new IdpLdap(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zitadel:index/idpLdap:IdpLdap';

    /**
     * Returns true if the given object is an instance of IdpLdap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdpLdap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdpLdap.__pulumiType;
    }

    /**
     * Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
     */
    declare public readonly autoLinking: pulumi.Output<string | undefined>;
    /**
     * User attribute for the avatar url
     */
    declare public readonly avatarUrlAttribute: pulumi.Output<string | undefined>;
    /**
     * Base DN for LDAP connections
     */
    declare public readonly baseDn: pulumi.Output<string>;
    /**
     * Bind DN for LDAP connections
     */
    declare public readonly bindDn: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Bind password for LDAP connections. This value is write-only and is never stored in Terraform state; it cannot be read back or retrieved from a datasource.
     */
    declare public readonly bindPassword: pulumi.Output<string>;
    /**
     * A non-reversible hash of the write-only bind_password, used to detect when the password changes. It does not contain the password itself.
     */
    declare public /*out*/ readonly bindPasswordHash: pulumi.Output<string>;
    /**
     * User attribute for the display name
     */
    declare public readonly displayNameAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the email
     */
    declare public readonly emailAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the email verified state
     */
    declare public readonly emailVerifiedAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the first name
     */
    declare public readonly firstNameAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the id
     */
    declare public readonly idAttribute: pulumi.Output<string | undefined>;
    /**
     * enable if a new account in ZITADEL should be created automatically on login with an external account
     */
    declare public readonly isAutoCreation: pulumi.Output<boolean>;
    /**
     * enable if a the ZITADEL account fields should be updated automatically on each login
     */
    declare public readonly isAutoUpdate: pulumi.Output<boolean>;
    /**
     * enable if users should be able to create a new account in ZITADEL when using an external account
     */
    declare public readonly isCreationAllowed: pulumi.Output<boolean>;
    /**
     * enable if users should be able to link an existing ZITADEL user with an external account
     */
    declare public readonly isLinkingAllowed: pulumi.Output<boolean>;
    /**
     * User attribute for the last name
     */
    declare public readonly lastNameAttribute: pulumi.Output<string | undefined>;
    /**
     * Name of the IDP
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * User attribute for the nick name
     */
    declare public readonly nickNameAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the phone
     */
    declare public readonly phoneAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the phone verified state
     */
    declare public readonly phoneVerifiedAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the preferred language
     */
    declare public readonly preferredLanguageAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the preferred username
     */
    declare public readonly preferredUsernameAttribute: pulumi.Output<string | undefined>;
    /**
     * User attribute for the profile
     */
    declare public readonly profileAttribute: pulumi.Output<string | undefined>;
    /**
     * Root CA for self-signed certificates for TLS connections to LDAP servers. It is intended to be filled with the contents of a .pem file.
     */
    declare public readonly rootCa: pulumi.Output<string>;
    /**
     * Servers to try in order for establishing LDAP connections
     */
    declare public readonly servers: pulumi.Output<string[]>;
    /**
     * Wether to use StartTLS for LDAP connections
     */
    declare public readonly startTls: pulumi.Output<boolean>;
    /**
     * Timeout for LDAP connections
     */
    declare public readonly timeout: pulumi.Output<string>;
    /**
     * User base for LDAP connections
     */
    declare public readonly userBase: pulumi.Output<string>;
    /**
     * User filters for LDAP connections
     */
    declare public readonly userFilters: pulumi.Output<string[]>;
    /**
     * User object classes for LDAP connections
     */
    declare public readonly userObjectClasses: pulumi.Output<string[]>;

    /**
     * Create a IdpLdap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdpLdapArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdpLdapArgs | IdpLdapState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdpLdapState | undefined;
            resourceInputs["autoLinking"] = state?.autoLinking;
            resourceInputs["avatarUrlAttribute"] = state?.avatarUrlAttribute;
            resourceInputs["baseDn"] = state?.baseDn;
            resourceInputs["bindDn"] = state?.bindDn;
            resourceInputs["bindPassword"] = state?.bindPassword;
            resourceInputs["bindPasswordHash"] = state?.bindPasswordHash;
            resourceInputs["displayNameAttribute"] = state?.displayNameAttribute;
            resourceInputs["emailAttribute"] = state?.emailAttribute;
            resourceInputs["emailVerifiedAttribute"] = state?.emailVerifiedAttribute;
            resourceInputs["firstNameAttribute"] = state?.firstNameAttribute;
            resourceInputs["idAttribute"] = state?.idAttribute;
            resourceInputs["isAutoCreation"] = state?.isAutoCreation;
            resourceInputs["isAutoUpdate"] = state?.isAutoUpdate;
            resourceInputs["isCreationAllowed"] = state?.isCreationAllowed;
            resourceInputs["isLinkingAllowed"] = state?.isLinkingAllowed;
            resourceInputs["lastNameAttribute"] = state?.lastNameAttribute;
            resourceInputs["name"] = state?.name;
            resourceInputs["nickNameAttribute"] = state?.nickNameAttribute;
            resourceInputs["phoneAttribute"] = state?.phoneAttribute;
            resourceInputs["phoneVerifiedAttribute"] = state?.phoneVerifiedAttribute;
            resourceInputs["preferredLanguageAttribute"] = state?.preferredLanguageAttribute;
            resourceInputs["preferredUsernameAttribute"] = state?.preferredUsernameAttribute;
            resourceInputs["profileAttribute"] = state?.profileAttribute;
            resourceInputs["rootCa"] = state?.rootCa;
            resourceInputs["servers"] = state?.servers;
            resourceInputs["startTls"] = state?.startTls;
            resourceInputs["timeout"] = state?.timeout;
            resourceInputs["userBase"] = state?.userBase;
            resourceInputs["userFilters"] = state?.userFilters;
            resourceInputs["userObjectClasses"] = state?.userObjectClasses;
        } else {
            const args = argsOrState as IdpLdapArgs | undefined;
            if (args?.baseDn === undefined && !opts.urn) {
                throw new Error("Missing required property 'baseDn'");
            }
            if (args?.bindDn === undefined && !opts.urn) {
                throw new Error("Missing required property 'bindDn'");
            }
            if (args?.bindPassword === undefined && !opts.urn) {
                throw new Error("Missing required property 'bindPassword'");
            }
            if (args?.isAutoCreation === undefined && !opts.urn) {
                throw new Error("Missing required property 'isAutoCreation'");
            }
            if (args?.isAutoUpdate === undefined && !opts.urn) {
                throw new Error("Missing required property 'isAutoUpdate'");
            }
            if (args?.isCreationAllowed === undefined && !opts.urn) {
                throw new Error("Missing required property 'isCreationAllowed'");
            }
            if (args?.isLinkingAllowed === undefined && !opts.urn) {
                throw new Error("Missing required property 'isLinkingAllowed'");
            }
            if (args?.servers === undefined && !opts.urn) {
                throw new Error("Missing required property 'servers'");
            }
            if (args?.startTls === undefined && !opts.urn) {
                throw new Error("Missing required property 'startTls'");
            }
            if (args?.timeout === undefined && !opts.urn) {
                throw new Error("Missing required property 'timeout'");
            }
            if (args?.userBase === undefined && !opts.urn) {
                throw new Error("Missing required property 'userBase'");
            }
            if (args?.userFilters === undefined && !opts.urn) {
                throw new Error("Missing required property 'userFilters'");
            }
            if (args?.userObjectClasses === undefined && !opts.urn) {
                throw new Error("Missing required property 'userObjectClasses'");
            }
            resourceInputs["autoLinking"] = args?.autoLinking;
            resourceInputs["avatarUrlAttribute"] = args?.avatarUrlAttribute;
            resourceInputs["baseDn"] = args?.baseDn;
            resourceInputs["bindDn"] = args?.bindDn;
            resourceInputs["bindPassword"] = args?.bindPassword ? pulumi.secret(args.bindPassword) : undefined;
            resourceInputs["displayNameAttribute"] = args?.displayNameAttribute;
            resourceInputs["emailAttribute"] = args?.emailAttribute;
            resourceInputs["emailVerifiedAttribute"] = args?.emailVerifiedAttribute;
            resourceInputs["firstNameAttribute"] = args?.firstNameAttribute;
            resourceInputs["idAttribute"] = args?.idAttribute;
            resourceInputs["isAutoCreation"] = args?.isAutoCreation;
            resourceInputs["isAutoUpdate"] = args?.isAutoUpdate;
            resourceInputs["isCreationAllowed"] = args?.isCreationAllowed;
            resourceInputs["isLinkingAllowed"] = args?.isLinkingAllowed;
            resourceInputs["lastNameAttribute"] = args?.lastNameAttribute;
            resourceInputs["name"] = args?.name;
            resourceInputs["nickNameAttribute"] = args?.nickNameAttribute;
            resourceInputs["phoneAttribute"] = args?.phoneAttribute;
            resourceInputs["phoneVerifiedAttribute"] = args?.phoneVerifiedAttribute;
            resourceInputs["preferredLanguageAttribute"] = args?.preferredLanguageAttribute;
            resourceInputs["preferredUsernameAttribute"] = args?.preferredUsernameAttribute;
            resourceInputs["profileAttribute"] = args?.profileAttribute;
            resourceInputs["rootCa"] = args?.rootCa;
            resourceInputs["servers"] = args?.servers;
            resourceInputs["startTls"] = args?.startTls;
            resourceInputs["timeout"] = args?.timeout;
            resourceInputs["userBase"] = args?.userBase;
            resourceInputs["userFilters"] = args?.userFilters;
            resourceInputs["userObjectClasses"] = args?.userObjectClasses;
            resourceInputs["bindPasswordHash"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["bindPassword", "bindPasswordHash"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IdpLdap.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IdpLdap resources.
 */
export interface IdpLdapState {
    /**
     * Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
     */
    autoLinking?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the avatar url
     */
    avatarUrlAttribute?: pulumi.Input<string | undefined>;
    /**
     * Base DN for LDAP connections
     */
    baseDn?: pulumi.Input<string | undefined>;
    /**
     * Bind DN for LDAP connections
     */
    bindDn?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Bind password for LDAP connections. This value is write-only and is never stored in Terraform state; it cannot be read back or retrieved from a datasource.
     */
    bindPassword?: pulumi.Input<string | undefined>;
    /**
     * A non-reversible hash of the write-only bind_password, used to detect when the password changes. It does not contain the password itself.
     */
    bindPasswordHash?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the display name
     */
    displayNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the email
     */
    emailAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the email verified state
     */
    emailVerifiedAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the first name
     */
    firstNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the id
     */
    idAttribute?: pulumi.Input<string | undefined>;
    /**
     * enable if a new account in ZITADEL should be created automatically on login with an external account
     */
    isAutoCreation?: pulumi.Input<boolean | undefined>;
    /**
     * enable if a the ZITADEL account fields should be updated automatically on each login
     */
    isAutoUpdate?: pulumi.Input<boolean | undefined>;
    /**
     * enable if users should be able to create a new account in ZITADEL when using an external account
     */
    isCreationAllowed?: pulumi.Input<boolean | undefined>;
    /**
     * enable if users should be able to link an existing ZITADEL user with an external account
     */
    isLinkingAllowed?: pulumi.Input<boolean | undefined>;
    /**
     * User attribute for the last name
     */
    lastNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * Name of the IDP
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the nick name
     */
    nickNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the phone
     */
    phoneAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the phone verified state
     */
    phoneVerifiedAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the preferred language
     */
    preferredLanguageAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the preferred username
     */
    preferredUsernameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the profile
     */
    profileAttribute?: pulumi.Input<string | undefined>;
    /**
     * Root CA for self-signed certificates for TLS connections to LDAP servers. It is intended to be filled with the contents of a .pem file.
     */
    rootCa?: pulumi.Input<string | undefined>;
    /**
     * Servers to try in order for establishing LDAP connections
     */
    servers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Wether to use StartTLS for LDAP connections
     */
    startTls?: pulumi.Input<boolean | undefined>;
    /**
     * Timeout for LDAP connections
     */
    timeout?: pulumi.Input<string | undefined>;
    /**
     * User base for LDAP connections
     */
    userBase?: pulumi.Input<string | undefined>;
    /**
     * User filters for LDAP connections
     */
    userFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * User object classes for LDAP connections
     */
    userObjectClasses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a IdpLdap resource.
 */
export interface IdpLdapArgs {
    /**
     * Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
     */
    autoLinking?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the avatar url
     */
    avatarUrlAttribute?: pulumi.Input<string | undefined>;
    /**
     * Base DN for LDAP connections
     */
    baseDn: pulumi.Input<string>;
    /**
     * Bind DN for LDAP connections
     */
    bindDn: pulumi.Input<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Bind password for LDAP connections. This value is write-only and is never stored in Terraform state; it cannot be read back or retrieved from a datasource.
     */
    bindPassword: pulumi.Input<string>;
    /**
     * User attribute for the display name
     */
    displayNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the email
     */
    emailAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the email verified state
     */
    emailVerifiedAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the first name
     */
    firstNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the id
     */
    idAttribute?: pulumi.Input<string | undefined>;
    /**
     * enable if a new account in ZITADEL should be created automatically on login with an external account
     */
    isAutoCreation: pulumi.Input<boolean>;
    /**
     * enable if a the ZITADEL account fields should be updated automatically on each login
     */
    isAutoUpdate: pulumi.Input<boolean>;
    /**
     * enable if users should be able to create a new account in ZITADEL when using an external account
     */
    isCreationAllowed: pulumi.Input<boolean>;
    /**
     * enable if users should be able to link an existing ZITADEL user with an external account
     */
    isLinkingAllowed: pulumi.Input<boolean>;
    /**
     * User attribute for the last name
     */
    lastNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * Name of the IDP
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the nick name
     */
    nickNameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the phone
     */
    phoneAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the phone verified state
     */
    phoneVerifiedAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the preferred language
     */
    preferredLanguageAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the preferred username
     */
    preferredUsernameAttribute?: pulumi.Input<string | undefined>;
    /**
     * User attribute for the profile
     */
    profileAttribute?: pulumi.Input<string | undefined>;
    /**
     * Root CA for self-signed certificates for TLS connections to LDAP servers. It is intended to be filled with the contents of a .pem file.
     */
    rootCa?: pulumi.Input<string | undefined>;
    /**
     * Servers to try in order for establishing LDAP connections
     */
    servers: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Wether to use StartTLS for LDAP connections
     */
    startTls: pulumi.Input<boolean>;
    /**
     * Timeout for LDAP connections
     */
    timeout: pulumi.Input<string>;
    /**
     * User base for LDAP connections
     */
    userBase: pulumi.Input<string>;
    /**
     * User filters for LDAP connections
     */
    userFilters: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * User object classes for LDAP connections
     */
    userObjectClasses: pulumi.Input<pulumi.Input<string>[]>;
}
