// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource representing a Google IdP on the organization.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = new zitadel.OrgIdpGoogle("default", {
 *     orgId: defaultZitadelOrg.id,
 *     name: "Google",
 *     clientId: "182902...",
 *     clientSecret: "GOCSPX-*****",
 *     scopes: [
 *         "openid",
 *         "profile",
 *         "email",
 *     ],
 *     isLinkingAllowed: false,
 *     isCreationAllowed: true,
 *     isAutoCreation: false,
 *     isAutoUpdate: true,
 *     autoLinking: "AUTO_LINKING_OPTION_USERNAME",
 * });
 * ```
 *
 * ## Import
 *
 * The resource can be imported using the ID format `<id[:org_id][:client_secret]>`, e.g.
 *
 * ```sh
 * $ pulumi import zitadel:index/orgIdpGoogle:OrgIdpGoogle imported '123456789012345678:123456789012345678:G1234567890123'
 * ```
 */
export class OrgIdpGoogle extends pulumi.CustomResource {
    /**
     * Get an existing OrgIdpGoogle resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrgIdpGoogleState, opts?: pulumi.CustomResourceOptions): OrgIdpGoogle {
        return new OrgIdpGoogle(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zitadel:index/orgIdpGoogle:OrgIdpGoogle';

    /**
     * Returns true if the given object is an instance of OrgIdpGoogle.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrgIdpGoogle {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrgIdpGoogle.__pulumiType;
    }

    /**
     * Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
     */
    declare public readonly autoLinking: pulumi.Output<string | undefined>;
    /**
     * client id generated by the identity provider
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * client secret generated by the identity provider. This value is write-only and is never stored in Terraform state; it cannot be read back or retrieved from a datasource.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * A non-reversible hash of the write-only client_secret, used to detect when the secret changes. It does not contain the secret itself.
     */
    declare public /*out*/ readonly clientSecretHash: pulumi.Output<string>;
    /**
     * enable if a new account in ZITADEL should be created automatically on login with an external account
     */
    declare public readonly isAutoCreation: pulumi.Output<boolean>;
    /**
     * enable if a the ZITADEL account fields should be updated automatically on each login
     */
    declare public readonly isAutoUpdate: pulumi.Output<boolean>;
    /**
     * enable if users should be able to create a new account in ZITADEL when using an external account
     */
    declare public readonly isCreationAllowed: pulumi.Output<boolean>;
    /**
     * enable if users should be able to link an existing ZITADEL user with an external account
     */
    declare public readonly isLinkingAllowed: pulumi.Output<boolean>;
    /**
     * Name of the IDP
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * ID of the organization. If not provided, the organization of the authenticated user/service account is used.
     */
    declare public readonly orgId: pulumi.Output<string | undefined>;
    /**
     * the scopes requested by ZITADEL during the request on the identity provider
     */
    declare public readonly scopes: pulumi.Output<string[] | undefined>;

    /**
     * Create a OrgIdpGoogle resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrgIdpGoogleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrgIdpGoogleArgs | OrgIdpGoogleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrgIdpGoogleState | undefined;
            resourceInputs["autoLinking"] = state?.autoLinking;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["clientSecret"] = state?.clientSecret;
            resourceInputs["clientSecretHash"] = state?.clientSecretHash;
            resourceInputs["isAutoCreation"] = state?.isAutoCreation;
            resourceInputs["isAutoUpdate"] = state?.isAutoUpdate;
            resourceInputs["isCreationAllowed"] = state?.isCreationAllowed;
            resourceInputs["isLinkingAllowed"] = state?.isLinkingAllowed;
            resourceInputs["name"] = state?.name;
            resourceInputs["orgId"] = state?.orgId;
            resourceInputs["scopes"] = state?.scopes;
        } else {
            const args = argsOrState as OrgIdpGoogleArgs | undefined;
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.isAutoCreation === undefined && !opts.urn) {
                throw new Error("Missing required property 'isAutoCreation'");
            }
            if (args?.isAutoUpdate === undefined && !opts.urn) {
                throw new Error("Missing required property 'isAutoUpdate'");
            }
            if (args?.isCreationAllowed === undefined && !opts.urn) {
                throw new Error("Missing required property 'isCreationAllowed'");
            }
            if (args?.isLinkingAllowed === undefined && !opts.urn) {
                throw new Error("Missing required property 'isLinkingAllowed'");
            }
            resourceInputs["autoLinking"] = args?.autoLinking;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["isAutoCreation"] = args?.isAutoCreation;
            resourceInputs["isAutoUpdate"] = args?.isAutoUpdate;
            resourceInputs["isCreationAllowed"] = args?.isCreationAllowed;
            resourceInputs["isLinkingAllowed"] = args?.isLinkingAllowed;
            resourceInputs["name"] = args?.name;
            resourceInputs["orgId"] = args?.orgId;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["clientSecretHash"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret", "clientSecretHash"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OrgIdpGoogle.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OrgIdpGoogle resources.
 */
export interface OrgIdpGoogleState {
    /**
     * Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
     */
    autoLinking?: pulumi.Input<string | undefined>;
    /**
     * client id generated by the identity provider
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * client secret generated by the identity provider. This value is write-only and is never stored in Terraform state; it cannot be read back or retrieved from a datasource.
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * A non-reversible hash of the write-only client_secret, used to detect when the secret changes. It does not contain the secret itself.
     */
    clientSecretHash?: pulumi.Input<string | undefined>;
    /**
     * enable if a new account in ZITADEL should be created automatically on login with an external account
     */
    isAutoCreation?: pulumi.Input<boolean | undefined>;
    /**
     * enable if a the ZITADEL account fields should be updated automatically on each login
     */
    isAutoUpdate?: pulumi.Input<boolean | undefined>;
    /**
     * enable if users should be able to create a new account in ZITADEL when using an external account
     */
    isCreationAllowed?: pulumi.Input<boolean | undefined>;
    /**
     * enable if users should be able to link an existing ZITADEL user with an external account
     */
    isLinkingAllowed?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the IDP
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * ID of the organization. If not provided, the organization of the authenticated user/service account is used.
     */
    orgId?: pulumi.Input<string | undefined>;
    /**
     * the scopes requested by ZITADEL during the request on the identity provider
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a OrgIdpGoogle resource.
 */
export interface OrgIdpGoogleArgs {
    /**
     * Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
     */
    autoLinking?: pulumi.Input<string | undefined>;
    /**
     * client id generated by the identity provider
     */
    clientId: pulumi.Input<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * client secret generated by the identity provider. This value is write-only and is never stored in Terraform state; it cannot be read back or retrieved from a datasource.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * enable if a new account in ZITADEL should be created automatically on login with an external account
     */
    isAutoCreation: pulumi.Input<boolean>;
    /**
     * enable if a the ZITADEL account fields should be updated automatically on each login
     */
    isAutoUpdate: pulumi.Input<boolean>;
    /**
     * enable if users should be able to create a new account in ZITADEL when using an external account
     */
    isCreationAllowed: pulumi.Input<boolean>;
    /**
     * enable if users should be able to link an existing ZITADEL user with an external account
     */
    isLinkingAllowed: pulumi.Input<boolean>;
    /**
     * Name of the IDP
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * ID of the organization. If not provided, the organization of the authenticated user/service account is used.
     */
    orgId?: pulumi.Input<string | undefined>;
    /**
     * the scopes requested by ZITADEL during the request on the identity provider
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
