// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Resource representing the feature flags configuration for the system.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zitadel from "@scoretechnologies/zitadel";
 *
 * const _default = new zitadel.SystemFeatures("default", {
 *     loginDefaultOrg: true,
 *     oidcTokenExchange: true,
 *     userSchema: false,
 *     improvedPerformances: [
 *         "IMPROVED_PERFORMANCE_PROJECT_GRANT",
 *         "IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED",
 *     ],
 *     oidcSingleV1SessionTermination: true,
 *     enableBackChannelLogout: true,
 *     loginV2: {
 *         required: true,
 *         baseUri: "https://login.example.com",
 *     }[0],
 *     permissionCheckV2: true,
 * });
 * ```
 *
 * ## Import
 *
 * The resource can be imported using the constant ID "system"
 *
 * ```sh
 * $ pulumi import zitadel:index/systemFeatures:SystemFeatures imported 'system'
 * ```
 */
export class SystemFeatures extends pulumi.CustomResource {
    /**
     * Get an existing SystemFeatures resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SystemFeaturesState, opts?: pulumi.CustomResourceOptions): SystemFeatures {
        return new SystemFeatures(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zitadel:index/systemFeatures:SystemFeatures';

    /**
     * Returns true if the given object is an instance of SystemFeatures.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SystemFeatures {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SystemFeatures.__pulumiType;
    }

    /**
     * If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
     */
    declare public readonly enableBackChannelLogout: pulumi.Output<boolean>;
    /**
     * Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
     */
    declare public readonly improvedPerformances: pulumi.Output<string[]>;
    /**
     * The login UI will use the settings of the default org (and not from the instance) if no organization context is set
     */
    declare public readonly loginDefaultOrg: pulumi.Output<boolean>;
    /**
     * Specify the login UI for all users and applications regardless of their preference.
     */
    declare public readonly loginV2: pulumi.Output<outputs.SystemFeaturesLoginV2>;
    /**
     * If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
     */
    declare public readonly oidcSingleV1SessionTermination: pulumi.Output<boolean>;
    /**
     * Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
     */
    declare public readonly oidcTokenExchange: pulumi.Output<boolean>;
    /**
     * Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
     */
    declare public readonly permissionCheckV2: pulumi.Output<boolean>;
    /**
     * User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
     */
    declare public readonly userSchema: pulumi.Output<boolean>;

    /**
     * Create a SystemFeatures resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SystemFeaturesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SystemFeaturesArgs | SystemFeaturesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SystemFeaturesState | undefined;
            resourceInputs["enableBackChannelLogout"] = state?.enableBackChannelLogout;
            resourceInputs["improvedPerformances"] = state?.improvedPerformances;
            resourceInputs["loginDefaultOrg"] = state?.loginDefaultOrg;
            resourceInputs["loginV2"] = state?.loginV2;
            resourceInputs["oidcSingleV1SessionTermination"] = state?.oidcSingleV1SessionTermination;
            resourceInputs["oidcTokenExchange"] = state?.oidcTokenExchange;
            resourceInputs["permissionCheckV2"] = state?.permissionCheckV2;
            resourceInputs["userSchema"] = state?.userSchema;
        } else {
            const args = argsOrState as SystemFeaturesArgs | undefined;
            resourceInputs["enableBackChannelLogout"] = args?.enableBackChannelLogout;
            resourceInputs["improvedPerformances"] = args?.improvedPerformances;
            resourceInputs["loginDefaultOrg"] = args?.loginDefaultOrg;
            resourceInputs["loginV2"] = args?.loginV2;
            resourceInputs["oidcSingleV1SessionTermination"] = args?.oidcSingleV1SessionTermination;
            resourceInputs["oidcTokenExchange"] = args?.oidcTokenExchange;
            resourceInputs["permissionCheckV2"] = args?.permissionCheckV2;
            resourceInputs["userSchema"] = args?.userSchema;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SystemFeatures.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SystemFeatures resources.
 */
export interface SystemFeaturesState {
    /**
     * If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
     */
    enableBackChannelLogout?: pulumi.Input<boolean | undefined>;
    /**
     * Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
     */
    improvedPerformances?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The login UI will use the settings of the default org (and not from the instance) if no organization context is set
     */
    loginDefaultOrg?: pulumi.Input<boolean | undefined>;
    /**
     * Specify the login UI for all users and applications regardless of their preference.
     */
    loginV2?: pulumi.Input<inputs.SystemFeaturesLoginV2 | undefined>;
    /**
     * If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
     */
    oidcSingleV1SessionTermination?: pulumi.Input<boolean | undefined>;
    /**
     * Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
     */
    oidcTokenExchange?: pulumi.Input<boolean | undefined>;
    /**
     * Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
     */
    permissionCheckV2?: pulumi.Input<boolean | undefined>;
    /**
     * User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
     */
    userSchema?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a SystemFeatures resource.
 */
export interface SystemFeaturesArgs {
    /**
     * If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
     */
    enableBackChannelLogout?: pulumi.Input<boolean | undefined>;
    /**
     * Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
     */
    improvedPerformances?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The login UI will use the settings of the default org (and not from the instance) if no organization context is set
     */
    loginDefaultOrg?: pulumi.Input<boolean | undefined>;
    /**
     * Specify the login UI for all users and applications regardless of their preference.
     */
    loginV2?: pulumi.Input<inputs.SystemFeaturesLoginV2 | undefined>;
    /**
     * If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
     */
    oidcSingleV1SessionTermination?: pulumi.Input<boolean | undefined>;
    /**
     * Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
     */
    oidcTokenExchange?: pulumi.Input<boolean | undefined>;
    /**
     * Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
     */
    permissionCheckV2?: pulumi.Input<boolean | undefined>;
    /**
     * User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
     */
    userSchema?: pulumi.Input<boolean | undefined>;
}
